### ISSUE TITLE
instruction retired problem

### ISSUE THREAD

**Issue by MohammedAl-hayanni** [RRZE-HPC/likwid#101]
I am trying to run PARSEC benchmark with likwid-perfctr and scale the time with -t 200ms. I have used -c to pin all the cores Core 0 - Core 3. I have found the instruction retired performance counter still read 000.00E00 for Core 0.
how can I have get the correct reading for Core 0

**Comment by TomTheBear** [comment]
`-c` is **without** pinning, so try with `-C`.

**Comment by MohammedAl-hayanni** [comment]
Thank you TomTheBear, I have used this script

likwid-perfctr -c N:0-3 -g CLOCK -O -t 200ms likwid-pin -c 0-1 ./parsec-3.0/pkgs/kernels/canneal/inst/amd64-linux.gcc-pthreads/bin/canneal 2 15000 2000 /home/configure/parsec-3.0/pkgs/kernels/canneal/inputs/2500000.nets 6000 > cannea2th37RTM.csv
 so should I change all -c to -C

**Comment by TomTheBear** [comment]
Yes change `-c` to `-C` and leave out `likwid-pin`:
`
likwid-perfctr -C N:0-3 -g CLOCK -O -t 200ms ./parsec-3.0/pkgs/kernels/canneal/inst/amd64-linux.gcc-pthreads/bin/canneal 2 15000 2000 /home/configure/parsec-3.0/pkgs/kernels/canneal/inputs/2500000.nets 6000 > cannea2th37RTM.csv
`
In your call, you selected the CPUs _logically_ indexed 0-3 in affinity domain N for likwid-perfctr but likwid-pin pins the application to the CPUs _physically_ indexed 0-1. This probably works but it is not guaranteed as physical CPUs `0-1` might not be in the selection `N:0-3`. They commonly are but just as a remark.
You can run `likwid-pin -c <selection> -p` to get the CPU numbers that are used for your selection.

**Comment by TomTheBear** [comment]
Do you still have problems or can we close this issue?

**Comment by MohammedAl-hayanni** [comment]
you can close it , the problem solved
