### ISSUE TITLE
Help with likwid-perfctr

### ISSUE THREAD

**Issue by s0nskar** [RRZE-HPC/likwid#105]
This is not an bug. I needed a little help with the `likwid-perfctr` library. What I want to do is able to add hooks in the code to measure the **Clock [MHz], Branch rate and Branch prediction ratio** by adding hooks in code like.
```cpp
int main() {
   start_measuring();
   // Doing something
   stop_measuring();
}
```
And this should output the Clock [MHz], Branch Rate and Branch Prediction value. I saw the C++ API example provided on this [link](http://rrze-hpc.github.io/likwid/Doxygen/C-likwidAPI-code.html). And following the same I can get result value (__is result value is clock value?__) then how to get remaining ones i.e branch rate and branch prediction rate. 

Thanks

**Comment by TomTheBear** [comment]
See duplicate on likwid-users mailing list:
https://groups.google.com/d/msg/likwid-users/9R-zhnyv1sw/sgWxbPR8AAAJ

**Comment by s0nskar** [comment]
Thanks @TomTheBear
