### ISSUE TITLE
likwid-agent and GroupString

### ISSUE THREAD

**Issue by jpecar** [RRZE-HPC/likwid#107]
I'm trying to make likwid-agent push numbers to gmetric. Upon startup, I get:
likwid-lua: likwid-agent:302: attempt to index a nil value (local 'gdata')

Similar if I want to write to local files, just some lines higher (226). 

Outputting to syslog works, tho.

It seems there's an unused variable GroupString involved and it is not clear to me how it is supposed to be used. Should it be an element of groupStrings array? Or something else?

**Comment by TomTheBear** [comment]
The likwid-agent is somewhat outdated. It was just a test for monitoring using the hardware counters.

The cause of the error is probably, that the group/eventset handling was moved to the C-library and not handled in Lua anymore.
If you hand over the group id to the function, you can take the element on the groupStrings array at index 'group id'. Moreover, for simplicity, I would comment out the addition of the 'group' option to gmetric. 

I will update the code as soon as I have time. Of course, you can do it yourself. I would appreciate getting the patch then.
