### ISSUE TITLE
Measuring kernel that uses openMP

### ISSUE THREAD

**Issue by elReynerino** [RRZE-HPC/likwid#108]
Hi,

I'm trying to measure several kernels of MiniAero, a benchmark simulation of the Mantevo Suite. The problem is, that the parallelization is done with kokkos, a library that relizes portable performance with template meta programming. As such I'm  not able to place the Markers for likwid-perfctr at the right positions in the template code.

So I tried it like the  tutorial for the marker api in the wiki here: https://github.com/RRZE-HPC/likwid/wiki/TutorialMarkerC

This code runs perfectly fine.

Similar code in Mini Aero:

template <typename Device>
void TimeSolverExplicitRK4<Device>::Solve()
{
	LIKWID_MARKER_INIT;
	#pragma omp parallel
	{
		LIKWID_MARKER_THREADINIT;
	}
.
.
.
#pragma omp parallel
	{
	LIKWID_MARKER_START("Gauss");
	//gauss_t -= __rdtsc();
        //Compute Gradients and Limiters
        if(options_.second_order_space || options_.viscous){
          green_gauss_gradient.compute_gradients(sol_temp_vec, gradients);
#ifdef WITH_MPI
          green_gauss_gradient.communicate_gradients(gradients);
#endif
        }
	//gauss_t += __rdtsc();
	LIKWID_MARKER_STOP("Gauss");
	}
.
.
.
        LIKWID_MARKER_CLOSE;
}

This produces following error:

$ likwid-perfctr -C S0:0-7 -f -m -g MEM ../../miniAero.likwid
--------------------------------------------------------------------------------
CPU name:       Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
CPU type:       Intel Xeon IvyBridge EN/EP/EX processor
CPU clock:      2.60 GHz
--------------------------------------------------------------------------------

 ... Face creation time:     1.00 seconds ...

 ... Extract BC face and delete ghost time:     0.00 seconds ...

 CPU Memory Usage (Current, High Water) - after mesh setup: 140 MB, 219 MB
 ... Setup time:     1.00 seconds ...
terminate called after throwing an instance of 'terminate called recursively
terminate called recursively
terminate called recursively
--------------------------------------------------------------------------------
No regions could be found in Marker API result file

So what am I doing wrong, or is there another way to measure the threads?

**Comment by TomTheBear** [comment]
Hi,
I did a check on miniAero and for me it works fine:
```
$ likwid-perfctr -C 0 -g BRANCH -m ./miniaero.exe 
--------------------------------------------------------------------------------
CPU name:	Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
CPU type:	Intel Core Haswell processor
CPU clock:	3.39 GHz
--------------------------------------------------------------------------------

 ... Face creation time:     0.00 seconds ...

 ... Extract BC face and delete ghost time:     0.00 seconds ...

 ... Setup time:     0.00 seconds ...

Time Step #100:  Time =  2.000000000e-04; dt =  2.000000000e-06

 ... Device Run time:     3.00 seconds ...

 ... Total elapsed time:     3.00 seconds ...
--------------------------------------------------------------------------------
Region Gauss, Group 1: BRANCH
+-------------------+----------+
|    Region Info    |  Core 0  |
+-------------------+----------+
| RDTSC Runtime [s] | 0.000046 |
|     call count    |      400 |
+-------------------+----------+

+------------------------------+---------+---------+
|             Event            | Counter |  Core 0 |
+------------------------------+---------+---------+
|       INSTR_RETIRED_ANY      |  FIXC0  | 1375528 |
|     CPU_CLK_UNHALTED_CORE    |  FIXC1  | 3277333 |
|     CPU_CLK_UNHALTED_REF     |  FIXC2  | 2857292 |
| BR_INST_RETIRED_ALL_BRANCHES |   PMC0  |  310901 |
| BR_MISP_RETIRED_ALL_BRANCHES |   PMC1  |    6490 |
+------------------------------+---------+---------+

+----------------------------+--------------+
|           Metric           |    Core 0    |
+----------------------------+--------------+
|     Runtime (RDTSC) [s]    | 4.592200e-05 |
|    Runtime unhalted [s]    |       0.0010 |
|         Clock [MHz]        |    3890.8646 |
|             CPI            |       2.3826 |
|         Branch rate        |       0.2260 |
|  Branch misprediction rate |       0.0047 |
| Branch misprediction ratio |       0.0209 |
|   Instructions per branch  |       4.4243 |
+----------------------------+--------------+
```
Since I commonly don't use cmake, it was a little bit of pain to add LIKWID to it but it works.

Please check you compilation whether it sets -DLIKWID_PERFMON properly (activates the macros). Moreover, I would suggest to run the LIKWID_MARKER_INIT at the constructor and LIKWID_MARKER_CLOSE at the destructor. For the test, I added them like you did : all LIKWID calls in Solve()

I don't know how you configured it, but in my case OpenMP was not possible because kokkos was configured with Pthreads and I didn't get OpenMP to fly.  So no OpenMP pragmas.

**Comment by elReynerino** [comment]
I'm using MiniAero from  github and not from the Mantevo website as th latter one seemed to have a few bugs and didn't compile without mpi.
But this shouldn't be the problem here...

The version from  github doesn't use cmake, so i just added all required options for likwid to the CXXFLAGS in the makefile like described in the likwid wiki for the marker api with likwid-perfctr.
I still don't know why it doesn't work with openMP like the example from the wiki showed. So i tried to compile kokkos with pthreads instead. I don't have much experience with pthreads, so i don't know how it works propperly, but kokkos seems to only use a  single thread with pthreads enabled (set KOKKOS_DEVICES=Pthreads in the makefile). Is there an environment variable that tells it how many threads are available?

And I didn't quite undestand which constructor and destructor you meant for LIKWID_MARKER_INIT and LIKWID_MARKER_CLOSE.

**Comment by TomTheBear** [comment]
So, you mean https://github.com/Mantevo/miniAero ? When you download the release there (1.0.0), it is the cmaks version. The master in the repository is the non-cmake version.
 
Looking at the Makefile (non-cmake) I would say you need:
```
CXXFLAGS=[...] -L<likwid-lib-dir> -I <likwid-include-dir> -DLIKWID_PERFMON
LINKFLAGS=-llikwid
LIB=-llikwid
```
The file `TimeSolverExplicitRK4.c` contains the class definition of the TimeSolverExplicitRK4 class. Each class has a constructor (executed when you create a class instance) and a destructor (called when you free/delete/close the class). The function `Solve()` is a class function, so you can initialize LIKWID in the constructor, close it in the destructor and use it in the class fuction. 

LIKWID doesn't care who (OpenMP, Pthreads, C++11 threads) creates the threads as long as they call `pthread_create` to create new threads. Moreover, they have to be pinned (done by `likwid-perfctr` with capital C). I don't know how you specify the number of threads with kokkos. Pthreads commonly doesn't use an environment variable to control the number. According to the README (https://github.com/Mantevo/miniAero/blob/master/kokkos/README#L60) you can run it either serial or MPI-parallel.

**Comment by elReynerino** [comment]
Thanks for all your help.
Measuring with the marker api is no problem in serial, it just didn't work to measure multiple threads simultaneously.

I had another idea for openMP:
Can I measure like this?
```
#pragma omp parallel
{
    LIKWID_MARKER_START("Gauss");
}

...  parallel Kernel...

#pragma omp parallel
{
    LIKWID_MARKER_STOP("Gauss");
}
```
Or does this break anything and measure ony irellevant stuff?
I tried it just now and it seemed to work...

**Comment by TomTheBear** [comment]
This a common way to use LIKWID when you cannot control the threads in the 'parallel kernel' e.g. in Intel MKL.

**Comment by elReynerino** [comment]
So this should produce proper measurements? It seems kind of strange to me, that only core 0 has memory bandwidth and the other none at all.

**Comment by TomTheBear** [comment]
Yes, the results should be fine. Memory controllers and other Uncore Devices are specific for a CPU socket. You cannot refer back to single Cores. If you want that, you can try (if available) the NUMA group which uses other events and counters. These events are core-specific but the results are not as accurate as the measurements from the memory controllers

**Comment by TomTheBear** [comment]
Any further problems or can we close this issue?

**Comment by elReynerino** [comment]
No, my measurements are looking fine,  i think this issue is solved.

**Comment by TomTheBear** [comment]
OK, grad to read that.
