### ISSUE TITLE
Help to understand likwid-perfctr with marker API

### ISSUE THREAD

**Issue by aoloso** [RRZE-HPC/likwid#113]
Two source files are attached for a variant of the STREAM (with OpenMP) benchmark - one with likwid-perfctr marker API and one without (just to show the difference before and after).
The modified file is built with:
icc -O3 -xCORE-AVX2 -ffreestanding -qopenmp -pthread -DSTREAM_ARRAY_SIZE=300000000 -DLIKWID_PERFMON -o stream_5_10_second stream_5-10_posix_memalign_markerAPI.c -llikwid -lm

The executable is run for the MEM event group (on 28-core, 2-socket Haswell node) as:
likwid-perfctr -C 0-27 -g MEM ./stream_5_10_second
The output of that run is attached as MEM_base.out

The same executable is run for the MEM event group but with the marker API activated as:
likwid-perfctr -C 0-27 -g MEM -m ./stream_5_10_second
The output is attached as MEM_markerAPI.out

The problem is that when the marker API is activated, it seems as if memory bandwidth is being computed only for the first socket and not the second. This appears not to be correct since all 28 cores are being used. Also, the bandwidth is computed for both sockets when marker API is not activated.

All files are in files.zip.
Any thoughts/suggestions?
[files.zip](https://github.com/RRZE-HPC/likwid/files/1261204/files.zip)

Thanks
-Amidu

**Comment by TomTheBear** [comment]
It is strange that the MarkerAPI does not read the second socket. I can reproduce it. I'm not 100% sure why it behaves like this and I currently don't have time to dig deeper into it, but move the `LIKWID_MARKER_INIT` to the beginning of the main function. This fixed it for me. Why it does not work when you call it "later" needs further investigation.

**Comment by aoloso** [comment]
Thanks much for the quick response. Able to confirm your suggestion works.

**Comment by TomTheBear** [comment]
I keep the issue open to notify myself to investigate this behavior

**Comment by aoloso** [comment]
Ok

**Comment by TomTheBear** [comment]
I checked this issue with the current 4.3.0 branch (which will be released as 4.3.2 soon) and it does not happen anymore.
