### ISSUE TITLE
likwid-mpirun syntax for hybrid MPI/OpenMP

### ISSUE THREAD

**Issue by aoloso** [RRZE-HPC/likwid#114]
Suppose I have a node with two sockets, each socket has 14 cores. I want to run 6 MPI processes on the node with 4 OpenMP threads per MPI process using the first 12 cores in each socket. The following works:

likwid-mpirun -mpi intelmpi -omp intel -np 6 -pin S0:0-3_S0:4-7_S0:8-11_S1:14-17_S1:18-21_S1:22-25 <executable>

But is there a more compact way to represent this?

**Comment by TomTheBear** [comment]
Currently this is the only way. I already started to simplify the selection for hybrid codes. When it is added, your selection would be something like this:
`likwid-mpirun -nperdomain S:3:4`
or
`likwid-mpirun -nperdomain S:3 -tpp 4`
= 3 MPI processes per socket with 4 threads each (tpp = threads-per-process).
The total number of processes can still be set with -np or is calculated based on the number of nodes, the count of affinity domains (here socket count) and the process count.

Just as note: In most cases you can leave out the `-mpi` and `-omp` setting. `likwid-mpirun` tries to detect these settings automatically.

**Comment by aoloso** [comment]
Thanks. 
Looking forward to when the simplified selection will be available.
