### ISSUE TITLE
likwid_mpirun works for 1 OpenMP thread per MPI process but fails for 2 threads per process

### ISSUE THREAD

**Issue by aoloso** [RRZE-HPC/likwid#116]
I am trying to run a hybrid MPI/OpenMP code across two haswell nodes. 
Both of the following work, i.e. with 1 OpenMP thread per MPI process:
likwid-mpirun -mpi intelmpi -omp intel -np 48 -nperdomain N:24 <executable>

likwid-mpirun -f -mpi intelmpi -np 48-pin S0:0_S0:1_S0:2_S0:3_S0:4_S0:5_S0:6_S0:7_S0:8_S0:9_S0:10_S0:11_S1:0_S1:1_S1:2_S1:3_S1:4_S1:5_S1:6_S1:7_S1:8_S1:9_S1:10_S1:11 <executable>

An attempt to use 2 threads per process fails as follows:
likwid-mpirun -f -mpi intelmpi -np 24 -pin S1:0-1_S1:2-3_S1:4-5_S0:0-1_S0:2-3_S0:4-5_S1:6-7_S1:8-9_S1:10-11_S0:6-7_S0:8-9_S0:10-11 <executable>
<executable>: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by <executable>)

Any thought on what this means? 
The executable works fine for multiple threads per process using the normal "mpirun."
Thanks.

**Comment by aoloso** [comment]
strings <executable> | grep GLIBC
GLIBC_2.2.5
GLIBCXX_3.4.11
GLIBCXX_3.4.21
GLIBCXX_3.4
GLIBCXX_3.4.20
GLIBC_2.3.2
GLIBC_2.4
GLIBC_2.3.4
GLIBC_2.3
GLIBC_2.7

whereas 
 strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_DEBUG_MESSAGE_LENGTH

Could it be /usr/lib64/libstdc++.so.6 requires an update?

**Comment by aoloso** [comment]
/usr/lib64/libstdc++.so.6 is being overwritten by setting LD_LIBRARY_PATH to point to /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 which has the right GLIBCXX version. Looks like likwid_mpirun is ignoring that overwrite.

strings /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by TomTheBear** [comment]
Hi,
likwid-mpirun itself does nothing with the LD_LIBRARY_PATH but both likwid-pin and likwid-perfctr do and one of them is called internally. But they just extend the LD_LIBRARY_PATH.
Is the overwrite done through `modules` or similar? If so, you might have a clash of versions on the two nodes, one has the overwritten path but the other one doesn't. Is that a possibility?

Internally, it uses also mpirun or mpiexec.hydra, so it is probably some environment stuff that is not forwarded to mpirun when it is called from likwid-mpirun.

**Comment by aoloso** [comment]
Yes modules are loaded in the job script. And yes it is possible the loaded modules take effect on the head node but not on the other. How does one force likwid_mpirun to propagate the environment on the head node to the other nodes in one's allocation? Nothing extra/special is done to have a successful run using Intel MPI's mpirun, for example.

**Comment by TomTheBear** [comment]
I just tested it on our cluster and the LD_LIBRARY_PATH is forwarded to the other nodes, which should contain the overwritten path to `libstdc++.so` if it is set on the master node.
What is especially interesting for me is that the LIKWID library is not linked against `libstdc++.so`. Even the libraries, that the LIKWID library is linked to, are not linked to `libstdc++.so`. Maybe at some deeper level but I havn't checked this.
Can you try to get the environment when running in threaded mode?
`likwid-mpirun -pin S0:0-1_S1:0-1 -np 4 env | grep "LD_"`

There is no method from the outside/command line to force `likwid-mpirun` to set or copy specific environment variables but there is a function `getEnvironmentIntelMPI()` that returns some variables that should be forwarded explicitly. You can add something like
`env["LD_LIBRARY_PATH"] = os.getenv("LD_LIBRARY_PATH")`

**Comment by aoloso** [comment]
`likwid-mpirun -f -mpi intelmpi -np 24 -pin S1:0-1_S1:2-3_S1:4-5_S0:0-1_S0:2-3_S0:4-5_S1:6-7_S1:8-9_S1:10-11_S0:6-7_S0:8-9_S0:10-11 env | grep "LD_" `

seems to to show that `LD_LIBRARY_PATH` is forwarded to the other nodes from the head node.
Yet running the actual executable is still given the previous error.
How do I add 
`env["LD_LIBRARY_PATH"] = os.getenv("LD_LIBRARY_PATH")` ?

**Comment by TomTheBear** [comment]
Can you check whether the application is linked to the correct library using `ldd` on both hosts?
`likwid-mpirun -f -mpi intelmpi -np 24 -pin S1:0-1_S1:2-3_S1:4-5_S0:0-1_S0:2-3_S0:4-5_S1:6-7_S1:8-9_S1:10-11_S0:6-7_S0:8-9_S0:10-11 ldd <abspath_to_app>`

To change likwid-mpirun, copy it from the install location anywhere where you have write permissions and add the `env[]..` line to the `getEnvironmentIntelMPI()` function. Then run it from that directory.

**Comment by aoloso** [comment]
The relevant part of the `ldd` output indicates all 24 processes point to the right libstdc++ as shown:
`        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffefd2a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffefd2a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffefd2a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffefd2a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffefd2a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffefd2a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffefd2a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffefd2a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffefd2a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffefd2a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffefd2a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffefd2a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffff52a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffff52a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffff52a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffff52a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffff52a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffff52a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffff52a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffff52a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffff52a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffff52a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffff52a5000)
        libstdc++.so.6 => /usr/local/other/SLES11.3/gcc/6.3/lib64/libstdc++.so.6 (0x00007ffff52a5000)
`

And we already confirmed `LD_LIBRARY_PATH` is properly propagated from the head node.
Baffling. A bit more wrinkle in case it helps. As indicated in the first posting of this thread, `likwid-mpirun -mpi intelmpi -omp intel -np 48 -nperdomain N:24` works fine. However, `likwid-mpirun -mpi intelmpi -omp intel -np 48 -nperdomain N:24 -g MEM` fails with the `GLIBCXX`  error. In order words any attempt to use `likwid-mpirun` where `likwid-pin` or `likwid-perfctr` is exercised throws the error. I wonder if those tools have some path(s) hardwired such that they look for libraries in some standard place(s) as opposed to picking them from the user's environment.

**Comment by TomTheBear** [comment]
It is really strange and I probably have to ask someone who has more understanding of this. Have you got the link paths with or without `-g` on the command line? 

Concerning the second part of your post: If you don't use -g <eventset> on the command line, it always calls `likwid-pin` in the background. Otherwise it uses `likwid-perfctr`. You can see what is called per rank by adding the `-d` command line switch for `likwid-mpirun`.  Interestingly, both scripts extend `LD_LIBRARY_PATH` and `LD_PRELOAD` with the `PREFIX/lib` path (`PREFIX` is defined in `config.mk` before compiling LIKWID, commonly `/usr/local/lib` and `/usr/local/lib/liblikwidpin.so`).
There are some hardwired paths inside but none is pointing to `/usr/lib64` but to `PREFIX/lib`.

**Comment by aoloso** [comment]
Update: I just noticed that actually the problem is not because I am using multiple nodes. The problem occurs even I am using a single node. I am sorry for misrepresenting the issue. Not sure if this helps a bit more in diagnosing the problem.

**Comment by aoloso** [comment]
BTW, adding `env["LD_LIBRARY_PATH"] = os.getenv("LD_LIBRARY_PATH")` to `getEnvironmentIntelMPI() ` didn't make a difference.

**Comment by aoloso** [comment]
Quick update: Tried again today by setting LD_PRELOAD to point to the right libstdc++.so and that seems to help bypass the problem.

**Comment by TomTheBear** [comment]
Have you tried with the last release (4.3.4)? Any novelties?

**Comment by TomTheBear** [comment]
Any updates? Otherwise I'll close the issue soon.
