### ISSUE TITLE
Documentation: likwid_markerGetRegion instead of likwid_markerGetResult

### ISSUE THREAD

**Issue by hekatebacchus** [RRZE-HPC/likwid#117]
In the tutorial of the marker API you write 

> LIKWID_MARKER_GET(char* tag, int* nevents, double* events, double* time, int* count) or likwid_markerGetResult(char* tag, int* nevents, double* events, double* time, double* count)

I think `likwid_markerGetResult` should be `likwid_markerGetRegion` since it is defined like that in `likwid.h`:
`#define LIKWID_MARKER_GET(regionTag, nevents, events, time, count) likwid_markerGetRegion(regionTag, nevents, events, time, count)`

Best Regards,
Markus

**Comment by TomTheBear** [comment]
Thank you. I fixed the wiki page.
Best,
Thomas
