### ISSUE TITLE
Producing a roofline plot with likwid

### ISSUE THREAD

**Issue by psteinb** [RRZE-HPC/likwid#126]
Hi,
I am inclined to produce a roofline plot with `likwid-perfctr` (from likwid 4.2.1) and would need some guidance on which events/counters are best to be used. 

I am after the standard roofline plot of performance in GFlops/s (along y) versus arithmetic intensity (along x). I am doing this on an ivy bridge dual-core laptop to start with and want to go to servers later. The code I am studying for this exercise is similar to the `stream_sp_avx` benchmark that `likwid-bench` comes with. 
First of, I'd like to measure flops, but that the numbers reported by likwid-bench and likwid-perfctr differ:

```
# likwid-perfctr -f -c 0 -g FLOPS_AVX likwid-bench -t stream_sp_avx -w S0:500MB:1
-------------------------------------------------------------------------------
CPU name:	Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
CPU type:	Intel Core IvyBridge processor
CPU clock:	2.89 GHz
--------------------------------------------------------------------------------
Warning: Sanitizing vector length to a multiple of the loop stride 32 and thread count 1 from 41666666 elements (499999992 bytes) to 41666656 elements (499999872 bytes)
Allocate: Process running on core 0 (Domain S0) - Vector length 41666656/166666624 Offset 0 Alignment 1024
Allocate: Process running on core 0 (Domain S0) - Vector length 41666656/166666624 Offset 0 Alignment 1024
Allocate: Process running on core 0 (Domain S0) - Vector length 41666656/166666624 Offset 0 Alignment 1024
--------------------------------------------------------------------------------
LIKWID MICRO BENCHMARK
Test: stream_sp_avx
--------------------------------------------------------------------------------
Using 1 work groups
Using 1 threads
--------------------------------------------------------------------------------
Running without Marker API. Activate Marker API with -m on commandline.
--------------------------------------------------------------------------------
Group: 0 Thread 0 Global Thread 0 running on core 0 - Vector length 41666656 Offset 0
--------------------------------------------------------------------------------
Cycles:			3669554002
CPU Clock:		2893399595
Cycle Clock:		2893399595
Time:			1.268250e+00 sec
Iterations:		32
Iterations per thread:	32
Inner loop executions:	1302083
Size (Byte):		499999872
Size per thread:	499999872
Number of Flops:	2666665984
MFlops/s:		2102.63
Data volume (Byte):	15999995904
MByte/s:		12615.81
Cycles per update:	2.752166
Cycles per cacheline:	44.034659
Loads per update:	2
Stores per update:	1
Load bytes per element:	8
Store bytes per elem.:	4
Load/store ratio:	2.00
Instructions:		791666481
UOPs:			1083333056
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Group 1: FLOPS_AVX
+---------------------------+---------+-------------+
|           Event           | Counter |    Core 0   |
+---------------------------+---------+-------------+
|     INSTR_RETIRED_ANY     |  FIXC0  |  2699993173 |
|   CPU_CLK_UNHALTED_CORE   |  FIXC1  | 11420439992 |
|    CPU_CLK_UNHALTED_REF   |  FIXC2  | 10150493754 |
| SIMD_FP_256_PACKED_SINGLE |   PMC0  |  2500646433 |
| SIMD_FP_256_PACKED_DOUBLE |   PMC1  |           0 |
+---------------------------+---------+-------------+

+----------------------+-----------+
|        Metric        |   Core 0  |
+----------------------+-----------+
|  Runtime (RDTSC) [s] |    4.7047 |
| Runtime unhalted [s] |    3.9475 |
|      Clock [MHz]     | 3255.0603 |
|          CPI         |    4.2298 |
|   Packed SP MFLOP/s  | 4252.2037 |
|   Packed DP MFLOP/s  |         0 |
+----------------------+-----------+
```
the difference is around 2x and I wonder that this couldn't only be due to the dynamic frequency scaling that I still have enabled. 

Second, the output of likwid-bench lists fields like `Data volume (Byte):` or `MByte/s:`. what would be the equivalent event/group in likwid-perfctr, `L3`? I am asking as the numbers are not entirely the same (about 10% deviation). 

It would be super helpful for my day-to-day performance engineering work, if producing roofline plots with likwid would be straight forward to some extent.

**Comment by TomTheBear** [comment]
Hi,

you are not the only one trying to derive a roofline plot from LIKWID measurements.

> First of, I'd like to measure flops, but that the numbers reported by likwid-bench and likwid-perfctr differ:

This is probably caused by the buggy floating-point events of IvyBridge CPUs (for more info: [http://icl.cs.utk.edu/projects/papi/wiki/PAPITopics:SandyFlops](http://icl.cs.utk.edu/projects/papi/wiki/PAPITopics:SandyFlops) ) and not the dynamic frequency scaling.

> Second, the output of likwid-bench lists fields like `Data volume (Byte):` or `MByte/s:`. what would be the equivalent event/group in likwid-perfctr, `L3`?

`L3` is a starting point but I would go the with memory controllers themselves. On desktop CPUs (like your laptop) there is no support for memory controllers yet so L3 should be fine. The L3 counters are not 100% accurate as you mentioned. What do you mean with 10% deviation between `Data volume (Byte):` and `MByte/s:`. The calculation is almost the same in likwid-bench, there shouldn't be a deviation.
With server CPUs you should have memory controllers. For server CPUs since SandyBridge you can use the `MEM_DP` and `MEM_SP` groups which gives you the operational intensity (use the SUM value in statistics table), the FLOP rate as well as the memory bandwidth.

**Comment by psteinb** [comment]
@TomTheBear thanks for getting back to me on this. If there is increased interest, I am happy to contribute to a central wiki or README file. I [started something](https://github.com/psteinb/meetingcpp2017/tree/master/figure/roofline) for a talk but didn't get anywhere with my laptop as you pointed out (the methodology was based on presentations given by @rrzeschorscherl). I might move to a server now and check there again. Beyond the talk, I'd be curious in similar adventures to create a roofline plot with bit manipulation operations rather than flops.

Regarding the 10% deviation (which btw was a flawed typo), I mean the following:
```
# likwid-perfctr -f -c 0 -g L3 likwid-bench -t stream_sp_avx -w S0:500MB:1
--------------------------------------------------------------------------------
CPU name:	Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
CPU type:	Intel Core IvyBridge processor
CPU clock:	2.89 GHz
--------------------------------------------------------------------------------
Warning: Sanitizing vector length to a multiple of the loop stride 32 and thread count 1 from 41666666 elements (499999992 bytes) to 41666656 elements (499999872 bytes)
Allocate: Process running on core 0 (Domain S0) - Vector length 41666656/166666624 Offset 0 Alignment 1024
Allocate: Process running on core 0 (Domain S0) - Vector length 41666656/166666624 Offset 0 Alignment 1024
Allocate: Process running on core 0 (Domain S0) - Vector length 41666656/166666624 Offset 0 Alignment 1024
--------------------------------------------------------------------------------
LIKWID MICRO BENCHMARK
Test: stream_sp_avx
--------------------------------------------------------------------------------
Using 1 work groups
Using 1 threads
--------------------------------------------------------------------------------
Running without Marker API. Activate Marker API with -m on commandline.
--------------------------------------------------------------------------------
Group: 0 Thread 0 Global Thread 0 running on core 0 - Vector length 41666656 Offset 0
--------------------------------------------------------------------------------
Cycles:			3617945425
CPU Clock:		2893402640
Cycle Clock:		2893402640
Time:			1.250412e+00 sec
Iterations:		32
Iterations per thread:	32
Inner loop executions:	1302083
Size (Byte):		499999872
Size per thread:	499999872
Number of Flops:	2666665984
MFlops/s:		2132.63
Data volume (Byte):	15999995904
MByte/s:		12795.78
Cycles per update:	2.713460
Cycles per cacheline:	43.415356
Loads per update:	2
Stores per update:	1
Load bytes per element:	8
Store bytes per elem.:	4
Load/store ratio:	2.00
Instructions:		791666481
UOPs:			1083333056
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Group 1: L3
+------------------------+---------+-------------+
|          Event         | Counter |    Core 0   |
+------------------------+---------+-------------+
|    INSTR_RETIRED_ANY   |  FIXC0  |  2752978572 |
|  CPU_CLK_UNHALTED_CORE |  FIXC1  | 11349256948 |
|  CPU_CLK_UNHALTED_REF  |  FIXC2  | 10109808175 |
|     L2_LINES_IN_ALL    |   PMC0  |   658645866 |
| L2_LINES_OUT_DIRTY_ALL |   PMC1  |   200162780 |
+------------------------+---------+-------------+

+-------------------------------+------------+
|             Metric            |   Core 0   |
+-------------------------------+------------+
|      Runtime (RDTSC) [s]      |     4.6294 |
|      Runtime unhalted [s]     |     3.9225 |
|          Clock [MHz]          |  3248.1285 |
|              CPI              |     4.1225 |
|  L3 load bandwidth [MBytes/s] |  9105.5047 |
|  L3 load data volume [GBytes] |    42.1533 |
| L3 evict bandwidth [MBytes/s] |  2767.1670 |
| L3 evict data volume [GBytes] |    12.8104 |
|    L3 bandwidth [MBytes/s]    | 11872.6717 |
|    L3 data volume [GBytes]    |    54.9638 |
+-------------------------------+------------+
```
If I compare now, `L3 bandwidth` to the output of `likwid-bench` I am ok. But the `L3 data volume` is 3x larger than the line with `Data volume (Byte)` from likwid-bench.

**Comment by TomTheBear** [comment]
You are running without MarkerAPI. Consequently, the measurements contain the initialization, the detection of iteration space (which executes the loop multiple times) and some more operations.

If you use the MarkerAPI (surrounding only the important loop) you get accurate measurements:
```
$ likwid-perfctr -C 0 -g L3 -m likwid-bench -t stream_sp_avx -w N:500MB:1
--------------------------------------------------------------------------------
CPU name:	Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
CPU type:	Intel Core Haswell processor
CPU clock:	3.39 GHz
--------------------------------------------------------------------------------
Warning: Sanitizing vector length to a multiple of the loop stride 32 and thread count 1 from 41666666 elements (499999992 bytes) to 41666656 elements (499999872 bytes)
Allocate: Process running on core 0 (Domain N) - Vector length 41666656/166666624 Offset 0 Alignment 1024
Allocate: Process running on core 0 (Domain N) - Vector length 41666656/166666624 Offset 0 Alignment 1024
Allocate: Process running on core 0 (Domain N) - Vector length 41666656/166666624 Offset 0 Alignment 1024
--------------------------------------------------------------------------------
LIKWID MICRO BENCHMARK
Test: stream_sp_avx
--------------------------------------------------------------------------------
Using 1 work groups
Using 1 threads
--------------------------------------------------------------------------------
Using Likwid Marker API
--------------------------------------------------------------------------------
Group: 0 Thread 0 Global Thread 0 running on core 0 - Vector length 41666656 Offset 0
--------------------------------------------------------------------------------
Cycles:			3477641244
CPU Clock:		3392183750
Cycle Clock:		3392183750
Time:			1.025192e+00 sec
Iterations:		16
Iterations per thread:	16
Inner loop executions:	1302083
Size (Byte):		499999872
Size per thread:	499999872
Number of Flops:	1333332992
MFlops/s:		1300.57
Data volume (Byte):	7999997952
MByte/s:		7803.41
Cycles per update:	5.216463
Cycles per cacheline:	83.463411
Loads per update:	2
Stores per update:	1
Load bytes per element:	8
Store bytes per elem.:	4
Load/store ratio:	2.00
Instructions:		395833249
UOPs:			541666528
--------------------------------------------------------------------------------
Writing Likwid Marker API results to file /tmp/likwid_27021.txt
--------------------------------------------------------------------------------
Region bench, Group 1: L3
+-------------------+----------+
|    Region Info    |  Core 0  |
+-------------------+----------+
| RDTSC Runtime [s] | 1.025198 |
|     call count    |        1 |
+-------------------+----------+

+-----------------------+---------+------------+
|         Event         | Counter |   Core 0   |
+-----------------------+---------+------------+
|   INSTR_RETIRED_ANY   |  FIXC0  |  395838600 |
| CPU_CLK_UNHALTED_CORE |  FIXC1  | 1222710000 |
|  CPU_CLK_UNHALTED_REF |  FIXC2  | 3464345000 |
|    L2_LINES_IN_ALL    |   PMC0  |  124675400 |
|     L2_TRANS_L2_WB    |   PMC1  |   39538540 |
+-----------------------+---------+------------+

+-------------------------------+------------+
|             Metric            |   Core 0   |
+-------------------------------+------------+
|      Runtime (RDTSC) [s]      |     1.0252 |
|      Runtime unhalted [s]     |     0.3604 |
|          Clock [MHz]          |  1197.2395 |
|              CPI              |     3.0889 |
|  L3 load bandwidth [MBytes/s] |  7783.1069 |
|  L3 load data volume [GBytes] |     7.9792 |
| L3 evict bandwidth [MBytes/s] |  2468.2711 |
| L3 evict data volume [GBytes] |     2.5305 |
|    L3 bandwidth [MBytes/s]    | 10251.3779 |
|    L3 data volume [GBytes]    |    10.5097 |
+-------------------------------+------------+
```

The measurements commonly contain RFOs (Read-For-Ownership, also called write-allocates) but likwid-bench's values are without RFOs. The scaling factor for stream is 1.333 because two arrays are loaded while one array is used as output without loading the memory location beforehand (=RFO required):
`(7999997952B * 1.333) / (1024**3) = 9.9GB`

**Comment by psteinb** [comment]
@TomTheBear thanks a bunch. that set me straight a bit. I'll work through your comments on `likwid-bench`. Regarding that: did you add the markers to the benchmark code? I thought that these benchmarks are written in a high level assembly according to [the wiki](https://github.com/RRZE-HPC/likwid/wiki/Likwid-Bench) ... then how did you do that?

on the bit manipulation issue: well, I guess I have to use some other metric for the y-axis (say elements/second) then and measure the instructions per byte transferred with `likwid-perfctr` to get some guidance where my "improvements" go. That would not be the most exact, but it would be the quantitive guidance I am after. if that won't hold, please let me know.

**Comment by TomTheBear** [comment]
The markers are included in the likwid-bench code (see EXECUTE macro in bench/src/bench.c) but only "activated" if you set `INSTRUMENT_BENCH` in `config.mk` to `true`. We do this in general as the markers (without -m command line switch for likwid-perfctr) cause only little overhead. (https://github.com/RRZE-HPC/likwid/wiki/Likwid-Bench#using-likwid-bench-together-with-likwid-perfctr)

Instructions per byte should work but this could include a lot of noise depending on your code. You could try the `UOPS_DISPATCHED_PORT_ARITH_PORTS_CORE` event which counts micro-ops scheduled to port 0, 1 and 5 (separate events for each port exist as well) but keep in mind that these counts contain speculatively scheduled events. The retired instructions event does not contain speculatively executed instructions.

**Comment by georgebisbas** [comment]
Dear all at LIKWID benchmarking suite,
First of all, I would like to congratulate you for this awesome work.
I had a glance at this "issue" here and I would like to ask you whether any roofline plot case using LIKWID has been reported till now. It would be awesome. Thank you in advance.

**Comment by TomTheBear** [comment]
I know that the Lawrence Berkeley Lab produces roofline plots with LIKWID, see this [presentation](https://www.nersc.gov/assets/Uploads/2-SWillams-Roofline-Intro.pdf). They also provide the [Empirical Roofline Toolkit (ERT)](https://crd.lbl.gov/departments/computer-science/par/research/roofline/software/ert/) but I'm not sure whether they use LIKWID as backend.

The tool [kerncraft](https://github.com/RRZE-HPC/kerncraft) and the [INSPECT pages](https://rrze-hpc.github.io/INSPECT/) present the roofline modell based on LIKWID (and other) analysis.

**Comment by georgebisbas** [comment]
Thank you very much for the info Tom.

**Comment by TomTheBear** [comment]
https://github.com/RRZE-HPC/likwid/wiki/Tutorial%3A-Empirical-Roofline-Model

**Comment by jrmadsen** [comment]
Just ran across this in my github notifications -- just for the record, ERT doesn't collect any hardware counters. It executes a series of known amounts of loads/stores/flops wrapped with a simple wall-clock timer and then constructs the roofs from that data. It cannot be used to estimate where your algorithm is located w.r.t. to the roofline

**Comment by TomTheBear** [comment]
Thanks for the clarification.

**Comment by SamHerts** [comment]
> I know that the Lawrence Berkeley Lab produces roofline plots with LIKWID, see this [presentation](https://www.nersc.gov/assets/Uploads/2-SWillams-Roofline-Intro.pdf). They also provide the [Empirical Roofline Toolkit (ERT)](https://crd.lbl.gov/departments/computer-science/par/research/roofline/software/ert/) but I'm not sure whether they use LIKWID as backend.
> 
> The tool [kerncraft](https://github.com/RRZE-HPC/kerncraft) and the [INSPECT pages](https://rrze-hpc.github.io/INSPECT/) present the roofline modell based on LIKWID (and other) analysis.

Note, the ERT tool has been moved to a new bitbucket repository:
[Empirical Roofline Toolkit (ERT](https://bitbucket.org/berkeleylab/cs-roofline-toolkit/src/master/)
