### ISSUE TITLE
WARNING: Counter PMC1 is only available with deactivated HyperThreading. Counter results defaults to 0.

### ISSUE THREAD

**Issue by SirLouiz** [RRZE-HPC/likwid#130]
Hello everyone, first, awsome project, really well done.

I have a AMD Phenom II X6 1055T 
and, i'm trying to run likwid-perfctr with a program i wrote.

$ likwid-perfctr -C 1 -g MEM -m ./invmat -r 32 -i 10
 It gives me:
--------------------------------------------------------------------------------
CPU name:	AMD Phenom(tm) II X6 1055T Processor
CPU type:	Unknown AMD Processor
CPU clock:	2.81 GHz
WARNING: Counter PMC1 is only available with deactivated HyperThreading. Counter results defaults to 0.
WARNING: Counter PMC2 is only available with deactivated HyperThreading. Counter results defaults to 0.
WARNING: Counter PMC3 is only available with deactivated HyperThreading. Counter results defaults to 0.
--------------------------------------------------------------------------------
And proceeds to show me the results of only PMC0.
+-------------------------------+---------+--------+
|             Event             | Counter | Core 1 |
+-------------------------------+---------+--------+
| NORTHBRIDGE_READ_RESPONSE_ALL |   PMC0  |     83 |
|    OCTWORDS_WRITE_TRANSFERS   |   PMC1  |      0 |
|     DRAM_ACCESSES_DCTO_ALL    |   PMC2  |      0 |
|     DRAM_ACCESSES_DCT1_ALL    |   PMC3  |      0 |
+-------------------------------+---------+--------+

My CPU has the K10 amd architecture, and amd doesn't have HyperThreading, what can i do?

**Comment by TomTheBear** [comment]
Thanks.
Can you please run `likwid-topology -V 3` and supply the output.

At first the CPU is not recognized correctly, that's why you have a `Unknown AMD Processor`. I will fix this when I get the model number from the requested output.
The warning is strange. It detects whether it is running on an Intel platform but this detection might fail. This is very uncommon and the fallback is 'not an Intel platform'. But the output of `likwid-topology` will show this.

**Comment by SirLouiz** [comment]
Alright,
$ likwid-topology -V 3
DEBUG - [hwloc_init_cpuInfo:125] HWLOC CpuInfo Family 16 Model 10 Stepping 0 isIntel 0 numHWThreads 6 activeHWThreads 6
DEBUG - [hwloc_init_nodeTopology:261] HWLOC Thread Pool PU 0 Thread 0 Core 0 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:261] HWLOC Thread Pool PU 1 Thread 0 Core 1 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:261] HWLOC Thread Pool PU 2 Thread 0 Core 2 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:261] HWLOC Thread Pool PU 3 Thread 0 Core 3 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:261] HWLOC Thread Pool PU 4 Thread 0 Core 4 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_nodeTopology:261] HWLOC Thread Pool PU 5 Thread 0 Core 5 Socket 0 inCpuSet 1
DEBUG - [hwloc_init_cacheTopology:361] HWLOC Cache Pool ID 0 Level 1 Size 65536
DEBUG - [hwloc_init_cacheTopology:361] HWLOC Cache Pool ID 1 Level 2 Size 524288
DEBUG - [hwloc_init_cacheTopology:361] HWLOC Cache Pool ID 2 Level 3 Size 6291456
DEBUG - [affinity_init:169] Affinity: Socket domains 1
DEBUG - [affinity_init:172] Affinity: NUMA domains 1
DEBUG - [affinity_init:175] Affinity: CPUs per socket 6
DEBUG - [affinity_init:181] Affinity: CPU cores per LLC 6
DEBUG - [affinity_init:185] Affinity: CPUs per LLC 6
DEBUG - [affinity_init:192] Affinity: Cache domains 1
DEBUG - [affinity_init:195] Affinity: All domains 4
DEBUG - [affinity_init:206] Affinity domain N: 6 HW threads on 6 cores
DEBUG - [affinity_init:247] Affinity domain S0: 6 HW threads on 6 cores
DEBUG - [affinity_init:281] Affinity domain C0: 6 HW threads on 6 cores
DEBUG - [affinity_init:363] Affinity domain M0: 6 HW threads on 6 cores
--------------------------------------------------------------------------------
CPU name:	AMD Phenom(tm) II X6 1055T Processor
CPU type:	Unknown AMD Processor
CPU stepping:	0
********************************************************************************
Hardware Thread Topology
********************************************************************************
Sockets:		1
Cores per socket:	6
Threads per core:	1
--------------------------------------------------------------------------------
HWThread	Thread		Core		Socket		Available
0		0		0		0		*
1		0		1		0		*
2		0		2		0		*
3		0		3		0		*
4		0		4		0		*
5		0		5		0		*
--------------------------------------------------------------------------------
Socket 0:		( 0 1 2 3 4 5 )
--------------------------------------------------------------------------------
********************************************************************************
Cache Topology
********************************************************************************
Level:			1
Size:			64 kB
Cache groups:		( 0 ) ( 1 ) ( 2 ) ( 3 ) ( 4 ) ( 5 )
--------------------------------------------------------------------------------
Level:			2
Size:			512 kB
Cache groups:		( 0 ) ( 1 ) ( 2 ) ( 3 ) ( 4 ) ( 5 )
--------------------------------------------------------------------------------
Level:			3
Size:			6 MB
Cache groups:		( 0 1 2 3 4 5 )
--------------------------------------------------------------------------------
********************************************************************************
NUMA Topology
********************************************************************************
NUMA domains:		1
--------------------------------------------------------------------------------
Domain:			0
Processors:		( 0 1 2 3 4 5 )
Distances:		10
Free memory:		4222.18 MB
Total memory:		7984.01 MB
--------------------------------------------------------------------------------
there it is

**Comment by TomTheBear** [comment]
Which version of LIKWID are you using? 

The output shows that you system is detected as "non-Intel" (`isIntel 0` in first line). When I remember it right, the bug you found is still there in version 4.2.1 but fixed in the pre-release 4.3.0. When you upgrade to this version you should be able to use all counters. Your system will still be detected as `Unknown AMD platform` but this is not problematic, it's just a string. LIKWID detects properly that your system is an AMD K10 core.

**Comment by SirLouiz** [comment]
I'm using version 4.2.1. I'll update it and see what happens, just a question, do i delete the old one, and build the new on top of it?

**Comment by TomTheBear** [comment]
It depends which source you took to install 4.2.1. If it is a pre-compiled package (RPM, DEB, ...) you should delete that first and then install the new one.
If you build from source, you commonly can overwrite the old one but some dead links might be persistent. I recommend to do it like this:
```
cd likwid-4.2.1
sudo make uninstall
cd ..
tar -xzf likwid-4.3.0.tar.gz
cd likwid-4.3.0
# maybe adapt config.mk to change the installation PREFIX
make -j && sudo make install
```
This way you keep your system clean.

**Comment by SirLouiz** [comment]
Worked like a charm, thank you very much!
