### ISSUE TITLE
Make likwid-perfctr display a warning when specifying an unknown event

### ISSUE THREAD

**Issue by hofm** [RRZE-HPC/likwid#132]
Some of my students appear to have trouble copying events names from the slides to the command line: MEM_LOAD_UOPS_RETIRED_L1_HIT becomes MEM_UOPS_RETIRED_L1_HIT or MEM_LOAD_UOPS_RETIRED_L1_HITS.

With -V 1 likwid-perfctr displays the following:
DEBUG - [perfmon_addEventSet:1423] Event MEM_LOAD_UOPS_RETIRED_L1_HITS not found for current architecture

Without -V <x> likwid-perfctr does not display a warning and reports the counter value as 0, which, obviously, is interpreted by students as "No L1 cache hits!"

A warning would be nice.

**Comment by TomTheBear** [comment]
Starting with commit https://github.com/RRZE-HPC/likwid/commit/0ea95c461074a20ff9e73699f3c0e996789e1588 the warnings are printed.
