### ISSUE TITLE
likwid-perfctr returning empty counters list with BroadwellEP

### ISSUE THREAD

**Issue by sguera** [RRZE-HPC/likwid#133]
Using the following architecture:
```
likwid-perfctr -i
--------------------------------------------------------------------------------
CPU name:	Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz
CPU type:	Intel Xeon Broadwell EN/EP/EX processor
CPU clock:	2.39 GHz
CPU family:	6
CPU model:	79
CPU short:	broadwellEP
CPU stepping:	1
CPU features:	ACPI MMX SSE SSE2 HTT TM RDTSCP MONITOR VMX EIST TM2 SSSE3 FMA SSE4.1 SSE4.2 AES AVX RDRAND HLE AVX2 RTM RDSEED SSE3 
--------------------------------------------------------------------------------
PERFMON version:	3
PERFMON number of counters:	8
PERFMON width of counters:	48
PERFMON number of fixed counters:	3
--------------------------------------------------------------------------------
```

If I try to list the groups or the events I get empty lists:
```
[guerrera@dmi-cl-login ~]$ likwid-perfctr -e
This architecture has 0 counters.
Counter tags(name, type<, options>):



This architecture has 0 events.
Event tags (tag, id, umask, counters<, options>):
[guerrera@dmi-cl-login ~]$ likwid-perfctr -E L1
Found 0 event(s) with search key L1:

Usable counter(s) for above event(s):
```

**Comment by TomTheBear** [comment]
Are you sure that the access to the registers is configured properly?

LIKWID tests the registers at `-e` to show only the events and counters that are available for you. If access it not properly configured no counter can be accessed and consequently no events are shown.

**Comment by sguera** [comment]
I did not install it myself but I checked a build directory still on the system and this things have been done:

Set BUILDDAEMON to true
Configure the path to the access daemon binary at ACCESSDAEMON
Set the ACCESSMODE to accessdaemon

Is there any other way to check if the configuration is done properly?

**Comment by TomTheBear** [comment]
Check the global log file for error messages from the access daemon.

You can check whether the suid-root bit is properly set for the access daemon and user is root.
```
$ ls -la $(which likwid-accessD)
-rw**s**r-xr-x 1 root root 52K Dec  7 10:02 /usr/local/sbin/likwid-accessD
```
Moreover, you can run a common performance group (e.g. BRANCH) with `-V 1` and check the output. You can see something like this:
```
DEBUG - [checkAccess:212] WARNING: The device for counter MBOX5C1 does not exist
DEBUG - [perfmon_addEventSet:1747] Cannot access counter register MBOX5C1
```
You should check that the msr device files exist in `/dev/cpu/0/msr`. Otherwise do a `sudo modprobe msr`.

**Comment by sguera** [comment]
I checked and the user is not root, even though it has the sticky bit set.
I assume it depends on that than. Thanks for clarifying.

**Comment by TomTheBear** [comment]
Well, the user should be allowed to access the msr and pci device files.
The user-sticky bit escalates the permissions of the application to the ones of the user, same for the group-sticky bit with the group of the file. If the user/group has the proper permissions, it should work.

**Comment by TomTheBear** [comment]
Can I close this 'bug' or do you have further questions/problems?

**Comment by sguera** [comment]
Thanks for the explanation. You can close the issue.
