### ISSUE TITLE
system wide monitoring of events using likwid-perfctr

### ISSUE THREAD

**Issue by yogeshVU** [RRZE-HPC/likwid#139]
How can one measure system wide events metrics using the likwid-perfctr

example for say 5 seconds....
```
likwid-perfctr -g MEM

```

**Comment by rrzeschorscherl** [comment]
```
$ likwid-perfctr -c <CORES> -g <GROUP> -S 5s
```
where `<CORES>` is the cores you want to measure on. On a machine with 2x20 cores and SMT on, you would type 
```
$ likwid-perfctr -c E:N:80:1:1 -g FLOPS_AVX -S 5s
```
to measure AVX flops for 5 seconds. If you want to measure memory traffic on Intel, it is sufficient to count on on core per locality domain.
