### ISSUE TITLE
Xeon Phi - MCDRAM and DDR4 Requests

### ISSUE THREAD

**Issue by PatilChetan** [RRZE-HPC/likwid#141]
Hi All,

Can anyone please share how I can use likwid to log request from cores to each of the 8 EDC (MCDRAM) and 2 MC (DDR4) for Xeon Phi? I have used perf tool and finding a bit difficult to understand how likwid can be used in similar way perf can. 

Also, if anyone can share specific raw events that I can plug to perf that can get me above data, then that will be useful too. I raised similar question on [Intel forum](https://software.intel.com/en-us/forums/software-tuning-performance-optimization-platform-monitoring/topic/754695) if anyone would like to take a look.

Thanks.

**Comment by TomTheBear** [comment]
Hi,
as you will probably know from the Intel forum, you get the counts for DDR4 and MCDRAM only for all cores and not for single cores (if you want to have them almost exact). There are specific DDR4 and MCDRAM bits for the OFFCORE_RESPONSE events but there tend to be less accurate and provide only load traffic counts (when I remember it properly).

With LIKWID you have multiple groups to measure DDR4 and MCDRAM (which could be combined to a single group) called MEM and HBM. There are also the groups HBM_OFFCORE (which uses the OFFCORE_RESPONSE events) and HBM_CACHE (if the MCDRAM is configured in cache mode, currently only usable with the perf_event backend).

Just as a hint, you can omit the options for perf with hex masks 0x0, so `perf stat -a -e uncore_edc_uclk_0/period=0x0,inv=0x0,edge=0x0,event=0x2,umask=0x1,thresh=0x0/` can be written as `perf stat -a -e uncore_edc_uclk_0/event=0x2,umask=0x1/`.

**Comment by PatilChetan** [comment]
@TomTheBear - Thank you.
