### ISSUE TITLE
likwid-setFrequencies on SNB reports missing Uncore as error

### ISSUE THREAD

**Issue by rrzeschorscherl** [RRZE-HPC/likwid#143]
Version 4.3.1 on E5-2680:

```
$ likwid-setFrequencies -p
Current CPU frequencies:
CPU 0: governor  performance min/cur/max 1.2/2.7/2.7 GHz Turbo 0
[...]

ERROR - [./src/frequency.c:freq_getUncoreFreqMin:853] No such file or directory.
Cannot read register 0x620 on CPU 0
No support for Uncore frequencies
```

No big deal but there first two lines of the error message at the bottom are really dispensable.

Cheers,
Georg.

**Comment by TomTheBear** [comment]
This has been fixed in https://github.com/RRZE-HPC/likwid/commit/4973d0e41d9ce19b48992f228eedba788fe9fbf1
You only get the last line on systems that don't provide the UNCORE_FREQ register.
