### ISSUE TITLE
likwid-perfctr reporting wrong runtime on Intel Skylake SP

### ISSUE THREAD

**Issue by cw585968** [RRZE-HPC/likwid#144]
Hi everyone,

I am experiencing problems when trying to use the most recent release of likwid (4.3.1) on an Intel Skylake SP machine.

I was trying to measure some performance groups with likwid-perfctr on different benchmarks, but when looking at the results likwid produced I got quite confused. The runtime displayed by likwid was way off the runtime reported by the benchmarks' internal measurements. I then tried to simplify the problem. I used `sleep ${sec}` to mimic different amounts of runtime of an application and saw that the runtime displayed by likwid was wrong when running longer than 30 seconds. This also appeared on multiples of 30 seconds (exact output at the end of the issue just for completeness).

Looking for a solution I performed tests on other machines like Intel Broadwell EP and Intel Haswell EP, which did not show the same issues. Then I found a commit named "[Likwid reads all counters in the background every 30 seconds to recognize overflows where not overflow bits exist](https://github.com/RRZE-HPC/likwid/commit/d6c5552ed36a30edb4e8b7bfda174c4b80babbaa)" which I think points to the right direction, although I myself was not able to identify the problem. I then tried to change the value of `duration` at `src/applications/likwid-perfctr.lua#L793` to see if this would result in different reset times and indeed it did.

Down below I provide some system information which I hope could help to find the issue.

Greetings

Christian Wassermann

The OS is: Ubuntu 17.10
Hardware Managed P-States / Intel SpeedShift is activated.
GCC version: 7.2.0

```shell
for i in $(seq 0 70); do
    echo -n "${i}: "; likwid-perfctr -c 0 -g CLOCK sleep ${i} | grep "|  Runtime" | awk '{ print $2,$6 }'
done
# resulted in:
0: Runtime 0.0026
1: Runtime 1.0047
2: Runtime 2.0115
3: Runtime 3.0174
4: Runtime 4.0126
5: Runtime 5.0068
6: Runtime 6.0051
7: Runtime 7.0046
8: Runtime 8.0050
9: Runtime 9.0002
10: Runtime 10.0379
11: Runtime 11.0233
12: Runtime 12.0100
13: Runtime 13.0081
14: Runtime 14.0021
15: Runtime 15.0430
16: Runtime 16.0551
17: Runtime 17.0091
18: Runtime 17.9648
19: Runtime 19.0413
20: Runtime 20.0154
21: Runtime 20.9625
22: Runtime 22.1623
23: Runtime 23.0170
24: Runtime 23.9277
25: Runtime 25.0434
26: Runtime 25.9882
27: Runtime 27.0817
28: Runtime 28.0269
29: Runtime 28.9109
30: Runtime 0.0017
31: Runtime 0.9974
32: Runtime 2.0037
33: Runtime 3.0041
34: Runtime 4.0075
35: Runtime 5.0390
36: Runtime 5.9759
37: Runtime 7.0278
38: Runtime 7.9850
39: Runtime 9.0159
40: Runtime 10.0413
41: Runtime 10.9607
42: Runtime 12.0579
43: Runtime 12.9937
44: Runtime 13.9734
45: Runtime 15.0264
46: Runtime 16.1112
47: Runtime 16.9813
48: Runtime 17.9404
49: Runtime 19.0511
50: Runtime 20.1603
51: Runtime 20.9879
52: Runtime 21.9698
53: Runtime 22.9258
54: Runtime 23.9788
55: Runtime 25.1119
56: Runtime 26.2202
57: Runtime 27.2164
58: Runtime 27.9820
59: Runtime 28.9744
60: Runtime 29.9631
61: Runtime 0.9898
62: Runtime 1.9938
63: Runtime 3.0016
64: Runtime 3.9988
65: Runtime 4.9935
66: Runtime 5.9818
67: Runtime 6.9942
68: Runtime 7.9924
69: Runtime 9.0061
70: Runtime 9.9802
```
```shell
$ cat /proc/cpuinfo
processor	: 87
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Gold 6152 CPU @ 2.10GHz
stepping	: 4
microcode	: 0x2000030
cpu MHz		: 2100.000
cache size	: 30976 KB
physical id	: 1
siblings	: 44
core id		: 28
cpu cores	: 22
apicid		: 121
initial apicid	: 121
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin intel_pt mba tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 4200.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```
[config.mk.txt](https://github.com/RRZE-HPC/likwid/files/1685499/config.mk.txt)

**Comment by TomTheBear** [comment]
The problem was not in the Lua part but in the library when calculating the metric results. I have put in the wrong runtime value.

**Comment by cw585968** [comment]
Thanks for the quick fix 👍
