### ISSUE TITLE
Likwid exits when register is already in use

### ISSUE THREAD

**Issue by hahnjo** [RRZE-HPC/likwid#150]
Likwid currently calls `exit(0)` when a register is already in use:
https://github.com/RRZE-HPC/likwid/blob/f15df41729bc3e9ce08e49d69cd9ac4eb9c204c7/src/perfmon.c#L278

1. That shouldn't happen when using the C API, an error code would be more helpful.
2. If at all the process should indicate that there was an error with a non-zero return value.

**Comment by hahnjo** [comment]
The current isn't much better and the API returns no error at all if Likwid cannot access a register. How is a program supposed to check this?

**Comment by TomTheBear** [comment]
You get a NOTYPE back instead of an exit. NOTYPE means 'Counter not usable for LIKWID'

**Comment by hahnjo** [comment]
How is that propagated if I call `perfmon_addEventSet`?

**Comment by TomTheBear** [comment]
It is not propagated back to the caller. The only method to find it out is by checking the type of each event afterwards. You only get an error (EINVAL) back if all counters in the eventset are in-use.

**Comment by hahnjo** [comment]
I don't think there is an API to check the type of an event (in a group) or I'm unable to find it in the documentation.

**Comment by TomTheBear** [comment]
You are right both times, there is no such API call and only testcpu is checked.
