### ISSUE TITLE
Replace perl she-bangline

### ISSUE THREAD

**Issue by fendor** [RRZE-HPC/likwid#153]
On some Unix variations, perl is not installed in `/usr/bin/perl`, e.g. in NixOS.
This forced me, to manually replace all occurrences of `#!/usr/bin/perl` to `#!/usr/bin/env perl`.
Then I was able to successfully compile the likwid tools.

Would it be possible to replace `#!/usr/bin/perl` in upstream with `#!/usr/bin/env perl`?
It should have the same functionality while simplifying the installation process for some Operating Systems and likwid is then, overall, more portable.

**Comment by TomTheBear** [comment]
Thank you for the PR. The perl scripts havn't been touch for a long time.
