### ISSUE TITLE
Failed Build for MIC

### ISSUE THREAD

**Issue by LefterisChris** [RRZE-HPC/likwid#16]
Hello, 
I was trying to build likwid for Intel xeon phi, but although I followed the configurations indicated, I got the following error:

===>  COMPILE  MIC/timer.o
/tmp/icckuOoB2as_.s: Assembler messages:
/tmp/icckuOoB2as_.s:109: Error: `rdtscp' is not supported on `k1om'
make: *** [MIC/timer.o] Error 1

I looked into config_defines.mk for the flag DHAS_RDTSCP but I couldn' t find, I also added it manually to default value 0 but the problem still occurs.
Is there any way around? 

Thanks in advance

**Comment by TomTheBear** [comment]
Hi,

the define was kicked some time ago and the decision whether the instruction should be used or not is now done dynamically in src/timer.c.  The decision is based on a cpuid bitflag that indicates whether the rdtscp instruction is available or not.
I tried building LIKWID for a Xeon Phi with ICC 13.1.3.192 Build 20130607 and got no problems. But when I use the newest version that is installed on our cluster 15.0.2.164 Build 20150121 I got the same error.
I corrected it a few seconds ago in commit 99e7fcca164486574f0330e9032f68749131022d . Please update your repository clone and try again.

Greetings,
Thomas

**Comment by LefterisChris** [comment]
Thanks a lot!
