### ISSUE TITLE
inconsistency: CPI Stat 

### ISSUE THREAD

**Issue by yogeshVU** [RRZE-HPC/likwid#160]
I am trying to interpret this command:

```
likwid-perfctr -g CACHES sleep 6
```

Under the CPI STAT metric, the sum and the average are both zero.

[loglink](https://gist.github.com/yogeshVU/916282807eb26b626b7305d3af6eed2e)

Is it correct?

**Comment by TomTheBear** [comment]
This bug was fixed in April (https://github.com/RRZE-HPC/likwid/commit/432e996d588f5297572fc490405828ed171bb7a1)
