### ISSUE TITLE
broadwellEP caches bw measurement

### ISSUE THREAD

**Issue by yogeshVU** [RRZE-HPC/likwid#163]
are the registers correctly utilized for L3 bandwidth calculation for this arch.

I am refering to the L3 bandwidth calculation in L3 group and the CACHE group

[CACHES_GROUP](https://github.com/RRZE-HPC/likwid/blob/master/groups/broadwellEP/CACHES.txt#L83)

[L3_GROUP](https://github.com/RRZE-HPC/likwid/blob/master/groups/broadwellEP/L3.txt#L19)

Shouldn't it be:

[L3-system](https://github.com/RRZE-HPC/likwid/blob/master/groups/broadwellEP/CACHES.txt#L96)

**Comment by TomTheBear** [comment]
No, that's all correct. In the L3 group, the counters `PMC0` and `PMC1` are configured to measure the cache lines being loaded into L2 from L3 (`L2_LINES_IN_ALL`) and dirty lines being evicted from L2 to L3 (`L2_LINES_OUT_DEMAND_DIRTY`). Consequently, the sum `PMC0+PMC1` gives you the total transferred cache lines.
In the CACHES groups, the counters `PMC0` and `PMC1` are configured with different events. `PMC0` counts all cache lines being replaced in L1 from L2 (`L1D_REPLACEMENT`) and `PMC1` measures the cache lines being written back from L1 to L2 (`L2_TRANS_L1D_WB`). The two events from the L3 group are measured in `PMC2` and `PMC3`, see the EVENTSET in CACHES section. Consequently, to get the same metric as in the L3 group, the calculation is `PMC2+PMC3`. The L3-system metrics measure the data traffic between L3 and memory/other socket/...

The logic in the performance group files is that you define the eventset (list of counter + event) in the EVENTSET section and use the counter names (`PMCx`, `CBOXxCy`, `FIXCx`, `PWRx`, ...) as variables in the metric formulas in the METRICS section.

**Comment by yogeshVU** [comment]
wow,, thanks for that clarification...I had incorrectly interpreted the counter values
