### ISSUE TITLE
Segfault when using likwid_markerRegisterRegion with perf_event backend

### ISSUE THREAD

**Issue by ohlmann** [RRZE-HPC/likwid#164]
When calling `likwid_markerRegisterRegion` from the Fortran interface, likwid segfaults in `HPMaddThread` when the `perf_event` backend is used. If the call to `likwid_markerRegisterRegion` is omitted, it works fine.

**Comment by TomTheBear** [comment]
This was a simple fix. I allocate an array in HPMinit() but this function is not called with perf_event backend. Thanks for reporting.
