### ISSUE TITLE
likwid-mpirun: uncore counters are not passed to likwid-perfctr

### ISSUE THREAD

**Issue by ohlmann** [RRZE-HPC/likwid#167]
When using likwid-mpirun, the uncore counter should be read only by the first core of each socket. However, some comparison of the cpu id in the lua script was done between a string and numbers and thus no cores were identified to record the uncore events.

A possible fix is available in [PR 166](https://github.com/RRZE-HPC/likwid/pull/166).

**Comment by TomTheBear** [comment]
Thanks for reporting. I thought this works good since the string `cpuexpr` is translated to a list of integer lists in `calculatePinExpr()` or `calculateCpuExprs()` before using `cpustr_to_cpulist` but a cast to number doesn't hurt.
