### ISSUE TITLE
Segfault with null pointer dereference 

### ISSUE THREAD

**Issue by gscheidling13** [RRZE-HPC/likwid#169]
Version: likwid 4.3.x
Platform: SuSE Linux 12 SP1 ; gcc version 4.8.5 (SUSE Linux) ; SGI UV3000 (144 Sockets; Intel(R) Xeon(R) CPU E5-4650 v3 @ 2.10GHz)
             
config.mk:
mach2:/apps/LIKWID # more DIST-accessD/likwid-master/config.mk
#################################################################
#################################################################
# Configuration options                                         #
#################################################################
#################################################################

# Please have a look in INSTALL and the WIKI for details on
# configuration options setup steps.
# supported: GCC, CLANG, ICC, MIC (ICC), GCCX86 (for 32bit systems)
COMPILER = GCC#NO SPACE

# Path were to install likwid
PREFIX = /apps/LIKWID/inst430-accessD#NO SPACE

# Set the default mode for MSR access.
# This can usually be overriden on the commandline.
# Valid values are: direct, accessdaemon and perf_event
ACCESSMODE = accessdaemon#NO SPACE

# Build Fortran90 module interface for Marker API. Adopt Fortran compiler
# in ./make/include_<COMPILER>.mk if necessary. Default: ifort (even for
# COMPILER=GCC)
FORTRAN_INTERFACE = false#NO SPACE

# Instrument likwid-bench with Marker API calls for use with likwid-perfctr
INSTRUMENT_BENCH = true#NO SPACE

#################################################################
#################################################################
# Advanced configuration options                                #
# Most users do not need to change values below this comment!   #
#################################################################
#################################################################

# Define the color of the likwid-pin output
# Can be NONE, BLACK, RED, GREEN, YELLOW, BLUE,
# MAGENTA, CYAN or WHITE
COLOR = CYAN#NO SPACE

# Some path definitions
MANPREFIX = $(PREFIX)/man#NO SPACE
BINPREFIX = $(PREFIX)/bin#NO SPACE
LIBPREFIX = $(PREFIX)/lib#NO SPACE

# These paths are hardcoded into executables and libraries. Usually
# they'll be the same as above, but package maintainers may want to
# distinguish between the image directories and the final install
# target.
# Keep in mind that the access and setFreq daemon need enough
# privileges that may be deleted when copying the files to
# the INTSTALLED_PREFIX
INSTALLED_PREFIX = $(PREFIX)#NO SPACE
INSTALLED_BINPREFIX = $(INSTALLED_PREFIX)/bin#NO SPACE
INSTALLED_LIBPREFIX = $(INSTALLED_PREFIX)/lib#NO SPACE

# For the daemon based secure msr/pci access configure
# the absolute path to the msr daemon executable.
ACCESSDAEMON = $(PREFIX)/sbin/likwid-accessD#NO SPACE
INSTALLED_ACCESSDAEMON = $(INSTALLED_PREFIX)/sbin/likwid-accessD#NO SPACE

# Build the accessDaemon. Have a look in the WIKI for details.
BUILDDAEMON = true#NO SPACE
# Build the setFrequencies daemon to allow users setting the CPU and Uncore
# frequency
BUILDFREQ = true#NO SPACE

# chown installed tools to this user/group
# if you change anything here, make sure that the user/group can access
# the MSR devices and (on Intel) the PCI devices.
INSTALL_CHOWN = -g root -o root#NO SPACE

# uncomment to optionally set external lua@5.2 or lua@5.3:
# default is use internally provide lua
#LUA_INCLUDE_DIR = /usr/include/lua5.2#NO SPACE
#LUA_LIB_DIR = /usr/lib/x86_64-linux-gnu#NO SPACE
#LUA_LIB_NAME = lua5.2#NO SPACE, executable is assumed to have the same name
#LUA_BIN = /usr/bin#NO SPACE

# Change to true to a build shared library instead of a static one
# It is NOT recommended to switch to static libraries as some features don't
# work when compiled statically
SHARED_LIBRARY = true#NO SPACE

# Build LIKWID with debug flags
#03-Jul-2018 MeJ ... DEBUG = false#NO SPACE
DEBUG = true#NO SPACE

# Basic configuration for some internal arrays.
# Maximal number of hardware threads
MAX_NUM_THREADS = 5000
# Maximal number of sockets
MAX_NUM_NODES = 300

# Paths to some configuration files that can be used to overwrite some
# array lengths defined at compilation
CFG_FILE_PATH = $(INSTALLED_PREFIX)/etc/likwid.cfg
# With the likwid-genTopoCfg it is possible to store the topology of a system
# in a file to avoid re-reading all topology informations again
TOPO_FILE_PATH = $(INSTALLED_PREFIX)/etc/likwid_topo.cfg

# Versioning Information
# The libraries are named liblikwid.<VERSION>.<RELEASE>
VERSION = 4
RELEASE = 3
MINOR = 0
# Date when the release is published
#03-Jul-2018 MeJ ... DATE    = 03.08.2017 
# --> we use the file timestamp in the master.zip file from GitHUB
DATE    = 27.06.2018

# In come cases it is important to set the rpaths for the LIKWID library. One
# example is the use of sudo because it resets environment variables like
# LD_LIBRARY_PATH
RPATHS = -Wl,-rpath=$(INSTALLED_LIBPREFIX)

# LIKWID uses a lock to avoid simultaneous usage by multiple users. The user
# owning this file has access to the LIKWID library and can use LIKWID
# simultaneously.
LIKWIDLOCKPATH = /var/tmp/likwid.lock

# The access daemon creates sockets under this path to communicate with the
# LIKWID library.
LIKWIDSOCKETBASE = /tmp/likwid  # -%d will be added automatically to the socket name

# The pinning library is put in LD_PRELOAD when using LIKIWD for thread/process
# pinning. The library overloads the pthread_create function to pin threads
# directly after their creation
LIBLIKWIDPIN = $(abspath $(INSTALLED_LIBPREFIX)/liblikwidpin.so.$(VERSION).$(RELEASE))

# Some tools (likwid-perfctr and likwid-topology) provide the export of their
# output to a file. LIKWID tries to format the file based on the file suffix.
# The folder contains scripts named as the file suffix, like xml, which read
# the CSV output of the tools and perform the conversation to the desired file
# format
LIKWIDFILTERPATH = $(abspath $(INSTALLED_PREFIX)/share/likwid/filter)

# LIKWID uses txt-files as input for the performance groups. The configured
# folder contains folders for each architecture with the architecture-specific
# performance group files. Despite this folder, LIKWID also checks
# $HOME/.likwid/groups
LIKWIDGROUPPATH = $(abspath $(INSTALLED_PREFIX)/share/likwid/perfgroups)

Commands:
**1. step: run (generate a .cfg)**
uv3000:/ # /apps/LIKWID/inst430-accessD/bin/likwid-genTopoCfg 
Writing new topology file /apps/LIKWID/inst430-accessD/etc/likwid_topo.cfg

uv3000:/ # wc -l /apps/LIKWID/inst430-accessD/etc/likwid_topo.cfg
30138 /apps/LIKWID/inst430-accessD/etc/likwid_topo.cfg

**2. step: run perfctr (which would use (read in the .cfg file ... for quick startup):**
uv3000:/ # gdb /apps/LIKWID/inst430-accessD/bin/likwid-lua
GNU gdb (GDB; SUSE Linux Enterprise 12) 8.0.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /apps/LIKWID/inst430-accessD/bin/likwid-lua...done.
(gdb) run /apps/LIKWID/inst430-accessD/bin/likwid-perfctr --verbose 3 -C 0,1,2 -g BRANCH sleep 1
Starting program: /apps/LIKWID/inst430-accessD/bin/likwid-lua /apps/LIKWID/inst430-accessD/bin/likwid-perfctr --verbose 3 -C 0,1,2 -g BRANCH sleep 1
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.22-62.10.1.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Detaching after fork from child process 749184.
DEBUG - [topology_init:1013] Reading topology information from /apps/LIKWID/inst430-accessD/etc/likwid_topo.cfg
INFO: You are running LIKWID in a cpuset with 12 CPUs. Taking given IDs as logical ID in cpuset

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5f07a72 in likwid_hwloc_get_type_depth (topology=0x0, 
    type=LIKWID_hwloc_OBJ_PU) at ./hwloc/traversal.c:21
21	  return topology->type_depth[type];
(gdb) where
#0  0x00007ffff5f07a72 in likwid_hwloc_get_type_depth (topology=0x0, 
    type=LIKWID_hwloc_OBJ_PU) at ./hwloc/traversal.c:21
#1  0x00007ffff64f372c in likwid_hwloc_get_nbobjs_by_type (topology=0x0, 
    type=LIKWID_hwloc_OBJ_PU)
    at /apps/LIKWID/DIST-accessD/likwid-master/ext/hwloc/include/hwloc/inlines.h:65
#2  0x00007ffff64f3c35 in create_lookups () at ./src/affinity.c:193
#3  0x00007ffff64f4006 in affinity_init () at ./src/affinity.c:294
#4  0x00007ffff64cfdf8 in cpustr_to_cpulist_logical (bcpustr=0x6c6140, 
    cpulist=0x6c4630, length=1728) at ./src/cpustring.c:469
#5  0x00007ffff64d1869 in cpustr_to_cpulist (cpustring=0x60ac68 "0,1,2", 
    cpulist=0x6c29d0, length=1728) at ./src/cpustring.c:908
#6  0x00007ffff64df55d in lua_likwid_cpustr_to_cpulist (L=0x604018)
    at ./src/luawid.c:1363
#7  0x00007ffff7bb157f in luaD_precall (L=L@entry=0x604018, func=func@entry=0x60e550, 
    nresults=nresults@entry=2) at ./src/ldo.c:360
#8  0x00007ffff7bc3ba1 in luaV_execute (L=L@entry=0x604018) at ./src/lvm.c:1115
#9  0x00007ffff7bb195f in luaD_call (L=L@entry=0x604018, func=<optimized out>, 
    nResults=<optimized out>) at ./src/ldo.c:491
#10 0x00007ffff7bb19b1 in luaD_callnoyield (L=0x604018, func=<optimized out>, 
    nResults=<optimized out>) at ./src/ldo.c:501
#11 0x00007ffff7bb0daf in luaD_rawrunprotected (L=L@entry=0x604018, 
    f=f@entry=0x7ffff7bc84e0 <f_call>, ud=ud@entry=0x7fffffffdbe0) at ./src/ldo.c:142
#12 0x00007ffff7bb1c0d in luaD_pcall (L=L@entry=0x604018, 
    func=func@entry=0x7ffff7bc84e0 <f_call>, u=u@entry=0x7fffffffdbe0, old_top=80, 
    ef=<optimized out>) at ./src/ldo.c:722
#13 0x00007ffff7bc9a0e in lua_pcallk (L=L@entry=0x604018, nargs=nargs@entry=8, 
    nresults=nresults@entry=-1, errfunc=errfunc@entry=3, ctx=ctx@entry=0, 
    k=k@entry=0x0) at ./src/lapi.c:968
#14 0x00000000004018cb in docall (L=L@entry=0x604018, narg=narg@entry=8, 
    nres=nres@entry=-1) at ./src/lua.c:203
#15 0x0000000000402561 in handle_script (argv=<optimized out>, L=0x604018)
    at ./src/lua.c:443
#16 pmain (L=0x604018) at ./src/lua.c:577
#17 0x00007ffff7bb157f in luaD_precall (L=L@entry=0x604018, func=0x604640, nresults=1)
    at ./src/ldo.c:360
#18 0x00007ffff7bb1953 in luaD_call (L=L@entry=0x604018, func=<optimized out>, 
---Type <return> to continue, or q <return> to quit---q
nResultsQuit
(gdb) info args
topology = 0x0
type = LIKWID_hwloc_OBJ_PU
(gdb) pwd
Working directory /.
(gdb) list
16	#endif /* HAVE_STRINGS_H */
17	
18	int
19	hwloc_get_type_depth (struct hwloc_topology *topology, hwloc_obj_type_t type)
20	{
21	  return topology->type_depth[type];
22	}
23	
24	hwloc_obj_type_t
25	hwloc_get_depth_type (hwloc_topology_t topology, unsigned depth)
(gdb) up
#1  0x00007ffff64f372c in likwid_hwloc_get_nbobjs_by_type (topology=0x0, 
    type=LIKWID_hwloc_OBJ_PU)
    at /apps/LIKWID/DIST-accessD/likwid-master/ext/hwloc/include/hwloc/inlines.h:65
65	  int depth = hwloc_get_type_depth(topology, type);
(gdb) info args
topology = 0x0
type = LIKWID_hwloc_OBJ_PU
(gdb) list
60	}
61	
62	static __hwloc_inline int
63	hwloc_get_nbobjs_by_type (hwloc_topology_t topology, hwloc_obj_type_t type)
64	{
65	  int depth = hwloc_get_type_depth(topology, type);
66	  if (depth == HWLOC_TYPE_DEPTH_UNKNOWN)
67	    return 0;
68	  if (depth == HWLOC_TYPE_DEPTH_MULTIPLE)
69	    return -1; /* FIXME: agregate nbobjs from different levels? */
(gdb) 

Ctrl-C

The Question is: Is the hwloc_topology init currently _supposed to work_ with 
(against) a cached .cfg file?

Viele Grüße nach Regensburg 

hans messner

**Comment by TomTheBear** [comment]
Thanks for the detailed outputs. 
LIKWID tries to read the topology config file first but has a fallback to initialize the topology from scratch through hwloc. If the file can be read properly, there shouldn't be calls to hwloc. But since the file option is rarely used, it might be that there were some bugs introduced over the last years. I think I know already the location, the affinity module wants the read some data from hwloc instead of using the read in topology.
I just have to check how I can test this as your systems is somewhat special and the bug might not occur on small to normal systems.

**Comment by TomTheBear** [comment]
This seems to not be a problem anymore, see #170.
