### ISSUE TITLE
Shared Library

### ISSUE THREAD

**Issue by LefterisChris** [RRZE-HPC/likwid#17]
Hello again,
I am using the latest version of likwid and when I run likwid-perfctr with an executable, which uses omp, i get the following error:
./helloflops3_xphi: error while loading shared libraries: libiomp5.so: cannot open shared object file: No such file or directory

I looked around and found that because likwid-lua has set the setuid bit, it ignores env LD_LIBRARY_PATH, thus the exec cannot link with libiomp5.so 
Moreover the exec is dynamically linked with: 
        linux-vdso.so.1 =>  (0x00007fff67bff000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f28b3d64000)
	libiomp5.so => /home/echristof/libraries/libiomp5.so (0x00007f28b3a4e000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f28b383c000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f28b361f000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f28b32c7000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f28b30c3000)
	/lib64/ld-linux-k1om.so.2 (0x00007f28b3f93000)

and likwid-lua: 
        linux-vdso.so.1 =>  (0x00007fff279dd000)
	liblikwid-lua.so.4 => /home/echristof/likwid_mic/lib/liblikwid-lua.so.4 (0x00007ff84f2c9000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff84f099000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff84ee95000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007ff84ec83000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff84ea65000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff84e70d000)
	libimf.so => /home/echristof/libraries/libimf.so (0x00007ff84e2b4000)
	libsvml.so => /home/echristof/libraries/libsvml.so (0x00007ff84dade000)
	libirng.so => /home/echristof/libraries/libirng.so (0x00007ff84d8cb000)
	libintlc.so.5 => /home/echristof/libraries/libintlc.so.5 (0x00007ff84d6aa000)
	/lib64/ld-linux-k1om.so.2 (0x00007ff84f55d000)

Only libiomp5.so is missing.
One solution would be to link them statically. Is there another solution through likwid-lua maybe?

Thanks in advance!

**Comment by TomTheBear** [comment]
You have to add the path to the Intel libraries in make/config_MIC.mk at RPATHS variable, see INSTALL file section Build on Xeon Phi

Greetings,
Thomas

**Comment by LefterisChris** [comment]
I have already modified make/include_MIC.mk:
LFLAGS   =  -pthread -g -mmic
RPATHS += -Wl,-rpath=/home/echristof/libraries 
SHARED_CFLAGS = -fpic -mmic -fvisibility=hidden -rpath=/home/echristof/libraries
SHARED_LFLAGS = -shared -mmic -fvisibility=hidden -rpath=/home/echristof/libraries

where rpath points to the directory on mic with the .so files. 
Do i need to add something? 
Thanks

**Comment by TomTheBear** [comment]
In my tests I didn't change the SHARED_* variables. Only the RPATHS variable. Likwid itself does not require OpenMP, it only uses Pthreads.

Have you tried: likwid-perfctr <options> ldd <executable> ? Is your executable also compiled with rpath? When LD_LIBRARY_PATH is skipped for suid-root executables, the wrapped executable does not have a valid LD_LIBRARY_PATH either.

**Comment by LefterisChris** [comment]
Indicating rpath when compiling the executable fixed the problem! 
Thank you for you prompt replies!
