### ISSUE TITLE
likwid-powermeter error inside slurm job

### ISSUE THREAD

**Issue by mrbtudocb** [RRZE-HPC/likwid#172]
Version: git version 07/16/18
Slurm version: 17.11.3-2

Inside a slurm job likwid-powermeter fails with the following error:

: likwid-powermeter 
/sfw/likwid/git160718/bin/likwid-lua: /sfw/likwid/git160718/bin/likwid-powermeter:175: table index is nil
stack traceback:
	/sfw/likwid/git160718/bin/likwid-powermeter:175: in main chunk
	[C]: in ?

Outside slurm likwid-powermeter  works without problems.

Best regards
Christian

**Comment by TomTheBear** [comment]
This is probably caused by running in a cpuset where the machine has multiple sockets but one of it has no CPUs (caused by the cpuset).

**Comment by mrbtudocb** [comment]
You're right, requesting a complete node with all cores fixes the problem.

Thanks a lot.

**Comment by TomTheBear** [comment]
I'll fix it even when running inside a cpuset, so I reopen this issue to keep me reminded.

**Comment by TomTheBear** [comment]
I tested it in a taskset cpuset and could reproduce the error. The fix works for taskset cpuset, I havn't tested cgroup cpuset but I'm confident that it works there, too.
