### ISSUE TITLE
Some groups broken on Skylake SP

### ISSUE THREAD

**Issue by hahnjo** [RRZE-HPC/likwid#182]
* `CACHES`
```
WARN: Counter CBOX28C0 not defined for current architecture
```
 * `L3CACHE`
```
WARN: Event MEM_LOAD_UOPS_RETIRED_L3_ALL not found for current architecture
WARN: Event MEM_LOAD_UOPS_RETIRED_L3_MISS not found for current architecture
```
 * `MEM_DP`
```
WARN: Counter MBOX6C0 not defined for current architecture
WARN: Counter MBOX6C1 not defined for current architecture
WARN: Counter MBOX7C0 not defined for current architecture
WARN: Counter MBOX7C1 not defined for current architecture
```
 * `TLB_DATA`
```
WARN: Event DTLB_LOAD_MISSES_WALK_DURATION not found for current architecture
WARN: Event DTLB_STORE_MISSES_WALK_DURATION not found for current architecture
```
 * `TLB_INSTR`
```
WARN: Event ITLB_MISSES_WALK_DURATION not found for current architecture
```

**Comment by TomTheBear** [comment]
* CACHES:
Fixed in https://github.com/RRZE-HPC/likwid/commit/9a0a23f48274bd070fc2b32a997b921e2452404d

* L3CACHE, MEM_DP, TLB_DATA and TLB_INSTR
Fixed in https://github.com/RRZE-HPC/likwid/commit/c8c6a336dfeb3f2b7a9c0c179548646483aa542e

Thanks for reporting

**Comment by TomTheBear** [comment]
* CACHES
Fixed in https://github.com/RRZE-HPC/likwid/commit/9a0a23f48274bd070fc2b32a997b921e2452404d

* L3CACHE, MEM_DP, TLB_DATA and TLB_INSTR
Fixed in https://github.com/RRZE-HPC/likwid/commit/c8c6a336dfeb3f2b7a9c0c179548646483aa542e
