### ISSUE TITLE
likwid-setFrequencies, segment fault

### ISSUE THREAD

**Issue by allenbunny** [RRZE-HPC/likwid#185]
on my centos 7.3, I can't use likwid-setFrequencies
```

[root@localhost runtmp]# likwid-setFrequencies -p -V 3
DEBUG: Given CPU expression expands to 24 CPU cores:
DEBUG: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
DEBUG: Given CPU expression expands to 2 CPU sockets:
DEBUG: 0,1
Unable to open path /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq for reading
	EXIT WITH ERROR:  Max Freq. could not be read
[root@localhost runtmp]# find / -name scaling_cur_freq
[root@localhost runtmp]# likwid-setFrequencies -l -V 3
DEBUG: Given CPU expression expands to 24 CPU cores:
DEBUG: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
DEBUG: Given CPU expression expands to 2 CPU sockets:
DEBUG: 0,1
段错误(吐核)    
```
'likwid-setFrequencies -l ' get segment fault

/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq this file does not exist

**Comment by TomTheBear** [comment]
Does the folder exist at all? If yes, there should be a file `scaling_driver` which contains the name of the CPU frequency driver. In my case it's `acpi-cpufreq`. If you use the `intel-pstate` driver, there should be a folder `/sys/devices/system/cpu/cpufreq/policy0` which contains the file. If none of the folders/files exist, try to load the kernel module `modprobe acpi-cpufreq` and try again

It would be good to have a backtrace of the segfault to see where it crashed:
```
gdb likwid-lua
run likwid-setFrequencies -p -V 3
```

**Comment by TomTheBear** [comment]
The folder `/sys/devices/system/cpu/intel_pstate` is already configured in LIKWID but the problem arises when getting the minimal and maximal supported frequency. This information is in the `cpuinfo_min_freq` and `cpuinfo_max_freq` files. If you find them and send me the locations, I could add them as additional search paths so that setFrequencies works for you and all other CentOS users.

**Comment by allenbunny** [comment]
```
[root@localhost cpufreq]# cd /sys/devices/system/cpu/intel_pstate
[root@localhost intel_pstate]# ls
max_perf_pct  min_perf_pct  no_turbo  num_pstates  turbo_pct
[root@localhost intel_pstate]# find / -name cpuinfo_min_freq
/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq
/sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_min_freq
/sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_min_freq
/sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_min_freq
.....
```

centos6 use acpi-cpufreq.  
centos 7 use intel_pstate. 
I use centos 7.3

**Comment by allenbunny** [comment]
```
[root@localhost intel_pstate]# cd /sys/devices/system/cpu/cpu0/cpufreq/
[root@localhost cpufreq]# ls
affected_cpus     cpuinfo_min_freq            scaling_available_governors  scaling_max_freq
cpuinfo_cur_freq  cpuinfo_transition_latency  scaling_driver               scaling_min_freq
cpuinfo_max_freq  related_cpus                scaling_governor             scaling_setspeed
[root@localhost cpufreq]# 
```

**Comment by TomTheBear** [comment]
Now I see, your system somehow mixes up the folders. Commonly you have the following:

* `acpi-cpufreq` driver: `/sys/devices/system/cpu/cpuX/cpufreq/`
* `intel_pstate` driver: `/sys/devices/system/cpu/intel_pstate` and `/sys/devices/system/cpu/cpufreq/policy0`

I'll add the folder to the frequency module

**Comment by allenbunny** [comment]
```
[root@localhost ~]# ll /sys/devices/system/cpu/cpufreq/policy0
ls: 无法访问/sys/devices/system/cpu/cpufreq/policy0: 没有那个文件或目录
[root@localhost ~]# find / -name policy0
[root@localhost ~]# 
```
/sys/devices/system/cpu/cpufreq/policy0 does not exist.

no file or fold names policy0.

I find 'cpupower' tool. maybe useful to you.

```
[root@localhost ~]# cpupower -c all frequency-info
analyzing CPU 0:
  driver: intel_pstate
  CPUs which run at the same hardware frequency: 0
  CPUs which need to have their frequency coordinated by software: 0
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 1.20 GHz - 3.30 GHz
  available cpufreq governors: performance powersave
  current policy: frequency should be within 1.20 GHz and 3.30 GHz.
                  The governor "powersave" may decide which speed to use
                  within this range.
  current CPU frequency: 1.20 GHz (asserted by call to hardware)
  boost state support:
    Supported: yes
    Active: yes

analyzing CPU 1:
...
```

When it's done, let me know, then i can reinstall likwid.

**Comment by allenbunny** [comment]
```
[root@localhost ~]# ll /sys/devices/system/cpu/cpu0/cpufreq/
affected_cpus                cpuinfo_transition_latency   scaling_governor
cpuinfo_cur_freq             related_cpus                 scaling_max_freq
cpuinfo_max_freq             scaling_available_governors  scaling_min_freq
cpuinfo_min_freq             scaling_driver               scaling_setspeed
```

scaling_cur_freq file not exist. do you mean cpuinfo_cur_freq?

**Comment by TomTheBear** [comment]
For reading you can use both files but for setting frequency you can use only the `scaling_*` files

**Comment by allenbunny** [comment]
```
[root@localhost grub]# cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed 
<unsupported>
[root@localhost grub]# cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors 
performance powersave
```
 It seems intel-pstate driver that has no userspace governor.
So intel-pstate can't set cpu freq? 

modprobe acpi-cpufreq, this command seems dont work at all. 
```
[root@localhost grub]# modprobe acpi-cpufreq
[root@localhost grub]# cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_driver
intel_pstate
intel_pstate
...
```

**Comment by TomTheBear** [comment]
I worked again on the frequency module and my above comment is wrong. You can control `acpi-cpufreq` and `intel_pstate` through CPU related files: `/sys/devices/system/cpu/cpu*/cpufreq/scaling_*`.
The new module uses a persistent daemon for the writes and performs all reads in the library. It uses only the CPU related files.
See https://github.com/RRZE-HPC/likwid/tree/persistent-freq-daemon
