### ISSUE TITLE
Wrong bytes/iteration count with daxpy in likwid-bench

### ISSUE THREAD

**Issue by rrzeschorscherl** [RRZE-HPC/likwid#195]
4.3.3

$ likwid-bench -t daxpy_avx512_fma -w S0:1GB:20:1:2
[...]
MFlops/s:               8486.64
Data volume (Byte):     511998689280
MByte/s:                67893.12
[...]

This is wrong - the benchmark does not account for the 24 bytes/iteration correctly although BYTES is set to 24 in the source. As far as I can see, this happens also, e.g., with the update benchmark (where only 8 bytes instead of 16 per scalar update are accounted for).

**Comment by TomTheBear** [comment]
Thanks for reporting. I have this issue already on my todo list.
