### ISSUE TITLE
Honor proposed Intel Hardware performance counter usage policy 

### ISSUE THREAD

**Issue by rrze-likwid** [RRZE-HPC/likwid#2]
Problem:

Likwid overwrites anything in the counter registers without asking. Intel proposed to allow using multiple tools without interference.

Solution:

Honor the solution of the Intel Whitepaper. Provide a overwrite mode.
Make init and setup of counters specific for the thread group and performance group. (Only overwrite register which are needed)

nate@verse.com:
> Intel's Performance Monitoring Unit Sharing Guide is attached.
> http://software.intel.com/file/30388

jan.eitzinger@fau.de:
> The paper is outdated. Further counters as Uncore (PCI based) and RAPL are not addressed.
> Therefore this issue is delayed.

bockelmann@org.dkrz.de:
> I really would like to see some method that checks whether the counters are already in use - Intel
> PCM reports within its init phase if the counters are not zeroed and ask to enforce a clearing.
> But there is also a conflict with tools like PAPI that rely on the Linux kernel perf_event interface:
> these tools do not set the MSRs directly and do not clean up at the end. So monitoring a node as
> root using likwid (or Intel PCM) might always fail if an application used the perf_event interface.

Thomas.Roehl@fau.de:
> The current trunk version checks the counter at the beginning. It skipps counters where the 
> control register is not empty. In general we wanted to avoid additional register reads at the 
> beginning as we have seen long access times for the MSRs in particular situations. But these 
> checks are needed so that we can use common control files for e.g. SandyBridge and 
> SandyBridge EP.
> In the end, LIKWID zeros the control registers but leaves the counter registers untouched. 

Thomas.Roehl@fau.de:
> This is not so easy to realize. Currently Likwid checks if registers are readable and writable but 
> does not fail when config registers are already in use. There is no flag like "--force".
> We think about it in Likwid 4.1

**Comment by TomTheBear** [comment]
The commit 8efa0ec46a30438e1b85eac3ba31ebe0b7a03303 adds the checks of the config registers and exits with warning if a config register is already in use. likwid-perfctr now has a flag to force overwriting of the counters. 
There may be some points in the sharing guide that are still not respected by LIKWID but this is better than nothing.

**Comment by TomTheBear** [comment]
Many users are annoyed by this feature, so I assume it works properly ;) Closing the issue.
