### ISSUE TITLE
run TutorialMarkerC obtain "Marker API result file does not exist. This may happen if the application has not called LIKWID_MARKER_CLOSE."

### ISSUE THREAD

**Issue by gengtsh** [RRZE-HPC/likwid#208]
hi,
i run the TutorialMarkerC second example, I try to use likwid-perfctr to obtain performance counters, e.g. L2CACHE. but i got "Marker API result file does not exist. This may happen if the application has not called LIKWID_MARKER_CLOSE"

basic my environment: 
1. i'm  one of the users of server, i'm one of soduers. there is no likwid env in the root .bashrc, so,     i need to use my own .bash_profile 

2. compile was fine
    **the command:**  sudo -E bash -c '/path to gcc bin/gcc -fopenmp -DLIKWID_PERFMON -I/path to likwid/likwid/4.3.2/include -L/path to likwid/likwid/4.3.2/lib hello.c -o hello -llikwid'
**i also run another command:** sudo /path to gcc bin/gcc -fopenmp -DLIKWID_PERFMON -I/path to likwid/likwid/4.3.2/include -L/path to likwid/likwid/4.3.2/lib hello.c -o hello -llikwid

3. but the run likwid i encountered an issue: 
   **the command:** sudo -i bash -c '/path to likwid/likwid/4.3.2/bin/likwid-perfctr -C S0:0 -g L3 -m ./hello'
   **the output:** 
--------------------------------------------------------------------------------
Failed to execute command: ./hello
--------------------------------------------------------------------------------
Marker API result file does not exist. This may happen if the application has not called LIKWID_MARKER_CLOSE.

the hello.c file is exactly the same of TutorialMarkerC second example, i'm pretty sure that there "LIKWID_MARKER_CLOSE" is in the end of hello.c

i'll be appreciated if you can help me out, thanks a lot.

**Comment by TomTheBear** [comment]
Why do you execute all commands with sudo? You can use gcc and LIKWID as user.
```
/tmp $ gcc -fopenmp -DLIKWID_PERFMON -I<include_dir> -L<lib_dir> hello.c -o hello -llikwid
/tmp $ likwid-perfctr -C S0:0 -g L3 -m ./hello
--------------------------------------------------------------------------------
CPU name:	Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
CPU type:	Intel Skylake processor
CPU clock:	4.01 GHz
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Region foo, Group 1: L3
[...]
```
I think the problem is not LIKWID but permissions. Maybe caused by security features of `sudo`.
```
/tmp $ sudo gcc -fopenmp -I /usr/local/include/ -L /usr/local/lib -DLIKWID_PERFMON hello.c -o hello / -llikwid
/tmp $ sudo -i bash -c "./hello"
bash: ./hello: No such file or directory
```
Can you execute `./hello` without LIKWID in your `sudo` environment?

Please use `sudo` with care. It is not thought for common tasks like compiling or running a program.

IF you really need it (LIKWID built with `ACCESSMODE=direct`), you should open a shell and run all commands in that single environment:

```
/tmp $ sudo bash
/tmp# gcc -fopenmp -I /usr/local/include/ -L /usr/local/lib -DLIKWID_PERFMON hello.c -o hello -llikwid
/tmp# /usr/local/bin/likwid-perfctr -C S0:0 -g L3 -m ./hello
--------------------------------------------------------------------------------
CPU name:	Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
CPU type:	Intel Skylake processor
CPU clock:	4.01 GHz
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Region foo, Group 1: L3
[...]
```

**Comment by gengtsh** [comment]
thanks  TomTheBear  reply me.
i did try 
/tmp $ sudo bash
/tmp# /path to gcc bin/gcc -fopenmp -I /path to likwid/include/ -L /path to likwid/lib -DLIKWID_PERFMON hello.c -o hello -llikwid
/tmp# /path to likwid/bin/likwid-perfctr -C S0:0 -g L3 -m ./hello

in this case, i got another error:
--------------------------------------------------------------------------------
./hello: error while loading shared libraries: liblikwid.so.4.3: cannot open shared object file: No such file or directory
--------------------------------------------------------------------------------
Marker API result file does not exist. This may happen if the application has not called LIKWID_MARKER_CLOSE.

**Comment by TomTheBear** [comment]
Your commands are (almost) correct although I'm still not sure why you use `sudo` at all.

You can do:
```
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path to likwid/lib
```
instead of setting the variable and exporting it afterwards.

You can post your questions on the user mailing list: http://groups.google.com/group/likwid-users
