### ISSUE TITLE
New releases please

### ISSUE THREAD

**Issue by robbat2** [RRZE-HPC/likwid#209]
Please make more regular releases, esp. after build system improvements!

**Comment by TomTheBear** [comment]
I'll try but my time is limited.

**Comment by TomTheBear** [comment]
https://github.com/RRZE-HPC/likwid/releases/tag/4.3.4

**Comment by robbat2** [comment]
Thanks! Added to Gentoo

**Comment by dirtyharrycallahan** [comment]
Curious why you need a release and not able to build off master?

**Comment by robbat2** [comment]
- shipping/mirroring release distribution tarballs
- Being able to reproduce results in semi-offline environments (pre-download a known versioned tarball)
- having a fixed point to base distribution patches against (e.g. https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-apps/likwid/files/likwid-4.3.1-fix-gnustack.patch you can see https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart for background)

**Comment by dirtyharrycallahan** [comment]
As someone who packages OSS for internal consumption I find snapshot packaging works for us.

https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_snapshots

**Comment by TomTheBear** [comment]
I can understand both approaches. We commonly install only the release versions on our systems except some test machines where I maintain a development version.

@robbat2 : Do you think it would be beneficial to integrate the gnustack patch in general? Or might it break anything for some use cases? On the wiki page I didn't find any downsides.

**Comment by robbat2** [comment]
@dirtyharrycallahan encouraging upstream projects to make formal releases that they have blessed is generally considered better than picking some arbitrary revision for a snapshot: because upstream should have a good idea if they consider the state of master to be blessed enough for packaging (and at that point they should just tag it!).

@TomTheBear I was meaning to find time to properly integrate the gnustack changes into the generation code. I inherited that specific patch from the prior maintainer.
