### ISSUE TITLE
how to analyse the system level metrics

### ISSUE THREAD

**Issue by gengtsh** [RRZE-HPC/likwid#214]
hi,
Many microarchitecture events are per logical CPU. What if I want to get a system level metric? Are there any system level hardware events I can use? For example, an event that counts the shared LLC's misses, or the bandwidth between LLC and memory,

**Comment by TomTheBear** [comment]
Likwid support the so-called Uncore counters. Uncore on server chips means L3 and below (memory controllers, socket interconnect,...). They exist per socket. They are measured by one hardware thread that is related to the Uncore (socket). Which thread depends on your choice of CPUs.

Please see the wiki for further Informationen which counters are provided for which micro-architecture.

If you want system-level, measure all CPUs for core-local events or one CPU per socket for Uncore events and see the STAT table.




<div>-------- Ursprüngliche Nachricht --------</div><div>Von: feiying <notifications@github.com> </div><div>Datum:28.03.2019  08:53  (GMT+01:00) </div><div>An: RRZE-HPC/likwid <likwid@noreply.github.com> </div><div>Cc: Subscribed <subscribed@noreply.github.com> </div><div>Betreff: [RRZE-HPC/likwid] how to analyse the system level metrics (#214) </div><div>
</div>hi,
Many microarchitecture events are per logical CPU. What if I want to get a system level metric? Are there any system level hardware events I can use? For example, an event that counts the shared LLC's misses, or the bandwidth between LLC and memory,

**Comment by gengtsh** [comment]
could you please tell me where I can find likwid per socket uncore event list information?

**Comment by TomTheBear** [comment]
`likwid-perfctr -e` lists all counters and events. The Uncore counters are not explicitly marked but all except PMC*, FIXC* and TMP* are Uncore counters. The counters are described in the wiki. For Skylake SP: https://github.com/RRZE-HPC/likwid/wiki/SkylakeSP
You can search for events using `likwid-perfctr -E <searchstr>`

Please use the mailing list for questions. There are more LIKWID users that can help you. In my opinion the issues are more development related and commonly it's only me who answers.
