### ISSUE TITLE
Provide minimal header for marker API

### ISSUE THREAD

**Issue by moebiusband73** [RRZE-HPC/likwid#215]
Currently the header likwid.h contains all likwid prototypes. If someone only uses the Marker API and wants that the code also compiles without likwid he has to either enclose all macros in additional ifdefs or create a header  with empty definitions of the macros. It would be better, especially for beginners, to provide such a header by default in likwid, and also document this as the recommended way to use the Marker API.

**Comment by mjklemm** [comment]
JM2C: I would not make a separate header, but rather make a new define that has to be set when the marker API should be active, e.g., 

`gcc -DLIKWID_ENABLE_MARKER_API ...`

If the define is not set, the likwid header defines all marker APIs as no-ops.

**Comment by moebiusband73** [comment]
This is exactly the way it already worked when I introduced the Marker API. The define created for this purpose is called LIKWID_PERFMON. The problem is that you also need to set the Marker macros to no-ops when likwid and therefore the likwid header ist not available.

This minimal header could be called likwid-markers.h and contain something like that:

https://github.com/RRZE-HPC/TheBandwidthBenchmark/blob/MARKERS/src/includes/likwid_markers.h

**Comment by mjklemm** [comment]
That just moves the problem to a different flavor, but does not solve it. :-)

If I do not have a copy of likwid anywhere on my machine, then I won't have that dummy header that makes the likwid macros a no-op.  So, a user will still have the same issue as before: a failing compilation.

**Comment by moebiusband73** [comment]
The plan is that you copy  this header into your project.
