### ISSUE TITLE
Broken ouput in likwid-mpirun -O

### ISSUE THREAD

**Issue by modkin** [RRZE-HPC/likwid#220]
In likwid 4.3.4 the csv output of likwid-mpirun was changed to the way it is in likwid-perfctr where the output is structured into multiple section starting with `TABLE, Region $name ...`

It looks like this only works for the first section but in the other sections the output is `TABLE, Region nil ...` 

Using e.g.:
`likwid-mpirun -np 2 -g MEM -O -m likwid-bench -t store -w S0:50MB`

produces:

```
...
TABLE,Region bench,Group 1 Raw,MEM,20,,,
Event,Counter,m1041:0:0,m1041:1:1,,,,
...
TABLE,Region nil,Group 1 Raw STAT,MEM,20,,,
Event,Counter,Sum,Min,Max,Avg,,
```

**Comment by TomTheBear** [comment]
Thanks for reporting
