### ISSUE TITLE
Large errors measuring AVX512 DP MFLOP/s on SLES12 SP3 with perf backend

### ISSUE THREAD

**Issue by ohlmann** [RRZE-HPC/likwid#224]
We had a discussion on this issue via email, but I wanted to bring this up in an issue because other users might be affected as well.

When I use `likwid-perfctr -C 1 -g FLOPS_DP -m likwid-bench -t ddot_avx512 -w S0:100kB:1`, then there is a discrepancy between the value measured by the hardware counters and the value given by likwid-bench. The ratio is about 2.8. Doing the same for the avx or sse benchmarks works fine, with only a smaller difference of ~7-8%.

Using perf directly seems to work. I think the result of the discussion was that it's unclear what's causing this difference, but that it's probably related to differences in the software stack/kernel of the different distributions.

**Comment by TomTheBear** [comment]
I havn't forget the issue and am still investigating. About two weeks ago, there was a post on the mailing list [Missing AVX512 Events on SkylakeX in Multithreaded Run](https://groups.google.com/forum/#!topic/likwid-users/VlllTO0qv-c) and I already thought that this could be a reason for your issue as well but I didn't find the time to log into your system to test it.

So, you could give it a try
`sudo wrmsr 0x10f 0x1`
before running LIKWID.

I prepared already a patch that throws a warning if PMC3 is selected, RTM is active (`grep -i rtm /proc/cpuinfo` )and TSX_FORCE_ABORT register is zero (`sudo rdmsr 0x10f`). With the above write, you set TSX_FORCE_ABORT to 1.

**Comment by TomTheBear** [comment]
Were you able to test it? If you do not have sufficient permission, you can also try to use only the 512B event with all counters (see post at mailing list) to see whether you are affected by the hardware bug.

**Comment by ohlmann** [comment]
Thanks for getting back to this. I can confirm that we are affected by the same issue.

I don't have sufficient permission, so I have only tested using different registers: if I count the AVX events on PMC3 and AVX512 on PMC2, the AVX512 values are correct and the AVX values are wrong. This seems to confirm that PMC3 returns "unexpected values".

Can you judge the potential performance implications of disabling TSX?

**Comment by TomTheBear** [comment]
I asked around in my working group and they don't even know a HPC-relevant application that uses TSX. We did some benchmarking (some time ago) with the result that atomics were always faster than TSX. This might have changed since that time. TSX is an additional feature, so if you disable it, there are no performance limitations for most codes. But you cannot run code using TSX/RTM instructions anymore.

**Comment by TomTheBear** [comment]
Just as remark. The Linux kernel has a workaround in perf starting with kernel version 5.2. It disables PMC3 when RTM is active and TSX_FORCE_ABORT register is zero. The kernel also provides a sysfs file to toggle the TSX_FORCE_ABORT register.

**Comment by ohlmann** [comment]
Thanks for the information, I also noticed that. What's your plan in likwid on how to handle this?

**Comment by TomTheBear** [comment]
LIKWID has the same behavior. It disables PMC3 if RTM is active and TSX_FORCE_ABORT register is zero. Furthermore, it prints a warning and the workaround (`sudo wrmsr 0x10f 0x1`). I want to add a switch, so that it prints the sysfs file with Linux >= 5.2 and the `wrmsr` command for lower versions.

**Comment by TomTheBear** [comment]
I added now the switch for Linux >= 5.2: https://github.com/RRZE-HPC/likwid/commit/0f62a40f250d658e5afd93658f703ecd365e9fdf

**Comment by TomTheBear** [comment]
Can we close this issue or do you have remaining questions?

**Comment by ohlmann** [comment]
No, thanks for addressing the issue.
