### ISSUE TITLE
Compile problem on 32 bit

### ISSUE THREAD

**Issue by npelov** [RRZE-HPC/likwid#225]
I get this error while trying to build on i686 machine:
./src/topology_proc.c: In function ‘proc_init_cpuFeatures’:
./src/topology_proc.c:282: error: ‘else’ without a previous ‘if’
make: *** [GCC/topology_proc.o] Error 1

When looking at the code I can see why it won't work - on 32 bit os the condition part is removed, but the if body remains:

#ifdef __x86_64
        if (ret != 1 || strcmp(ident,"flags") != 0 || strcmp(ident, "Features") != 0)
#endif
        {
            continue;
        }
        else
        {
            ret = 1;
            break;
        }

**Comment by TomTheBear** [comment]
Thanks for reporting. This should be fixed in https://github.com/RRZE-HPC/likwid/commit/4b9ec7d5a6fb8908458c8553aed1a3f5f901f310 (referenced wrong issue in comment)
