### ISSUE TITLE
Unable to build static binaries

### ISSUE THREAD

**Issue by mmoelle1** [RRZE-HPC/likwid#227]
I am trying to build likwid (latest checkout of the master branch) in static mode since I would like to provide precompiled binaries of likwid-pin and likwid-mpirun together with our research code G+Smo. The only changes made to `config.mk` are as follows:

```
BUILDDAEMON = false#NO SPACE
BUILDFREQ = false#NO SPACE
SHARED_LIBRARY = false#NO SPACE
```

The compilation process works fine until it comes to the linking stage:

```
===>  LINKING  likwid-bench
<PATH_TO_LIKWID_SOURCE>/likwid/ext/lua/liblikwid-lua.a(loadlib.o): In function `lookforfunc':
loadlib.c:(.text+0x4c4): undefined reference to `dlsym'
loadlib.c:(.text+0x511): undefined reference to `dlerror'
loadlib.c:(.text+0x546): undefined reference to `dlopen'
loadlib.c:(.text+0x5bf): undefined reference to `dlerror'
<PATH_TO_LIKWID_SOURCE>/likwid/ext/lua/liblikwid-lua.a(loadlib.o): In function `gctm':
loadlib.c:(.text+0x771): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make[1]: *** [likwid-bench] Error 1
make: *** [bench/likwid-bench] Error 2
```

Are static builds supported officially. If so, is the above error known and maybe fixed in some branch?

Many thanks in advanced.

**Comment by TomTheBear** [comment]
Hi,
you can build LIKWID as static library but it has downsides. I wasn't able to build LIKWID, basically Lua, as static so I can use the Lua scripts with a C module in `require`. But when I have time, I will look at it again.

The error when building likwid-bench was fixed in the above commit.

**Comment by mmoelle1** [comment]
Hi,

Thanks for the fix. Likwid-bench now compiles and runs fine. However, other commands that make use of likwid-lua don’t work, e.g.

./likwid-pin
<PATH_TO_LIKWID>/likwid-lua: ...<PATH_TO_LIKWID>/share/lua/likwid.lua:33: module 'liblikwid' not found:
no field package.preload['liblikwid']
no file ‘<PATH_TO_LIKWID>/share/lua/liblikwid.lua'
no file '/usr/local/share/lua/5.3/liblikwid.lua'
no file '/usr/local/share/lua/5.3/liblikwid/init.lua'
no file '/usr/local/lib/lua/5.3/liblikwid.lua'
no file '/usr/local/lib/lua/5.3/liblikwid/init.lua'
no file './liblikwid.lua'
no file './liblikwid/init.lua'
no file '<PATH_TO_LIKWID>/lib/liblikwid.so'
no file '/usr/local/lib/lua/5.3/liblikwid.so'
no file '/usr/local/lib/lua/5.3/loadall.so'
no file './liblikwid.so'
stack traceback:
[C]: in function 'require'
...<PATH_TO_LIKWID>/share/lua/likwid.lua:33: in main chunk
[C]: in function 'require'
./likwid-pin:33: in main chunk
[C]: in ?

It this what you mean by

I wasn't able to build LIKWID, basically Lua, as static so I can use the Lua scripts with a C module in require. But when I have time, I will look at it again.

**Comment by TomTheBear** [comment]
Yes, exactly. The problem is probably that Lua should load some C-module at runtime. For that, it requires dlopen and shared libraries but when everything is static this breaks. 
A solution might be to integrate the static LIKWID lib directly into the Lua interpreter but this would require a change in the build system as Lua is currently build before the LIKWID library.
