### ISSUE TITLE
likwid-perfctr -e should separate events and counters clearly

### ISSUE THREAD

**Issue by Shurakai** [RRZE-HPC/likwid#23]
At first, I didn't even notice that both are being output. (I only read that on the wikipage and then checked on my system.)

So, I just think that having no blank lines above/below the descriptions, such as

> This architecture has 97 counters.
> Counter tags(name, type<, options>)

has the effect of "hiding" these lines within the flood of events/counters.

In my case, some of the output looks like this:

> [lots of lines here]
> PBOX3, Physical Layer box, EDGEDETECT|THRESHOLD|INVERT
> This architecture has 695 events.
> Event tags (tag, id, umask, counters<, options>):
> TEMP_CORE, 0x0, 0x0, TMP0
> [lots of lines here]

Here, the first line is still a counter, then two lines of description and then the events are listed. It is almost impossible to see lines 3 and 4 if one doesn't know they are there.

**Comment by TomTheBear** [comment]
There are now 2 empty lines between the counter and the event lists. I close this issue.
