### ISSUE TITLE
likwid-powermeter -i  error

### ISSUE THREAD

**Issue by rohosalndn** [RRZE-HPC/likwid#232]
Hello, 

I am trying to test your toolsuite. I tried `likwid-powermeter` and I get the following error. Do you have any idea how to fix it? 

```
robert@robert-VirtualBox:~/likwid$ likwid-powermeter -i
Cannot gather values from MSR_PLATFORM_INFO
Cannot gather values from unit register 0x606, deactivating RAPL support
The Intel Skylake processor does not support reading power data or access is locked
```
I run it on Ubuntu VM installed on a Windows 10 machine. 

Thanks!

**Comment by rohosalndn** [comment]
OK, I managed to grand MSR access and got rid of the above error. But it doesn't show any readings:

> robert@robert-VirtualBox:~/likwid$ likwid-powermeter
> --------------------------------------------------------------------------------
> CPU name:	Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
> CPU type:	Intel Skylake processor
> CPU clock:	3.41 GHz
> --------------------------------------------------------------------------------
> --------------------------------------------------------------------------------
> Runtime: 2.00201 s
> Measure for socket 0 on CPU 0
> Domain PKG:
> Energy consumed: 0 Joules
> Power consumed: 0 Watt
> Domain PP0:
> Energy consumed: 0 Joules
> Power consumed: 0 Watt
> Domain PP1:
> Energy consumed: 0 Joules
> Power consumed: 0 Watt
> Domain DRAM:
> Energy consumed: 0 Joules
> Power consumed: 0 Watt
> Domain PLATFORM:
> Energy consumed: 0 Joules
> Power consumed: 0 Watt
> --------------------------------------------------------------------------------
> robert@robert-VirtualBox:~/likwid$ likwid-pin -p
> Domain N:
> 	0
> 
> Domain S0:
> 	0
> 
> Domain C0:
> 	0
> 
> Domain M0:
> 	0

No sure what else needs to be done. It should show some values but it returns 0.

**Comment by TomTheBear** [comment]
Please you base metal and no virtual machines to test LIKWID. In virtual machines it is pure gambling. For some combinations of VM-Host and VM-Guest it might work but as soon as Windows is the host, you are probably screwed. There is a reason why other hardware performance tools (https://github.com/opcm/pcm) ship with an extra Windows driver.

**Comment by rohosalndn** [comment]
Got it, thanks!
