### ISSUE TITLE
Adding flag to mpirun

### ISSUE THREAD

**Issue by modkin** [RRZE-HPC/likwid#235]
Hello,

is there any way to add a custom flag to mpirun (or mpiexec).
I specifically would need "--allow-run-as-root" since I am using likwid in a docker container as root and mpirun won't work otherwise.

Thanks,
Dominik

**Comment by TomTheBear** [comment]
I checked the source code of likwid-mpirun and you should be able to do it already. Try '--' on the commandline in front of your MPI options.

`likwid-mpirun -np 2 -- --allow-run-as-root ./a.out`

**Comment by nilskohl** [comment]
Hi,

I initiated this. Can confirm that your solution works if the dashes are placed after the executable:
`likwid-mpirun -np 2 ./a.out -- -allow-run-as-root`

Thanks for the hint
Nils

**Comment by TomTheBear** [comment]
Thanks for the confirmation but after the executable is not good because it is a mpi option and not a option for the executable. I'll check that.
