### ISSUE TITLE
Specify what the short name for the processor microarchitecture is

### ISSUE THREAD

**Issue by Shurakai** [RRZE-HPC/likwid#24]
The wiki states on page likwid-perfctr:

> in the directory $HOME/.likwid/groups/ARCH/, where ARCH is a short name for the processor 
> microarchitecture. You can get the short name by running `likwid-perfctr -i`.

I did run that command and my output looks like this:

### Output ###
--------------------------------------------------------------------------------
CPU name:       Intel(R) Xeon(R) CPU E5-2630 0 @ 2.30GHz
CPU type:       Intel Xeon SandyBridge EN/EP processor
CPU clock:      2.30 GHz
CPU family:     6
CPU model:      45
CPU stepping:   7
CPU features:   ACPI MMX SSE SSE2 HTT TM RDTSCP MONITOR VMX EIST TM2 SSSE3 SSE4.1 SSE4.2 AES AVX SSE3
--------------------------------------------------------------------------------
PERFMON version:        3
PERFMON number of counters:     8
PERFMON width of counters:      48
PERFMON number of fixed counters:       3
--------------------------------------------------------------------------------
Supported Intel processors:
        Intel Core 2 65nm processor
        Intel Core 2 45nm processor
        Intel Xeon MP processor
        Intel Atom 45nm processor
        Intel Atom 32nm processor
        Intel Atom 22nm processor
        Intel Core Bloomfield processor
        Intel Core Lynnfield processor
        Intel Core Westmere processor
        Intel Nehalem EX processor
        Intel Westmere EX processor
        Intel Core SandyBridge processor
        Intel Xeon SandyBridge EN/EP processor
        Intel Core IvyBridge processor
        Intel Xeon IvyBridge EN/EP/EX processor
        Intel Core Haswell processor
        Intel Xeon Haswell EN/EP/EX processor
        Intel Atom (Silvermont) processor
        Intel Atom (Airmont) processor
        Intel Xeon Phi Coprocessor
        Intel Core Broadwell processor

Supported AMD processors:
        AMD Opteron single core 130nm processor
        AMD Opteron Dual Core Rev E 90nm processor
        AMD Opteron Dual Core Rev F 90nm processor
        AMD Barcelona processor
        AMD Shanghai processor
        AMD Istanbul processor
        AMD Magny Cours processor
        AMD Interlagos processor
        AMD Family 16 model - Kabini processor

### Output End ###

I have, admittedly, as a novice user no idea what I should use for "ARCH" and this should be clarified (also in the documentation); for me, architecture is something like "x86_64" but that does not seem reasonable here (it does not even appear in the output of said command).

**Comment by TomTheBear** [comment]
Hi,

The output of the short name is currently only available in the master branch. I added this in commit https://github.com/RRZE-HPC/likwid/commit/1fdb30ff605a528fb24a233fb2feca7b50f7a1e9 a few days ago and directly updated the documentation. When I don't do it directly, I forget it...

As an alternative you can look at the perfgroups folder after installation:
```
$ ls /usr/local/share/likwid/perfgroups/
atom       broadwellD   core2    haswellEP   ivybridge    k10  kabini   nehalemEX  phi          sandybridgeEP  skylake   westmereEX
broadwell  broadwellEP  haswell  interlagos  ivybridgeEP  k8   nehalem  pentiumm   sandybridge  silvermont     westmere
```

I'm currently in the test phase for a new release, then the documentation is up-to-date again.

**Comment by TomTheBear** [comment]
The short name used by LIKWID is printed when calling `likwid-perfctr -i` in the 4.1.0 release. I close this issue now.
