### ISSUE TITLE
AVX Formula

### ISSUE THREAD

**Issue by flori-uni** [RRZE-HPC/likwid#258]
A short question: Shouldn't it be 

` Packed DP [MFLOP/s] = 1.0E-06*(FP_ARITH_INST_RETIRED_256B_PACKED_DOUBLE*4+FP_ARITH_INST_RETIRED_512B_PACKED_DOUBLE*8)/runtime `  in the `FLOPS_AVX.txt` file?

https://github.com/RRZE-HPC/likwid/blob/d4deec4ca7769a8fbea4a71bcf2cdad9e5b644a2/groups/CLX/FLOPS_AVX.txt#L23

**Comment by TomTheBear** [comment]
True, it's a typo in the documentation part, the actual formula used for calculation is ok.
