### ISSUE TITLE
likwid-mpirun with -g MEM not working

### ISSUE THREAD

**Issue by MatReiKIT** [RRZE-HPC/likwid#260]
Hi there.

i tried to measure memory bandwith with likwid-mpirun but got an error.

i used this command to debug:
`likwid-mpirun -np 2 -g MEM ./mpi_hello`

but get this error message instead of results:

------------------

> WARN: Cannot extract OpenMP vendor from executable or commandline, assuming no OpenMP
> Argument -o to option -g starts with invalid character -.
> Did you forget an argument to an option?
> 
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code.. Per user-direction, the job has been aborted.
> 
> Argument -o to option -g starts with invalid character -.
> Did you forget an argument to an option?
> 
> mpirun detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> 
>   Process name: [[28564,1],0]
>   Exit code:    1

------------------
If i add the debug flag there is one interesting point:

> DEBUG: Host localhost with 2 slots (max. 64 slots)
> DEBUG: Process 0 measures with event set: 
> DEBUG: Process 1 measures with event set: 
> EXEC (Rank 0): /usr/local/bin/likwid-perfctr -f  -C 0 -g  -o /home2/reichardt/.output_63693_%r_%h.csv ./mpi_hello /usr/local/bin/likwid-mpirun /usr/local/bin/likwid-lua
> EXEC (Rank 1): /usr/local/bin/likwid-perfctr -f  -C 1 -g  -o /home2/reichardt/.output_63693_%r_%h.csv ./mpi_hello /usr/local/bin/likwid-mpirun /usr/local/bin/likwid-lua
> 

as you see, there is the eventset missing.

digging further in the code i could point the problem to the **for** loop (line 1054) in the **splitUncoreEvents** function where the options for the memory measure get lost.

if i change line 1056 from ... match("^PMC%d") to match("PMC%d") the program will get results (don't know if it breaks other things).
the detected event sets are:
> DEBUG: Process 0 measures with event set: UNC_DRAM_ACCESSES_DCT0_ALL:UPMC0,UNC_DRAM_ACCESSES_DCT1_ALL:UPMC1
> D

CPU: AMD Opteron(tm) Processor 6376  (don't know if important)

p.s. thanks for this great tool ;)

**Comment by TomTheBear** [comment]
Hi, thanks for reporting.

Your workaround breaks other things, yes. The match `^PMC%d` is correct because it should split the core counters (`PMCx`) from the uncore counters (`UPMCx`). The problem is when combining the event lists. Core 0 should get core+uncore and core 1 just core events.
The bug is in this if-condition (https://github.com/RRZE-HPC/likwid/blob/master/src/applications/likwid-mpirun.lua#L1061), it does not match `^UPMC%d` to put the event into the socket list.

**Comment by MatReiKIT** [comment]
Thank you for the patch.
Unfortunately something seams still wrong.

> DEBUG: Process 0 measures with event set: ,UNC_DRAM_ACCESSES_DCT0_ALL:UPMC0,UNC_DRAM_ACCESSES_DCT1_ALL:UPMC1
> DEBUG: Process 1 measures with event set: 
> EXEC (Rank 0): /usr/local/bin/likwid-perfctr -f  -C 0 -g ,UNC_DRAM_ACCESSES_DCT0_ALL:UPMC0,UNC_DRAM_ACCESSES_DCT1_ALL:UPMC1 -o /home2/reichardt/.output_36309_%r_%h.csv ./mpi_hello
> EXEC (Rank 1): /usr/local/bin/likwid-perfctr -f  -C 1 -g  -o /home2/reichardt/.output_36309_%r_%h.csv ./mpi_hello

i tested this case on an AMD Epyc a few minutes ago, there it's working fine. Only this old Opteron stuff is making trouble.

**Comment by TomTheBear** [comment]
The problem is now the MEM group itself. It defines only uncore counters, so the second process gets an empty eventset.
The simplest way to fix this, is to add a core event to the group, like:
```
EVENTSET
PMC0  RETIRED_INSTRUCTIONS
UPMC0  UNC_DRAM_ACCESSES_DCT0_ALL
UPMC1  UNC_DRAM_ACCESSES_DCT1_ALL
```
I'll fix it in likwid-mpirun. It should switch to "just pinning" if the eventset is empty for a process.

**Comment by TomTheBear** [comment]
Can you please try the above patch? I tested it on Intel hardware because I don't have old AMD systems in my playground.

**Comment by MatReiKIT** [comment]
seems working.

> DEBUG: Host localhost with 2 slots (max. 64 slots)
> DEBUG: Process 0 measures with event set: UNC_DRAM_ACCESSES_DCT0_ALL:UPMC0,UNC_DRAM_ACCESSES_DCT1_ALL:UPMC1
> DEBUG: Process 1 measures with event set: No events
> EXEC (Rank 0): /usr/local/bin/likwid-perfctr -f  -C 0 -g UNC_DRAM_ACCESSES_DCT0_ALL:UPMC0,UNC_DRAM_ACCESSES_DCT1_ALL:UPMC1 -o /home2/reichardt/.output_44560_%r_%h.csv ./mpi_hello
> EXEC (Rank 1): /usr/local/bin/likwid-pin -q  -c 1 ./mpi_hello

Thanks

**Comment by TomTheBear** [comment]
Thanks for testing. I have do some follow-ups (empty table columns in output) but your issue is fixed.
