### ISSUE TITLE
Counter PMC0 is only available with deactivated HyperThreading

### ISSUE THREAD

**Issue by flori-uni** [RRZE-HPC/likwid#261]
I'm trying to use this awesome project for some research during my bachelor thesis. Sadly I'm continuously getting the error "Counter PMC0 is only available with deactivated HyperThreading" (same for PMC1, PMC2, PMC3) and I've got no option to disable HyperThreading on my machine. So do I need to change the Events to PMC4, PMC5, PMC6, PMC7?

**Comment by flori-uni** [comment]
My mistake. Sorry.

**Comment by wq-peng** [comment]
> My mistake. Sorry.

May I ask how you solve this problem? Thanks.

**Comment by TomTheBear** [comment]
I also don't know but my guess is that performance monitoring was disabled completely. Some BIOS provide options for that.
