### ISSUE TITLE
Suppress Marker API warning

### ISSUE THREAD

**Issue by modkin** [RRZE-HPC/likwid#264]
When running an application that has likwid markers inside the following warning is generated even when executing without likwid at all:

`Running without Marker API. Activate Marker API with -m on commandline.`
https://github.com/RRZE-HPC/likwid/blob/031ee03e39e957c9a9684aeb11d5716e82818acd/src/libperfctr.c#L169

Is there any way to suppress this warning or would it be possible to only warn if e.g. likwid-perfctr is actually used?

**Comment by TomTheBear** [comment]
The output FD is `stderr`, so yes, you could discard all `stderr` output but that's probably not what you want.
It would be possible to check for `likwid-perfctr` but how far up should we check it? Just direct parent (`likwid-perfctr ... ./app`) or further up (`likwid-perfctr ... wrapper ./app`)?

**Comment by modkin** [comment]
I see the problem with the check and don't really know a solution.
The best way is probably to just re-compile without the markers then.

Thanks for the answer!
