### ISSUE TITLE
Power9 - metrics only for core 0

### ISSUE THREAD

**Issue by rdietric** [RRZE-HPC/likwid#267]
On Power9, metrics are only shown for core 0, independent of the number of threads the program uses. With x86 everything works as expected.

Reproduce with:
OMP_NUM_THREADS=2
likwid-perfctr -g FLOPS ./omp_prog

**Comment by TomTheBear** [comment]
Have you checked whether your cpuset contains more than core 0? I just checked on a Power9 system (ata TUD) and it works fine. You can check that with likwid-topology (`*` in last column).

**Comment by rdietric** [comment]
I checked the master branch today and the issue seems to be fixed now. 

The issue might have also been related to SLURM exclusive jobs, which do not allocate all resources of a node (only core 0).

Thanks for your support! The issue can be closed.
