### ISSUE TITLE
lkwid-bench CUDA support

### ISSUE THREAD

**Issue by melven** [RRZE-HPC/likwid#268]
How difficult is it to add CUDA support to likwid-bench? I noticed that there are already micro-benchmarks for various different architectures...

**Comment by TomTheBear** [comment]
It depends what you want to benchmark. You probably need a different format as the current ptt files. 
- lowest level copy: `B[idx] = A[idx];` where `idx = threadIdx.x + blockIdx.x * blockDim.x` s automatically defined
- kernel level copy:
```
__global__ void _copy_kernel(int num_elems, float *B, const float *__restrict__ const A) {
  const int i = threadIdx.x + blockIdx.x * blockDim.x;
  if (i < num_elems) { buffer_b[i] = buffer_a[i]; }
}
void stream_copy(int size, dim3 thread_blocks, dim3 threads_per_block, float *A, float *B) {
  copy<<<thread_blocks,threads_per_block>>>(size, B, A);
}
```
- even higher level copy: ...

To generate the benchmarks at compile time, you need something like `bench/perl/genAsm.pl`. For the generation at runtime, you have write something similar in C like `bench/src/ptt2asm.c`. Threads are not needed but it would be beneficial to use an extra pthread for each GPU for allow (future) hybrid runs.

Moreover, you need a CUDA version of the stream allocator and you have to think about the cmdline options (e.g. -w G0:size:threadIdx.x:blockIdx.x:blockDim.x:...).
