### ISSUE TITLE
Accessing AMD Zen L3PMCs using the Marker API

### ISSUE THREAD

**Issue by justinborromeo** [RRZE-HPC/likwid#271]
I was looking through the Marker API documentation and found the following [eventset groups](https://github.com/RRZE-HPC/likwid/tree/master/groups/zen) for AMD's Zen architecture.  Is there a set of similar groups for accessing the architecture's L3 cache PMCs (i.e. the counters mentioned [here](https://github.com/RRZE-HPC/likwid/blob/0b9194d90cdc3171e0799da40d4c58a77f0dc33e/src/includes/perfmon_zen_counters.h#L77)) or is there another API for accessing these?

**Comment by TomTheBear** [comment]
Hi. All counters/events are available in MarkerAPI mode. There is simply no predefined group for the L3 counters for AMD Zen but you can also specify raw event sets on the command line:
`likwid-perfctr -C 0 -g L3_ACCESS:CPMC0,L3_MISS:CPMC1 -m <app_with_marker>`

If you want, you can create your own performance group for your eventset: https://github.com/RRZE-HPC/likwid/wiki/likwid-perfctr#defining-custom-performance-groups . Just put the file in `$HOME/.likwid/groups/zen` and you can use it like all other groups.

Be aware that the L3 segments are shared by multiple cores and only one core in each segment will read the counters.
