### ISSUE TITLE
Wiki Editing

### ISSUE THREAD

**Issue by bkmgit** [RRZE-HPC/likwid#273]
Would be helpful if contributions to the wiki could also be made. This might help with #201. Could this be enabled for this repository, see https://help.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis - alternatively, rather than use a wiki, perhaps markdown formatting could be used and the content put in the main git repository to allow for contributions through pull requests.

**Comment by TomTheBear** [comment]
I have generally no problem with opening up the wiki but I have some concerns about the management of user contributions. Currently, I don't get notified if someone edits in the wiki. Does that change if you open it up (no, I asked)? For code submissions, I can moderate in PRs but for the wiki there is no such process yet. Your proposed markdown method would work but, with me in the user perspective, this does not seem like a standard way to contribute. I havn't seen such a system at other repositories yet.

In general, do you have a contribution you would like to add to the wiki?

We will discuss that in the group. Thanks for the suggestion.

**Comment by bkmgit** [comment]
Static site generators work ok, see for example:
https://github.com/go-gitea/gitea/tree/master/docs
Some projects allow anyone to edit the wiki, for example:
https://github.com/gosu/gosu/wiki

Initially, just fixing a typo on https://github.com/RRZE-HPC/likwid/wiki/Likwid-Bench
perl skript -> perl script

**Comment by TomTheBear** [comment]
Thanks for the links. 

Typo fix done.

**Comment by TomTheBear** [comment]
I asked the other group members and the overall opinion is to not open the wiki or use a static site generator. If anyone contacts us with the wish to contribute, we would probably add him/her to the repository. The personal contact makes it much easier to give advise and support for the contribution.

**Comment by bkmgit** [comment]
Ok. Thanks for your reply.

**Comment by TomTheBear** [comment]
Do you want to get an invite to the repo?

**Comment by bkmgit** [comment]
Yes, invite is nice.

Can also look at creating static site generator. This has a few advantages over the wiki:
* Changes can be made by pull requests
* If one clones or forks the repository, documentation in the wiki also follows. 
An introduction is available at:
https://github.blog/2016-08-22-publish-your-project-documentation-with-github-pages/

However, can modify wiki.

**Comment by TomTheBear** [comment]
You should have an invite.
