### ISSUE TITLE
[Question] Clarification about Likwid-bench and memory placement options

### ISSUE THREAD

**Issue by pramodk** [RRZE-HPC/likwid#276]
Hello there,

I am trying to understand an example from [Usage section ](https://github.com/RRZE-HPC/likwid/wiki/Likwid-Bench#usage):

```
$ likwid-bench  -t copy -w S1:1GB:2-0:S0,1:S0  -w S0:1GB:2
```

And explanation says:

```
This example runs the copy kernel on two threads per socket but overrides the default
setting with placing all vectors in the socket 0 domain. Note that you either specify no
stream arguments or all stream arguments. This means that if your kernel operates on two
streams you have to specify two streams in the optional memory arguments. The syntax is 
<domain>:<size>:[<threads>](<threads>])-::,:.... You can offset the array by a multiple of type, 
i.e., if the kernel operates on doubles you can offset the array by a multiple of sizeof(double)`. 
Notice that this offset is also checked against the stride of the loop. 
```

I understand `S1:1GB:2` and `S0:1GB:2` indicating socket number, memory size and threads. But I didn't understand `-0:S0,1:S0` part in first argument and how it placed the memory in `S0` instead of `S1`.

Could you please elaborate a bit?

**Comment by pramodk** [comment]
After bit of experimenting, my interpretation is:

```
-0:S0,1:S0
```
 means:
* run 0th thread on S0 for memory allocation
* run 1st thread on S0 for memory allocation

So `-` is used to separate execute and memory allocation?

**Comment by TomTheBear** [comment]
Hi,

It's not the thread 0 or 1 but stream/allocation 0 and 1. The copy benchmark requires an input and an output array.

The placement of threads/streams is determined by the first part S0/S1, the second parameter is the size and the third part the number of threads in the domain (first parameter). If you want to place the streams not in the given domain, you can specify a different location in the and.

So `S0:1GB:4-0:S1,1:S1` places 4 threads in the domain S0 (socket 0).  Allocates in total 1GB but places both arrays in S1, which basically tests the read and write socket interconnect bandwidth.

The offset is rarely used but you can use it to shift the start of the array to e.g. use unaligned accesses.

**Comment by pramodk** [comment]
Understood! Thanks @TomTheBear for detailed explanation!
