### ISSUE TITLE
likwid-perfctr does not support ARMv8?

### ISSUE THREAD

**Issue by huangshiyou** [RRZE-HPC/likwid#277]
I successfully built the tool on the armV8 architecture. But it fails to run. Here is what it shows:
likwid-perfctr -a
No groups defined for nil

likwid-perfctr -g BRANCH ls
--------------------------------------------------------------------------------
CPU name:
CPU type:	nil
CPU clock:	0.00 GHz
ERROR - [./src/perfmon.c:perfmon_addEventSet:1976] No such file or directory.
Cannot read performance group BRANCH

**Comment by TomTheBear** [comment]
The detection on ARMv8 is currently limited. I just had access to three different ARMv8 platforms. 

The definitions are in https://github.com/RRZE-HPC/likwid/blob/master/src/includes/topology.h#L136-L164 . The detection function reads `/proc/cpuinfo` and uses the fields:

* `CPU architecture`
* `CPU variant`
* `CPU revision`
* `CPU part`
* `CPU implementer`

If you can send me `/proc/cpuinfo` of your system, it's quite easy to add. If you want to try to add it yourself, I can point you to the relevant files.

**Comment by huangshiyou** [comment]
Thanks for your reply. Here it is:
cat /proc/cpuinfo
processor	: 0
BogoMIPS	: 243.75
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x3
CPU part	: 0xd0c
CPU revision	: 1

BTW, does the support changing the size of LLC?

**Comment by TomTheBear** [comment]
Can you give me additionally the information what kind of chip this is? I was unable to find any info for the ID 0xd0c. Anything like Cortex Ax or My?

What do you mean with changing the size of LLC? Until now, I havn't found an interface on ARM platforms to read cache information. Setting cache sizes is commonly not allowed. Or do you mean cache partitioning (like Intel CAT)?

**Comment by TomTheBear** [comment]
I found the chip. I added the support as pull request: https://github.com/RRZE-HPC/likwid/pull/278

It would be great if you could try it out because I don't have access to such a machine. If the perf_event device was renamed, it won't work. In this case, please send me the file listing of `/sys/bus/event_source/devices/`.

**Comment by huangshiyou** [comment]
Thanks for that! I am glad you found it. I forgot to reply to you yesterday. I will try it today and let you know if it works. It'll be great if you can show me where to add the support for other chips because I have some other ARM chips.

**Comment by TomTheBear** [comment]
Since this "How to add new chips" tutorial was requested already quite often, I created a wiki page: https://github.com/RRZE-HPC/likwid/wiki/AddARMSupport

If you add a new chip and encounter problems, please let me know. I might have missed something.

**Comment by TomTheBear** [comment]
I got some info about the Neoverse N1. The pull request should contain everything to run on the machines already.
Did you have time to test it? I still don't have access to such a machine.

**Comment by huangshiyou** [comment]
Will do

**Comment by TomTheBear** [comment]
Fixed in 5.1.0
