### ISSUE TITLE
Strange (error?) results for likwid-topology in examples.

### ISSUE THREAD

**Issue by masterspline** [RRZE-HPC/likwid#28]
On page https://code.google.com/p/likwid/wiki/LikwidTopology#Intel_Dunnington
> Intel Dunnington
> -------------------------------------------------------------
> CPU name:       Intel Xeon MP processor
System have 4 sockets and 6 cores per socket
> Sockets:                4 
> Cores per socket:       6
But for Level 3 cache shown 3 groups (not 4) of cores with 8 cores per group (not 6).
> Cache groups:   ( 0 12 1 13 2 14 3 15 ) ( 4 16 5 17 6 18 7 19 ) ( 8 20 9 21 10 22 11 23 )

This result looks like error.

**Comment by TomTheBear** [comment]
Hi,

thanks for the hint but anything in the Google Code repository and wiki is outdated. The topology examples were made with LIKWID 3 which uses an interface to CPUID. This interface was ok but left room for some bugs. In LIKWID 4 the hwloc library is used. I included some examples for LIKWID 4 in the likwid-topology wiki page https://github.com/RRZE-HPC/likwid/wiki/likwid-topology . There is no example output for the Intel Dunnington, we don't run the system anymore.

Greetings,
Thomas
