### ISSUE TITLE
Missing perf events in sky lake

### ISSUE THREAD

**Issue by huangshiyou** [RRZE-HPC/likwid#280]
Here is the error msg:
ERROR - [./src/includes/perfmon_skylake.h:perfmon_init_skylake:72] No such file or directory.
Cannot zero 0x3F1 (0x3F1)
ERROR - [./src/includes/perfmon_skylake.h:perfmon_init_skylake:77] No such file or directory.
Cannot zero 0x3F7 (0x3F7)

CPU info:
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
stepping	: 4
microcode	: 0x2000069
cpu MHz		: 3174.420
cache size	: 33792 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes

**Comment by huangshiyou** [comment]
This might not be the software's problem. I guess this is more like to be a hardware issue.

**Comment by TomTheBear** [comment]
There is something wrong with your installation. If you use `ACCESSMODE=perf_event` the function `perfmon_init_skylake()` is never called. Instead it calls `perfmon_init_perfevent()`.

Please do `make distclean && make && (sudo) make install` everytime you change an option in `config.mk`. If you have multiple installations of LIKWID on your system, make sure that the `LD_LIBRARY_PATH` points to the right library.

**Comment by TomTheBear** [comment]
Were you able to resolve the issue on your side?

**Comment by huangshiyou** [comment]
My bad. I am busy with some other things these days so that I forgot about
this. I will do a quick test today. Thanks.

**Comment by huangshiyou** [comment]
I guess its the hardware's problem:
--------------------------------------------------------------------------------
CPU name:	Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
CPU type:	Intel Cascadelake SP processor
CPU clock:	2.50 GHz
ERROR: No event in given event string can be configured.
       Either the events or counters do not exist for the
       current architecture. If event options are set, they might
       be invalid.

When I do perf list:
List of pre-defined events (to be used in -e):

  alignment-faults                                   [Software event]
  bpf-output                                         [Software event]
  context-switches OR cs                             [Software event]
  cpu-clock                                          [Software event]
  cpu-migrations OR migrations                       [Software event]
  dummy                                              [Software event]
  emulation-faults                                   [Software event]
  major-faults                                       [Software event]
  minor-faults                                       [Software event]
  page-faults OR faults                              [Software event]
  task-clock                                         [Software event]

  msr/aperf/                                         [Kernel PMU event]
  msr/mperf/                                         [Kernel PMU event]
  msr/smi/                                           [Kernel PMU event]
  msr/tsc/                                           [Kernel PMU event]

  rNNN                                               [Raw hardware event descriptor]
  cpu/t1=v1[,t2=v2,t3 ...]/modifier                  [Raw hardware event descriptor]
   (see 'man perf-list' on how to encode it)

  mem:<addr>[/len][:access]                          [Hardware breakpoint]

**Comment by huangshiyou** [comment]
By the way, this is an AWS EC2 m5 machine.

**Comment by TomTheBear** [comment]
Yes, the hardware seems limited. They probably patch out the hardware event support in their Cloud OS.

**Comment by pramodk** [comment]
> Yes, the hardware seems limited. They probably patch out the hardware event support in their Cloud OS.

That’s also my experience on EC2 even on dedicated hosts. There are some web references from 2015-2016 saying this should be possible on dedicated host but I tested this two weeks ago and it’s not the case.

**Comment by TomTheBear** [comment]
That's unfortunate. I planned to test the ARM Neoverse N1 support on their Graviton 2 systems when they are available.

**Comment by TomTheBear** [comment]
Can we close this issue or do you have further questions/issues?

**Comment by huangshiyou** [comment]
Yea
