### ISSUE TITLE
Automated code review for likwid

### ISSUE THREAD

**Issue by gingerDevilish** [RRZE-HPC/likwid#281]
Hi!

I am developing Monocodus, and we are integrating a variety of code checkers into CI.
The tool spawns checkers’ outputs right into pull requests interfaces, which could be useful for you: 
<img width="635" alt="image" src="https://user-images.githubusercontent.com/11041411/78507521-1bde4d80-7789-11ea-9d9e-b5c8cebee312.png">
<img width="633" alt="image" src="https://user-images.githubusercontent.com/11041411/78507553-44fede00-7789-11ea-8420-9f17d2c2c311.png">
https://github.com/monocodus-demonstrations/likwid/pull/1

I would really like to get some feedback on our service from you. Please take some time to try it out — it’s free, and I hope it’s going to be useful for you.

Thanks.

**Comment by TomTheBear** [comment]
Thanks for the review but I'm fine with the two functions. Shorting them is not required.

Just as feedback: It would be better to add some descriptive links if you come up with terms like 'cyclomatic complexity'. I also don't see this complexity, it's just some nested switch-case statements, nothing too complicated. The found issues should not be pictures but normal text for copy&paste. I'm not sure what the threshold for 'too long' is but there are three functions that have almost the same size (`topology_setName`, `perfmon_init_maps` and `perfmon_init_funcs`) but only one of them is mentioned in your review.
