### ISSUE TITLE
Error with likwid-setFrequencies : Cannot parse cpustring

### ISSUE THREAD

**Issue by pramodk** [RRZE-HPC/likwid#283]
After #282, I was trying`likwid-setFrequencies` and get following:

```
$ likwid-setFrequencies -l
WARN: Selected affinity domain N has only 2 hardware threads, but selection string evaluates to 72 threads.
     This results in multiple threads on the same hardware thread.
/home/kumbhar/perftools/install/bin/likwid-lua: Cannot parse cpustring
stack traceback:
	[C]: in function 'likwid.cpustr_to_cpulist'
	/home/kumbhar/perftools/install/bin/likwid-setFrequencies:221: in main chunk
	[C]: in ?
```

I will be happy to do further testing or provide additional information.

**Comment by TomTheBear** [comment]
This is the same issue as #282 in a different application . You are running in a cpuset with 2 hardware threads and `likwid-setFrequencies -l` want to resolve `N:0-<numThreads>` but this returns only your 2 hardware threads instead of the requested `<numThreads>`. This needs to be fixed.
