### ISSUE TITLE
Does not build with GCC 10

### ISSUE THREAD

**Issue by michaelkuhn** [RRZE-HPC/likwid#287]
GCC 10 defaults to `-fno-common`, which causes the build to fail with:
```
./GCC/pci_proc.o:(.bss+0x0): multiple definition of `sharedl3_lock'
./GCC/access_x86.o:(.bss+0x0): first defined here
./GCC/pci_proc.o:(.bss+0x4c0): multiple definition of `sharedl2_lock'
./GCC/access_x86.o:(.bss+0x4c0): first defined here
./GCC/pci_proc.o:(.bss+0x980): multiple definition of `numa_lock'
./GCC/access_x86.o:(.bss+0x980): first defined here
./GCC/pci_proc.o:(.bss+0xe40): multiple definition of `tile_lock'
./GCC/access_x86.o:(.bss+0xe40): first defined here
./GCC/pci_proc.o:(.bss+0x1300): multiple definition of `core_lock'
./GCC/access_x86.o:(.bss+0x1300): first defined here
...
```
Adding `-fcommon` to `CFLAGS` works around the problem.

**Comment by TomTheBear** [comment]
Have you tried a release version or the current master branch?

The current master contains this patch (https://github.com/RRZE-HPC/likwid/commit/11d80e26c19c9c5585965e299fb31ecbe09f3f15) which should fix the issue.

**Comment by michaelkuhn** [comment]
I tried building version 5.0.1. I also tried finding a commit with a fix but must have missed this one. Will this be included in a 5.0.2 release or only in 6.0.x (just asking so I can update my Spack PR at https://github.com/spack/spack/pull/16641)? Thanks!

**Comment by TomTheBear** [comment]
It's going to be in the next bugfix release, so 5.0.2. The next version with new features will be 5.1.0 (CPU voltage, ...). The jump from 4.3.4 to 5.0.0 was due to the many new features that were included (POWER and ARM support, Nvidia GPUs, ...).

**Comment by TomTheBear** [comment]
If the patch is suitable for you and spack, can you please close the issue. Of course, if you have further questions or notes for the issue, feel free to keep it open and post them here.

**Comment by michaelkuhn** [comment]
I have updated the Spack PR to only apply the `-fcommon` workaround until version 5.0.2. Thanks!
