### ISSUE TITLE
likwid-mpirun: cannot specify MPI type with -mpi

### ISSUE THREAD

**Issue by MarcelKoch** [RRZE-HPC/likwid#288]
I cannot define the mpi type with `-mpi` if the mpi type is different from the default one `mpirun` would choose. In my concrete case, I want to use openmpi, but likwid only accepts mpich, since this is the default one likwid guesses. Here is a patch, which solved the problem for me.
```
diff --git a/src/applications/likwid-mpirun.lua b/src/applications/likwid-mpirun.lua
index 509efe43..017dd0cc 100644
--- a/src/applications/likwid-mpirun.lua
+++ b/src/applications/likwid-mpirun.lua
@@ -818,8 +818,9 @@ local function getMpiExec(mpitype)
             end
         end
     end
-    local testmpitype = getMpiType()
-    if mpitype ~= testmpitype then
+    if mpiexecutable == nil then
+        local testmpitype = getMpiType()
         print_stderr(string.format("ERROR: Cannot find executable for MPI type %s but %s", mpitype, testmpitype))
         os.exit(1)
     end
```

**Comment by TomTheBear** [comment]
That's true, there have been problems with the `-mpi` switch. I'm working on `likwid-mpirun` and a similar fix is also in my changes. Thanks for reporting it with a patch.
