### ISSUE TITLE
Unsupported processor for AMD Ryzen 9 3900X

### ISSUE THREAD

**Issue by fmitch** [RRZE-HPC/likwid#289]
On installing Likwid 5.0.1 Release, I'm unable to run any binaries and running make in the examples folder gives the following:

```
$ gcc -fopenmp -DLIKWID_PERFMON -I/usr/local/include -L/usr/local/lib C-markerAPI.c -o C-markerAPI -llikwid -lm
$ /usr/local/bin/likwid-perfctr -C 0 -g INSTR_RETIRED_ANY:FIXC0 -m ./C-markerAPI
--------------------------------------------------------------------------------
CPU name:       AMD Ryzen 9 3900X 12-Core Processor
CPU type:       nil
CPU clock:      3.79 GHz
ERROR - [./src/perfmon.c:perfmon_init_maps:1174] Unsupported AMD Zen Processor
WARN: Counter FIXC0 not defined for current architecture
ERROR: No event in given event string can be configured.
       Either the events or counters do not exist for the
       current architecture. If event options are set, they might
       be invalid.
```
From looking at `src/perfmon.c`, it seems like the Zen2 arch should be supported. Is this an oversight? Is the Ryzen 9 3900X actually not supported?

**Comment by TomTheBear** [comment]
AMD Zen2 is supported. It looks like the model id for architecture detection is missing I don't have a desktop version of the Zen2 architecture. With the output of `grep -E "model|family|stepping" /proc/cpuinfo  | sort -u` we can add it to LIKWID. The only registered model id for Zen2 is `ZEN2_RYZEN = 0x31 = 49`.

**Comment by fmitch** [comment]
Here's the info:
```
grep -E "model|family|stepping" /proc/cpuinfo | sort -u
cpu family	: 23
model		: 113
model name	: AMD Ryzen 9 3900X 12-Core Processor
stepping	: 0
```

**Comment by TomTheBear** [comment]
https://github.com/RRZE-HPC/likwid/commit/5d33ebf1a2c0017b1a1ab630b5c839fe3948283f

I'll will be in the next release 5.0.2. Thanks for reporting and providing the required data.

If you want it now, download the patch [likwid-Zen2-add.txt](https://github.com/RRZE-HPC/likwid/files/4646548/likwid-Zen2-add.txt) and execute at the base directory:
```
cd likwid-5.0.1
patch -p 1 < likwid-Zen2-add.txt
make distclean
make
(sudo) make install
```

If you encounter problems, let me know. Otherwise we could close this issue.
