### ISSUE TITLE
likwid-topology segfault in affinity_finalize on Raspberry Pi 4 (ARMv8)

### ISSUE THREAD

**Issue by Tobi29** [RRZE-HPC/likwid#290]
# Problem

Using a checkout of 99b0d23927f5e65cfa4eb5aeac1c57504395694b (also happens with the 5.0.1 release) compiled for a Raspberry Pi 4 causes both likwid-topology and likwid-pin (as far as I can tell due to the same issue) to segfault after execution.

As far as I can tell this is probably a similar problem to #228.

# Debugging

Debugging the code reveals that there is an out of bounds write to the `domains` array in `affinity_init`, which corrupts `domains[0].tag` (`{mlen = 18, slen = 1, data = 0x55555b6f60 "N"}` -> `{mlen = 18, slen = 1, data = 0x55555b6f60 "@p[UU"}`) and one way or another causes the call to `free` done at the end to crash.

The debug output shows that it seems to think 2 domains will be created, but actually 3 end up being made:
```
DEBUG - [affinity_init:304] Affinity: Socket domains 1
DEBUG - [affinity_init:312] Affinity: NUMA domains 0
DEBUG - [affinity_init:315] Affinity: CPUs per socket 4
DEBUG - [affinity_init:340] Affinity: All domains 2
DEBUG - [affinity_init:353] Affinity domain N: 4 HW threads on 4 cores
DEBUG - [affinity_init:392] Affinity domain S0: 4 HW threads on 4 cores
DEBUG - [affinity_init:491] Affinity domain M0: 4 HW threads on 4 cores
```

Running `likwid-pin -p` shows this corrupted string:
```
Domain  �:�U:
        0,1,2,3

Domain S0:
        0,1,2,3

[1]    6056 segmentation fault (core dumped)  likwid-pin -p
```

# Details

 * likwid Version: 99b0d23927f5e65cfa4eb5aeac1c57504395694b
 * Linux Kernel: Linux tobias-pi 5.4.38-1-ARCH #1 SMP PREEMPT Wed May 6 11:05:57 MDT 2020 aarch64 GNU/Linux
 * CPU Model: Raspberry Pi 4 Model B Rev 1.1
 * [cpuinfo.txt](https://github.com/RRZE-HPC/likwid/files/4658128/cpuinfo.txt)
 * [gdb.txt](https://github.com/RRZE-HPC/likwid/files/4658093/gdb.txt)
 * [likwid-topology.txt](https://github.com/RRZE-HPC/likwid/files/4658096/likwid-topology.txt)
 * [lscpu.txt](https://github.com/RRZE-HPC/likwid/files/4658098/lscpu.txt)

**Comment by TomTheBear** [comment]
Hi, thanks for reporting and providing detailed information. The problem get visible here:

`Affinity: NUMA domains 0`

This value shouldn't be possible as all systems have at least one memory domain. UMA systems should have a value of 1, for NUMA systems the value should be `>= Socket domains`.
If you want to fix this, ensure that after the loop in https://github.com/RRZE-HPC/likwid/blob/master/src/affinity.c#L306-L312, the value is at least one.

Another problem in your outputs is that the CPU type detection does not work:
```
CPU name:       BCM2835
CPU type:       nil
```
If you want to fix this, follow the topology section (https://github.com/RRZE-HPC/likwid/wiki/AddARMSupport#add-hardware-topology-information). The ID `ARM_CORTEX_A72` is already there but the name and its assignment in `src/topology.c` is missing. The ID is already registered for performance monitoring.
