### ISSUE TITLE
Error measuring CLOCK/ENERGY performance group with C/C++-API

### ISSUE THREAD

**Issue by ntippman** [RRZE-HPC/likwid#293]
I use the C/C++-API to continuously measure values for different performance groups and output the results as csv.

Only when trying to measure the CLOCK or ENERGY group i receive the following error message:

`ERROR - [./src/includes/perfmon_skylake.h:perfmon_startCountersThread_skylake:985] No such file or directory.
Power register read operation failed`

and the next `perfmon_startCounters` fails.

All other available performance groups behave as expected and do not show this error.

This error was tested and occured on the following systems:

- Intel Core i5-6260U, Ubuntu 19.04, GCC 8.3.0
- 2x Intel Xeon Gold 6226 CPU, Centos7, GCC 8.3.0
- 2x Intel Xeon CPU E5-2667 v3, Centos7.4, GCC 8.3.0 (with `ERROR - [./src/includes/perfmon_haswell.h:perfmon_startCountersThread_haswell:1256] No such file or directory.`)

with LIKWID-Version 5.0.1 and `LIKWID_FORCE=1`.

I attached a small reproducer with a makefile ([reproducer.zip](https://github.com/RRZE-HPC/likwid/files/4999469/reproducer.zip)).
Execute with `./likwid <GROUP> <INTERVAL>`

**Comment by TomTheBear** [comment]
Thanks for reporting. Both groups `CLOCK` and `ENERGY` read one respectively multiple energy counters. You should see the same problems with `MEM_DP` and `MEM_SP`. If not, there is something strange going on.

Can you try on one of the hosts to run with `-V 1` or `perfmon_setVerbosity(1)` and check whether there is some line like `Counter PWRx does not exist` at `perfmon_init()` or `perfmon_addEventSet()`.

I hope I find some time this week to test your reproducer.

**Comment by ntippman** [comment]
You are right, the same problem occurs with `MEM_SP` and `MEM_DP`.

The output from `perfmon_setVerbosity(1)` indicates no problem with the `PWRx` Counters:

```
DEBUG - [perfmon_addEventSet:2120] Added event INSTR_RETIRED_ANY for counter FIXC0 to group 0
DEBUG - [perfmon_addEventSet:2120] Added event CPU_CLK_UNHALTED_CORE for counter FIXC1 to group 0
DEBUG - [perfmon_addEventSet:2120] Added event CPU_CLK_UNHALTED_REF for counter FIXC2 to group 0
DEBUG - [perfmon_addEventSet:2120] Added event PWR_PKG_ENERGY for counter PWR0 to group 0
DEBUG - [perfmon_addEventSet:2120] Added event PWR_DRAM_ENERGY for counter PWR3 to group 0
DEBUG - [perfmon_addEventSet:2120] Added event UNCORE_CLOCK for counter UBOXFIX to group 0
```
See the full [Output.txt](https://github.com/RRZE-HPC/likwid/files/4784686/reproducer_verbosity_1.txt)


The first iteration of measurements seems the work as intended, so the error only occurs on the second iteration.
