### ISSUE TITLE
attempt to call a nil value (field 'getGroups')

### ISSUE THREAD

**Issue by mjpt777** [RRZE-HPC/likwid#30]
I've pulled the latest version that builds successfully. When I run I get the following error.

```
$ sudo likwid-perfctr -a
/usr/local/bin/likwid-lua: /usr/local/bin/likwid-perfctr:363: attempt to call a nil value (field 'getGroups')
```

**Comment by TomTheBear** [comment]
Hi,
are you sure that the new library is in the lib path? Or did you try to run it after built from the local directory? The getGroups() function was introduced on the 11.02.2016.
Please do a `make uninstall` before installing the new version to swipe the old libs or make sure that the liblikwid.so softlink points to the newly installed library.

**Comment by mjpt777** [comment]
I had done a `make uninstall` first time. I tried again and it worked after a `make distclean`

Thanks.
