### ISSUE TITLE
likwid Unsupported Processor 

### ISSUE THREAD

**Issue by nournadar** [RRZE-HPC/likwid#300]
Hello,
I installed likwid on a skylake and I keep getting "Unsupported processor"

```
$ sudo likwid-perfctr -i
ERROR - [./src/perfmon.c:1216] Unsupported Processor
```

I can see that its a well known issue.. Is there a work around for it ?

**Comment by TomTheBear** [comment]
Can you please supply the output of `/proc/cpuinfo` for one "processor". LIKWID is probably missing the model ID to identify your chip. There is no good source for the various model IDs, so I can only add those I know.

**Comment by nournadar** [comment]
is this what you mean @TomTheBear 
```
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
stepping        : 4
microcode       : 0x2000064
cpu MHz         : 1000.000
cache size      : 28160 KB
physical id     : 0
siblings        : 40
core id         : 0
cpu cores       : 20
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx avx512f rdseed adx smap clflushopt clwb avx512cd xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku md_clear flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips        : 4800.01
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

```

**Comment by TomTheBear** [comment]
Yes thank you.

Which version are you using because Skylake SP chips (Model 85 = 0x55) is already supported for quite some time?
Commit (https://github.com/RRZE-HPC/likwid/commit/67bdfd7916bd298e2826269a36d0c9e88acad966 , 17 Jul 2017)

**Comment by nournadar** [comment]
```

$ likwid-bench -v
likwid-bench -- Version 5.0.0

```

**Comment by TomTheBear** [comment]
Have you built LIKWID yourself or is it some packaged version? I cannot find a 5.x.x version where the "unsupported processor" error output is on line 1216 in `src/perfmon.c`.

I have no problems with LIKWID 5.0.0 on an Intel(R) Xeon(R) Gold 6246 CPU @ 3.30GHz.

Please provide the output of `likwid-topology -V 3 | head -n 1`. It outputs the IDs that are used in LIKWID.

**Comment by nournadar** [comment]
I built from source 
```
$ likwid-perfctr -v
likwid-perfctr -- Version 5.0.0 (commit: 233ab943543480cd46058b34616c174198ba0459)
```

**Comment by TomTheBear** [comment]
This all looks correct to me.

Does `likwid-topology` properly identify your chip?
Example:
```
CPU name:       Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
CPU type:       Intel Xeon IvyBridge EN/EP/EX processor
CPU stepping:   4
```
There are multiple location where the family and model ID is used, I'm trying to identify where it fails. The `CPU type` setting is made in `src/topology.c`while fail in `src/perfmon.c`. Perfmon uses the IDs twice, once for configuring the event/counter lists and once to adjust the function pointers for start/stop/read.

**Comment by nournadar** [comment]
```
$ likwid-topology
--------------------------------------------------------------------------------
CPU name:       Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
CPU type:       Intel Skylake SP processor
CPU stepping:   4
********************************************************************************
Hardware Thread Topology
********************************************************************************
Sockets:                2
Cores per socket:       20
Threads per core:       2
```

**Comment by TomTheBear** [comment]
You used `sudo` when opening the issue. Does `sudo likwid-topology` work as well?

Otherwise, can you please rebuild using the current master and try again. I havn't changed anything but the error points me to lines in the current version and not some old commit. Have you changed the `ACCESSMODE` in `config.mk`?

The commit hash that's printed in the version output does not help, it is the same already a long time. See #226 .

**Comment by TomTheBear** [comment]
Any updates?
