### ISSUE TITLE
Trying to run on more than one core

### ISSUE THREAD

**Issue by Rabab53** [RRZE-HPC/likwid#315]
I am trying to use likwid-perfctr  command to access DRAM level information:

likwid-perfctr  -C 0-5 -g MEM  -m numactl --interleave=all ./a.out
INFO: You are running LIKWID in a cpuset with 1 CPUs. Taking given IDs as logical ID in cpuset
WARN: Selected affinity domain N has only 1 hardware threads, but selection string evaluates to 2 threads.
     This results in multiple threads on the same hardware thread.
/scratch/user/likwid/likwid_install/bin/likwid-lua: Cannot parse cpustring
stack traceback:
	[C]: in function 'likwid.cpustr_to_cpulist'
	...cratch/user/likwid/likwid_install/bin/likwid-perfctr:224: in main chunk
	[C]: in ?
Could you please advise?

**Comment by TomTheBear** [comment]
Were you able to find the solution yourself? You probably tried to use LIKWID inside of some batch job with a limited cpuset.

**Comment by Rabab53** [comment]
Yes using  LIKWID inside of batch job helps. Thanks
