### ISSUE TITLE
Error when running likwid-perfctr on Haswell 

### ISSUE THREAD

**Issue by nournadar** [RRZE-HPC/likwid#318]
I have likwid version 5 compiled with gcc 8.3 installed as a module 
Same module works on Skylake architecture with no errors 
I can see haswell in the supported architectures. Any idea why I am getting this ?
```
$ likwid-perfctr -c 0-36 -g L2 likwid-bench -t copy_mem -w S1:1GB:2 -w S0:1GB:2
--------------------------------------------------------------------------------
CPU name:       Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz
CPU type:       Intel Xeon Haswell EN/EP/EX processor
CPU clock:      2.30 GHz
Cannot get access to MSRs. Please check permissions to the MSRs
```

**Comment by ntippman** [comment]
This should fix the access to the MSR files.
`sudo modprobe msr`

**Comment by nournadar** [comment]
Thank you this seems to work for me
