### ISSUE TITLE
Need for Zen+ support

### ISSUE THREAD

**Issue by edisonchan** [RRZE-HPC/likwid#319]
I have a laptop which use a Zen+ CPU(Ryzen 3550H), its info:
grep -E "model|family|stepping" /proc/cpuinfo | sort -u

cpu family	: 23
model		: 24
model name	: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
stepping	: 1

I had tried a patch which was in a closed issue: https://github.com/RRZE-HPC/likwid/issues/289, but it does not work for my cpu.

**Comment by TomTheBear** [comment]
The above commit contains the patch or you use [zenplus.txt](https://github.com/RRZE-HPC/likwid/files/5118988/zenplus.txt). You were lucky, I just worked on AMD Zen.

It will be in the 5.0.2 release.
