### ISSUE TITLE
Can not work after turn smt off by script in linux.

### ISSUE THREAD

**Issue by edisonchan** [RRZE-HPC/likwid#320]
My Ryzen 3550 laptop does not provide the SMT setting, so I need to use a script to turn off the SMT in Linux before to test something.
My script:

#!/bin/sh
for n in 1 3 5 7
   do echo 0 > /sys/devices/system/cpu/cpu${n}/online
done

cat /sys/devices/system/cpu/smt/active
lscpu --extended

The likwid-perfctr would report error core dumped after I ran such script, for example:

likwid-perfctr -g DATA  ./geekbench5
--------------------------------------------------------------------------------
CPU name:	AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx  
CPU type:	AMD K17 (Zen+) architecture
CPU clock:	2.10 GHz
Segmentation fault (core dumped)

The likwid was built with the patch https://github.com/RRZE-HPC/likwid/issues/319 .

**Comment by TomTheBear** [comment]
Why do you have to shut down the SMT threads and not just tell LIKWID and the application to not use them?
`likwid-perfctr -C N:0-3 -g DATA ...` should do the trick. As long as `geekbench` respects cpusets, this should work.

LIKWID on x86_64 is getting it's information from hwloc. I have to check how hwloc behaves if hw threads are taken offline. The PR #296 will contain checks for offline/online hw threads but for different reasons.

**Comment by edisonchan** [comment]
SMT would cause some resource be shared  in half for each virtual core, so in some case disable SMT would be nice.
http://developer.amd.com/wp-content/resources/56420.pdf
https://www.codeblueprint.co.uk/2019/11/05/does-smt-make-sense.html

btw, the latest git clone of likwid does not work with Ryzen 3550H and can not use the #319 patch for resolve the problem.

**Comment by TomTheBear** [comment]
It is true that some resources are shared with SMT but does the runtime change free these resources or just if you disable SMT at boot time? If you look at the [kernel documentation](https://www.kernel.org/doc/html/v5.8/core-api/cpu_hotplug.html), it states "logically shutdown" and the bulletpoints in section "The offline case" do not contain "freeing resources".

You probably have to wait until the A64FX PR is merged. But this will check the online/offline state of CPUs only once when gathering the topology. If you shut down single HW threads during a LIKWID run, it will still result in an error, probably segfault.

**Comment by TomTheBear** [comment]
This patch from the A64FX PR should fix your problems: https://github.com/RRZE-HPC/likwid/pull/296/commits/3ba94e05875d0b21787736f9a870339cd8382131

**Comment by TomTheBear** [comment]
Fixed in 5.1.0
