### ISSUE TITLE
Passing LD_PRELOAD to likwid

### ISSUE THREAD

**Issue by buketbenek** [RRZE-HPC/likwid#321]
Dear Sir/Madam,

We would like to test some calls from a library loaded via LD_PRELOAD. However, it is not passed to likwid-perfctr.

Is there any workaround for that?

Regards,
Buket

**Comment by TomTheBear** [comment]
Hi,

Where do you want to use the `LD_PRELOAD`'ed functions? Inside `likwid-perfctr` or in the application wrapped by it?

`likwid-perfctr` expands the `LD_PRELOAD` environment variable in case of pinning (`-C`) to add the pinning library (`liblikwidpin.so`). Of course, it keeps everything that's inside `LD_PRELOAD` before.
https://github.com/RRZE-HPC/likwid/blob/master/src/applications/likwid-perfctr.lua#L809-L814

```
$ cat echo_env.sh
#!/bin/bash
env
$ chmod +x echo_env.sh
$ LD_PRELOAD=bla likwid-perfctr -C 0,1 -g BRANCH ./echo_env.sh | grep LD_PRELOAD
ERROR: ld.so: object 'bla' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
LD_PRELOAD=bla
```

`likwid-perfctr` forwards it to the wrapped application. Can you provide a test case to show your exact problems?

**Comment by buketbenek** [comment]
Dear Thomas,

Sorry for replying late. We would like to LD_PRELOAD our library to the application wrapped by likwid-perfctr. From your explanations, it shouldn't be a problem to use the overloaded functions and analyse with likwid-perfctr. It might be a problem coming from the library.

I can contact again if the problem continues after we fully debugged the issue in our side.

Thanks a lot.
Regards,
Buket

**Comment by TomTheBear** [comment]
Dear Buket,

I thought about it again and it might be an LIKWID issue if the mechanism to start the wrapped application does not take action based on `LD_PRELOAD`. LIKWID uses `fork()` followed by `execvp()` to start the application (https://github.com/RRZE-HPC/likwid/blob/master/src/luawid.c#L1967). If `LD_PRELOAD` is somehow triggered by the shell or some other mechanism, the preloading of libraries might not work.
When I executed the `echo_env` example in my last post, I got the line `ERROR: ld.so: object 'bla' from LD_PRELOAD cannot...` three times but I have not checked which execution triggered them. Once definitely when executing `likwid-perfctr` but I'm not sure about the other two lines. It might be the start of the `accessdaemon` and the wrapped application but that's just a guess.

Best regards,
Thomas

**Comment by buketbenek** [comment]
Dear Thomas,

Thanks for your reply. We are almost done with debugging the library. We found the correct setting that works without an issue. However, it still fails with likwid analysis.

So, I did the trick in Line 2025 of luawid.c with replacing execvp() with execve as follows:

```
char *const envs[] = {"LD_PRELOAD=/home/bgursoy/spin_test/libspin/libspin.so",NULL};
status = execve(*argv, argv, envs);
```

It works now after the rebuilt for Wrapper Mode:

```
$ /home/bgursoy/likwid-5.0.1/bin/likwid-perfctr -C S0:0 -g MEM ./gdr_test
```

However, it doesn’t work for the Marker Mode:

```
[bgursoy@joules likwid_test]$ g++ gdr_likwid.cpp -DLIKWID_PERFMON -L/home/bgursoy/likwid-5.0.1/lib -I/home/bgursoy/likwid-5.0.1/include -Wl,--rpath,/home/bgursoy/likwid-5.0.1/lib -lcudart -lcuda -lpthread -ldl -lgdrapi -o gdr_test -llikwid

[bgursoy@joules likwid_test]$ /home/bgursoy/likwid-5.0.1/bin/likwid-perfctr -C S0:0 -g MEM -m ./gdr_test
```

The error: “Marker API result file does not exist. This may happen if the application has not called LIKWID_MARKER_CLOSE.”. However, marked region code should be correct:
```
LIKWID_MARKER_INIT;
LIKWID_MARKER_START(“test”);
…
LIKWID_MARKER_STOP(“test”);
LIKWID_MARKER_CLOSE;
```

Can it be the affect of execve() workaround on the Marker API?

**Comment by TomTheBear** [comment]
Thanks for your input. I tried it again and cannot see any problems.

I created a simple LD_PRELOAD tool that overloads the `close()` function and prints `[LD_PRELOAD]`. Moreover, I wrote an application that does some computation on arrays and open/closes a file with output.

WIthout LIKWID:
```
$ LD_PRELOAD=overload_close.so ./test_openclose
Running without Marker API. Activate Marker API with -m on commandline.
Opening testfile.txt
Closing testfile.txt
[LD_PRELOAD]
```

With `likwid-perfctr`:
```
$ LD_PRELOAD=overload_close.so likwid-perfctr -C 0 -g CLOCK ./test_openclose
--------------------------------------------------------------------------------
CPU name:	Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
CPU type:	Intel Core Haswell processor
CPU clock:	3.39 GHz
--------------------------------------------------------------------------------
Running without Marker API. Activate Marker API with -m on commandline.
Opening testfile.txt
Closing testfile.txt
[LD_PRELOAD]
--------------------------------------------------------------------------------
Group 1: CLOCK
+-----------------------+---------+-----------+
|         Event         | Counter |   Core 0  |
+-----------------------+---------+-----------+
|   INSTR_RETIRED_ANY   |  FIXC0  | 841702794 |
| CPU_CLK_UNHALTED_CORE |  FIXC1  | 376359941 |
|  CPU_CLK_UNHALTED_REF |  FIXC2  | 341724582 |
|     PWR_PKG_ENERGY    |   PWR0  |    2.2894 |
|      UNCORE_CLOCK     | UBOXFIX |         0 |
+-----------------------+---------+-----------+

+----------------------+-----------+
|        Metric        |   Core 0  |
+----------------------+-----------+
|  Runtime (RDTSC) [s] |    0.1117 |
| Runtime unhalted [s] |    0.1109 |
|      Clock [MHz]     | 3735.9697 |
|  Uncore Clock [MHz]  |         0 |
|          CPI         |    0.4471 |
|      Energy [J]      |    2.2894 |
|       Power [W]      |   20.5014 |
+----------------------+-----------+
```
Due to my bad selection of the overloaded function, the `[LD_PRELOAD]` is printed quite often during the run. I omitted those in the output.

With `likwid-perfctr` and MarkerAPI calls around the computation:
```
$ LD_PRELOAD=overload_close.so likwid-perfctr -C 0 -g CLOCK -m ./test_openclose
--------------------------------------------------------------------------------
CPU name:	Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
CPU type:	Intel Core Haswell processor
CPU clock:	3.39 GHz
--------------------------------------------------------------------------------
Opening testfile.txt
Closing testfile.txt
[LD_PRELOAD]
--------------------------------------------------------------------------------
Region loop, Group 1: CLOCK
+-------------------+----------+
|    Region Info    |  Core 0  |
+-------------------+----------+
| RDTSC Runtime [s] | 0.098941 |
|     call count    |        1 |
+-------------------+----------+

+-----------------------+---------+-----------+
|         Event         | Counter |   Core 0  |
+-----------------------+---------+-----------+
|   INSTR_RETIRED_ANY   |  FIXC0  | 840015000 |
| CPU_CLK_UNHALTED_CORE |  FIXC1  | 372463200 |
|  CPU_CLK_UNHALTED_REF |  FIXC2  | 334938800 |
|     PWR_PKG_ENERGY    |   PWR0  |    2.1674 |
|      UNCORE_CLOCK     | UBOXFIX | 373402500 |
+-----------------------+---------+-----------+

+----------------------+-----------+
|        Metric        |   Core 0  |
+----------------------+-----------+
|  Runtime (RDTSC) [s] |    0.0989 |
| Runtime unhalted [s] |    0.1098 |
|      Clock [MHz]     | 3772.2105 |
|  Uncore Clock [MHz]  | 3774.0038 |
|          CPI         |    0.4434 |
|      Energy [J]      |    2.1674 |
|       Power [W]      |   21.9062 |
+----------------------+-----------+
```

All these tests are done with the current 5.0.2 release without any changes. I see some problems since the `LD_PRELOAD` overload kicks in already for the LIKWID code and maybe I should add an `--env <name>=<value>` option to `likwid-perfctr`.

**Comment by TomTheBear** [comment]
Any updates?

**Comment by buketbenek** [comment]
Dear Thomas,

I will be able to work on your reply next week.

I am sorry for not replying and Thank you very much for the directions.

I will write how it goes.

Regards,
Buket

**Comment by buketbenek** [comment]
Dear Thomas,

I tried with the latest version 5.1.0 and it works now. Maybe, it was related with some definitions related with our library but it works with the latest version now.

Thank you very much for all the help.

Regards,
Buket

**Comment by TomTheBear** [comment]
Dear Buket,
Thanks for the update. I'm glad it works now on your side. I'll close the issue but if you encounter related problems, feel free to activate the issue again.
Best,
Thomas
