### ISSUE TITLE
Skylake-SP LLC-Counters (TID Option)

### ISSUE THREAD

**Issue by ferdi15** [RRZE-HPC/likwid#331]
Hi,
According to your wiki Documentation (https://github.com/RRZE-HPC/likwid/wiki/SkylakeSP) you can set 8 Bits in the TID option. The Intel Documentation says, you need to set in total 9 Bits (Cn_MSR_PMON_BOX_FILTER0 Register Bits 8:0).
How do I need to handle this, to use the Filter correctly? 

Best regards 
Ferdi

**Comment by TomTheBear** [comment]
Hi,

Good find. It's not just a documentation issue but also the code only sets 8 bits for the TID option: https://github.com/RRZE-HPC/likwid/blob/master/src/includes/perfmon_skylake.h#L374 

I'll keep the issue open to remind me to update the documentation as soon as LIKWID 5.1.0 comes out.

Thanks
Thomas

**Comment by TomTheBear** [comment]
If you are interested in how to apply counter/event options in general: https://github.com/RRZE-HPC/likwid/wiki/likwid-perfctr#using-custom-event-or-counter-related-options

**Comment by ferdi15** [comment]
Thanks for your response. I'm already quit familiar with these options. I was just a little bit confused about the TID option, but I also found the issue in the perfmon_skylake.h file.

Thanks
Ferdinand

**Comment by TomTheBear** [comment]
You are welcome. I just wrote that text yesterday because I didn't find a good text about the options in the Wiki.

**Comment by ferdi15** [comment]
I found a short text about the Options here: https://github.com/RRZE-HPC/likwid/wiki/TutorialOptions
In the TutorialOptions Text you are separating the Options EDGEDETECT:THRESHOLD=0x1 with a ":". In your new Text EDGEDETECT=0x1|THRESHOLD=0x1  you're using a "|". 
Are both seperators correct?

**Comment by TomTheBear** [comment]
I should have searched more carefully.

I changed the separator in the new text to `:`. That's the right one. `|` won't work as it is interpreted by the shell.

It was already late.

**Comment by TomTheBear** [comment]
I updated the wiki page
