### ISSUE TITLE
Zen3 support need.

### ISSUE THREAD

**Issue by edisonchan** [RRZE-HPC/likwid#332]
**Why do you need support for this specific architecture?**
I have a Zen 3 CPU on hand.

**Which architecture model, family and further information? CPU or accelerator? **
Ryzen 5800X.
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 25
model           : 33
model name      : AMD Ryzen 7 5800X 8-Core Processor
stepping        : 0
microcode       : 0xa201009
cpu MHz         : 2152.943
cache size      : 512 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 8
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes

**Is the documentation of the hardware counters publicly available?**
Not yet, but I think most of them should same to Zen 2.
reference for thermal info of Zen3 :
https://lore.kernel.org/lkml/20200914200715.1997757-1-wei.huang2@amd.com/
https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.7-Perf-Changes

**Are there already any usable tools (commercial or open-source)?**
Not sure.
Linux perf should have some kind support for Zen3.

**Comment by TomTheBear** [comment]
AMD has released [this document](https://www.amd.com/system/files/TechDocs/55922-A1-PUB.zip) but your system is not "model 60h" but "model 21h" (33). Also, until now, the CPU family for AMD Zen 1/2 was 0x17 but yours is 0x19 (25). So I'm not sure whether the document is suitable for your chip.

Moreover, although I can add architectures based on the documentation, I cannot release the support without testing.

Nevertheless, I'm interested in adding Zen3 support.

**Comment by TomTheBear** [comment]
See #339
