### ISSUE TITLE
[BUG] Memory bandwidth showing 0 MB/s except for core 0 on Zen2

### ISSUE THREAD

**Issue by keichi** [RRZE-HPC/likwid#335]
**Describe the bug**
I'm trying to measure the memory bandwidth of my application using `likwid-perfctr` but it shows0 MB/s except for core 0.

**To Reproduce**
* LIKWID command and/or API usage
    ```
    sudo likwid-perfctr -C N:0-3 -c N:0-3 -g MEM -m likwid-bench -t stream_sp_avx -w N:500MB:4
    ```
* LIKWID version and download source (Github, FTP, package manger, ...): LIKWID 5.0.1, downloaded from this GitHub repository and compiled from source
* Operating system: Debian 10.6 (Linux 4.19.0-12-amd64)
* Does your application use libraries like MPI, OpenMP or Pthreads?: OpenMP
* In case of Nvidia GPUs, which CUDA version?: N/A
* Are you using the MarkerAPI (CPU code instrumentation) or the NvMarkerAPI (Nvidia GPU code instrumentation)?: Yes, but it also happens without the marker API.

**To Reproduce with a LIKWID command**
Please supply the output of the command with `-V 3` added to the command: [gist](https://gist.github.com/keichi/aa1aa25b1358ae84288bf76a6d054788)

**Additional context**
This might be related to #294 but I do get a seemingly correct measurement on core 0.

**Comment by TomTheBear** [comment]
Some performance monitoring units are not available on a per-core basis but per-NUMA-domain, per-socket or even per-node basis. Memory controllers are commonly per-socket. Therefore, LIKWID selects one code in your cpuset per-socket to measure them.

If you look at the [Zen2 architecture page](https://github.com/RRZE-HPC/likwid/wiki/Zen2) in the wiki, you can see which counters are available at which granularity.

**Comment by TomTheBear** [comment]
Further remarks: You don't need to specify the cpuset twice `-C N:0-3 -c N:0-3`. Use either `-C` if you want pinning (recommended) or `-c` if you just want to measure those cores but the user or the application is responsible to run on those cores.

**Comment by keichi** [comment]
Got it; I should've noticed that wiki page. Thanks a lot!
