### ISSUE TITLE
[BUG] failed to compile on aarch64

### ISSUE THREAD

**Issue by dfaraj** [RRZE-HPC/likwid#338]
I downloaded version 5.0.2 on arm node

lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              48
On-line CPU(s) list: 0-47
Thread(s) per core:  1
Core(s) per socket:  12
Socket(s):           4
NUMA node(s):        4
Vendor ID:           0x46
Model:               0
Stepping:            0x1
BogoMIPS:            200.00
NUMA node0 CPU(s):   0-11
NUMA node1 CPU(s):   12-23
NUMA node2 CPU(s):   24-35
NUMA node3 CPU(s):   36-47
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm fcma dcpop sve

when issued make, I got this

./src/access_x86_msr.c: In function ‘test_rdpmc’:
./src/access_x86_msr.c:83:5: error: impossible constraint in ‘asm’
     __asm__ volatile("rdpmc" : "=a" (low), "=d" (high) : "c" (counter));

**Comment by TomTheBear** [comment]
You have to change the `COMPILER` in `config.mk` to `GCCARMv8` and rebuild (`make distclean && make`)

**Comment by TomTheBear** [comment]
For Fujitsu A64FX you have to use the current `master` branch. I'll publish a release with A64FX support soon.
