### ISSUE TITLE
Integer Benchmarks using likwid-bench

### ISSUE THREAD

**Issue by cod3monk** [RRZE-HPC/likwid#34]
According to [the likwid-bench wiki page](https://github.com/RRZE-HPC/likwid/wiki/Likwid-Bench#adding-benchmarks), `TYPE INT` is supported, but the following bench code does not compile for me:

> STREAMS 1
> TYPE INT
> FLOPS 0
> BYTES 4
> DESC Integer load, only 32-bit scalar operations
> LOADS 1
> STORES 0
> LOOP 1
> movl    ISCALAR, [STR0 + GPR1 * 4]

with this error message:
> ===>  ASSEMBLE  GCC/load_int32.o
> ./GCC/load_int32.s: Assembler messages:
> ./GCC/load_int32.s:32: Error: no such instruction: `type INT'
> ./GCC/load_int32.s:36: Error: no such instruction: `movl ISCALAR,[rsi+rax * 4]'
> make[1]: *** [GCC/load_int32.o] Error 1

Thanks and cheers from ATX.

**Comment by TomTheBear** [comment]
This is a mistake in the Wiki page. The supported types are SINGLE (float) and DOUBLE (double).

https://github.com/RRZE-HPC/likwid/commit/62584903d8a76ef4943128459c92241ef5b04f34
and
https://github.com/RRZE-HPC/likwid/commit/05b377556b87062b86200edda6c1581d58f884ee

With the commits it works also for INT.
Comment on your code: You try to load from STREAM0 to a constant value. You need a register here. A load into GPR4 from STREAM0 would be like this: `movq GPR4, [STR0 + GPR1 * 4]`.
I don't get why `movl` is not supported, it is a valid instruction for GAS. It works with `movq`.
