### ISSUE TITLE
Running likwid-perfctr without sudo in AArch64 yields permission denied

### ISSUE THREAD

**Issue by arnamoy10** [RRZE-HPC/likwid#342]
I was trying to run LIKWID in a machine where I do not have sudo access, with a AArch64 architecture.

I followed the instructions listed [here](https://github.com/RRZE-HPC/likwid/wiki/TutorialLikwidPerf), where it mentions I do not need sudo access for installing LIKWID.  So I did

```
make
make install
```

Then I created a C file and compiled using gcc 

`gcc -DLIKWID_PERFMON -I ~/likwid-install/include/ -L ~/likwid-install/lib/ likwid_example.c -o test -llikwid`

I set the `LD_LIBRARY_PATH` appropriately.

But when I run the application --> `~/likwid-install/bin/likwid-perfctr -C S0:0 -g L3 -m ./test 40 5 40`, it shows:

```
WARN: Linux kernel configured with paranoid level 3
Setup of event INST_RETIRED on CPU 0 failed: Permission denied
Setup of event CPU_CYCLES on CPU 0 failed: Permission denied
Setup of event L2D_CACHE_REFILL on CPU 0 failed: Permission denied
Setup of event L2D_CACHE_WB on CPU 0 failed: Permission denied
```

Can you please help?

Thank you

**Comment by TomTheBear** [comment]
Unfortunately, you cannot use LIKWID with perf_event paranoid value 3.

**Comment by TomTheBear** [comment]
I added a better check for the paranoid level with better output functions. Now LIKWID tells you that it does not work with paranoid greater or equal than 3.
