### ISSUE TITLE
likwid-perfctr MEM group when running multiple processes simultaneously

### ISSUE THREAD

**Issue by goghino** [RRZE-HPC/likwid#346]
Consider a computation setup on ZEN 2 architecture, where multiple single core processes are running simultaneously on different cores within a single NUMA domain. I would like to monitor MEM counters for each of these processes. What I observe, however, is that only the process 0 reports some nonzero numbers, i.e. 

```
+-----------------------------------+-----------+
|               Metric              |   Core 0  |
+-----------------------------------+-----------+
|        Runtime (RDTSC) [s]        |  104.5141 |
|        Runtime unhalted [s]       |  159.5837 |
|            Clock [MHz]            | 3097.6171 |
|                CPI                |    2.7922 |
|  Memory read bandwidth [MBytes/s] |   53.5399 |
|  Memory read data volume [GBytes] |    5.5957 |
| Memory write bandwidth [MBytes/s] |   51.4066 |
| Memory write data volume [GBytes] |    5.3727 |
|    Memory bandwidth [MBytes/s]    |  104.9465 |
|    Memory data volume [GBytes]    |   10.9684 |
+-----------------------------------+-----------+
```

while all other processes (1-63) report zeros, i.e.

```
+-----------------------------------+-----------+
|               Metric              |   Core 1  |
+-----------------------------------+-----------+
|        Runtime (RDTSC) [s]        |  107.8107 |
|        Runtime unhalted [s]       |  165.9868 |
|            Clock [MHz]            | 3108.2061 |
|                CPI                |    2.8897 |
|  Memory read bandwidth [MBytes/s] |         0 |
|  Memory read data volume [GBytes] |         0 |
| Memory write bandwidth [MBytes/s] |         0 |
| Memory write data volume [GBytes] |         0 |
|    Memory bandwidth [MBytes/s]    |         0 |
|    Memory data volume [GBytes]    |         0 |
+-----------------------------------+-----------+
```
In this case I am running the same program with identical data on every core. I wonder if this is a bug or a feature, given that the memory is a shared resource for all the cores, thus the numbers reported at process 0 are cumulative measures across all cores within the NUMA domain.

**Comment by TomTheBear** [comment]
If you look at https://github.com/RRZE-HPC/likwid/wiki/Zen2, the memory controller counters are per-socket. You cannot refer back to the traffic caused by single cores of a socket. LIKWID selects one HW thread on each socket (in your CPUset) to do the memory controller readings, thus only HW thread 0 reports values.

**Comment by goghino** [comment]
I see, thanks for clarification! Also how reliable are these numbers? I run the identical benchmark twice (expect that one time one measured only MEM, and in the second run I measured MEM and L3) and I get different readings, I would expect the data volume would be identical:

```
+-----------------------------------+-----------+
|               Metric              |   Core 0  |
+-----------------------------------+-----------+
|        Runtime (RDTSC) [s]        |  104.5141 |
|        Runtime unhalted [s]       |  159.5837 |
|            Clock [MHz]            | 3097.6171 |
|                CPI                |    2.7922 |
|  Memory read bandwidth [MBytes/s] |   53.5399 |
|  Memory read data volume [GBytes] |    5.5957 |
| Memory write bandwidth [MBytes/s] |   51.4066 |
| Memory write data volume [GBytes] |    5.3727 |
|    Memory bandwidth [MBytes/s]    |  104.9465 |
|    Memory data volume [GBytes]    |   10.9684 |
+-----------------------------------+-----------+
```

```
+-----------------------------------+-----------+
|               Metric              |   Core 0  |
+-----------------------------------+-----------+
|        Runtime (RDTSC) [s]        |   53.2669 |
|        Runtime unhalted [s]       |   82.1935 |
|            Clock [MHz]            | 3102.0149 |
|                CPI                |    2.8693 |
|  Memory read bandwidth [MBytes/s] |   58.7054 |
|  Memory read data volume [GBytes] |    3.1271 |
| Memory write bandwidth [MBytes/s] |   57.0304 |
| Memory write data volume [GBytes] |    3.0378 |
|    Memory bandwidth [MBytes/s]    |  115.7359 |
|    Memory data volume [GBytes]    |    6.1649 |
+-----------------------------------+-----------+
```

**Comment by TomTheBear** [comment]
The AMD documentation lists the metric as "approximate". The metric lines containing "read" or "write" can be ignored, the events count "traffic over channel" and not "traffic over channel in read direction". Same for write. I need to remove them for all Zen architectures.

I don't see problems in the outputs. In the second case around half the runtime is used to measure MEM (104s vs. 53s) and you see around half of the data volume from the first case (10.9GB vs. 6.1GB). LIKWID does not scale the counter results in case of multi-group measurements.
