### ISSUE TITLE
NVMARKER for likwid-perfctr is not working

### ISSUE THREAD

**Issue by cstyl** [RRZE-HPC/likwid#347]
Hi,

I am trying to use Likwid v 5.1.0 that has been compiled with NVIDIA support. The following code returns an error with id 35 which I am not sure what that is. I am using Cuda 10.2. Please let me know if you know more. Note that when I run `likwid-topology` all the GPUs on the node are listed properly.

```sh
$ likwid-perfctr -G 0 -W FLOPS_DP -m ./a.out
--------------------------------------------------------------------------------
CPU name:	Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
CPU type:	Intel Cascadelake SP processor
CPU clock:	2.50 GHz
--------------------------------------------------------------------------------
Error: function (*cuptiProfilerBeginSessionPtr)(&beginSessionParams) failed with error 35.
Error starting up GPU Marker API.
--------------------------------------------------------------------------------
GPU Marker API result file does not exist. This may happen if the application has not called LIKWID_GPUMARKER_CLOSE.
```

**Comment by TomTheBear** [comment]
Error 35 is `CUPTI_ERROR_INSUFFICIENT_PRIVILEGES`. I havn't found a way to check the privileges before starting the measurement to print out a proper message.

User measurements have to be allowed by the admin:
https://developer.nvidia.com/nvidia-development-tools-solutions-err-nvgpuctrperm-cupti
https://developer.nvidia.com/nvidia-development-tools-solutions-err_nvgpuctrperm-permission-issue-performance-counters#SolnAdminTag

**Comment by cstyl** [comment]
Thank you for the update Tom. I manage to get it working after talking to the admins.
