### ISSUE TITLE
Performance Groups on Zen3

### ISSUE THREAD

**Issue by ErikP94** [RRZE-HPC/likwid#348]
Hi there!

We will be getting Zen 3 AMD CPUs at our computing centre soon and I plan to use Likwid heavily for Monitoring purposes (thanks for this really cool tool by the way). I wanted to have a look at the existing performance groups on Zen3 and had to find out that the folder is still empty. The support for this architecture is marked 'limited' on the Github mainpage.

This CPU is brandnew, so I obviously understand that it isn't fully supported yet. i just wanted to ask if you can estimate when you can use likwid on this architecture.

Cheers,
Erik

**Comment by TomTheBear** [comment]
Hi Erik,

Until now, the Family 19h PPR documentation has not been published by AMD (see [TechDocs](https://www.amd.com/en/support/tech-docs)). I check the site from time to time and as soon as the documentation is there, I can finish the work on Zen3. The current LIKWID version contains the same logic as the Linux kernel but the event lists are still missing publicly.

For testing, you can copy the [Zen2 events](https://github.com/RRZE-HPC/likwid/blob/master/src/includes/perfmon_zen2_events.txt) into the [Zen3 events file](https://github.com/RRZE-HPC/likwid/blob/master/src/includes/perfmon_zen3_events.txt) and recompile (same for group files). Don't use the measurements for anything important, there are probably changes between Zen2 and Zen3 events. As soon as the Zen3 support is merged, you just have to replace the groups and eventlist to get fully support.

Best,
Thomas

**Comment by ErikP94** [comment]
Thanks for the quick answer!

**Comment by gabriel-rodriguez** [comment]
I am also interested in the Zen3 support, but alas the PPR is still unpublished. I have used the "trick" of copying Zen2 events into Zen3 events, the results I have seen don't look half bad. However, I'm missing lots of useful stuff present in Intel cores, like the L2CACHE and L3CACHE groups. Is this not implementable with the Zen performance registers, or is the implementation in likwid not complete at this time?

**Comment by TomTheBear** [comment]
The `L2CACHE` and `L3CACHE` groups are just not written yet. Most architectures provide the events required for the `LxCACHE` groups. The events are available for Zen1 and Zen2. You can create the groups [yourself](https://github.com/RRZE-HPC/likwid/wiki/likwid-perfctr#defining-custom-performance-groups) or wait until we add them.

**Comment by gabriel-rodriguez** [comment]
Thanks a lot for the quick reply! I'll try to implement them myself if I find the time to spare. Let me know if it would be useful for you if I report back the results somehow.

**Comment by TomTheBear** [comment]
I just added the event list and performance groups for AMD Zen3 to the `master` branch

**Comment by TomTheBear** [comment]
I checked the events required for `L2CACHE` and `L3CACHE` in the new Zen3 documentation. On Intel, we use "all L2 accesses" and "all L2 misses" but these metrics on AMD require 7 events while having only 6 counter registers. But `all L2 accesses` and `all L2 hits` are possible. I added them but marked them as "experimental" as I don't have access to an AMD Zen3 system at the moment.
