### ISSUE TITLE
likwid-mpirun hostfile parsing

### ISSUE THREAD

**Issue by axeliniyes** [RRZE-HPC/likwid#35]
### Hello,
There is a problem when likwid-mpirun read the hostfile the user provides, if the hosts names contains, for example, a dash in the name the program will ignore all its name after the dash making:

- host1-10
- host1-11
- host1-12
- host2-10

into:

- host1
- host1
- host1
- host2

And so the mpi execution will fail because it will not found the good names for the hosts.

The solution is to replace the line 

hostname = line:match("^([%.%a%d]+)")

of all 4 readHostfile* methods to:

hostname = line:match("^([%.%a%d-]+)")

but anyway this solution is for this specific problem, I think that the regular expression should take all the line from the hostfile without modifications.

**Comment by axeliniyes** [comment]
Hello, the pattern is not working:

([%.%a%d_-])+

should be:

([%.%a%d_-]+)

**Comment by TomTheBear** [comment]
I fixed it in commit https://github.com/RRZE-HPC/likwid/commit/3c9c337bc099114c80c190e1c176c14da9f80cdc
