### ISSUE TITLE
Static case for  likwid-bench

### ISSUE THREAD

**Issue by Qinghe12** [RRZE-HPC/likwid#356]
Every case in likwid-bench has to been recompilered when starting 1 test, which cost too much time.
Is‘t possible for  likwid-bench  to run the bench suite staticlly，like copy_avx？
Or can I port the  case out as a complete elf in linux?

**Comment by TomTheBear** [comment]
I understand what you want to do but I don't get what "every case [...] has to been recompiled" means. If you change a kernel in the source tree, the build system will rebuild the test (and possibly some others) but not every kernel. The kernels included in `likwid-bench` are commonly static thus no rebuilding is required. If you want to do prototyping, use the [dynamic kernel loading](https://github.com/RRZE-HPC/likwid/wiki/Likwid-Bench#adding-benchmarks) feature where you place the kernel file in a specific folder and `likwid-bench` parses, compiles and runs it on-the-fly.

There is no way to extract an ELF out of `likwid-bench`. The kernels are only functions, the whole allocation and threading logic is in the main `likwid-bench`.

**Comment by Qinghe12** [comment]
Thanks for your reply.
I found another question，in stream_avx case , the performance as following implementation using unrolling-loops  would be 30% lower than no unrolling-loops or more. 
....
 vmovaps    ymm1, [STR1 + GPR1*8]
 vmovaps    ymm2, [STR1 + GPR1*8+32]
 vmovaps    ymm3, [STR1 + GPR1*8+64]
 vmovaps    ymm4, [STR1 + GPR1*8+96]
 vmulpd     ymm1, ymm1, ymm5
 vaddpd     ymm1, ymm1, [STR2 + GPR1*8]
 vmulpd     ymm2, ymm2, ymm5
 vaddpd     ymm2, ymm2, [STR2 + GPR1*8+32]
 vmulpd     ymm3, ymm3, ymm5
 vaddpd     ymm3, ymm3, [STR2 + GPR1*8+64]
 vmulpd     ymm4, ymm4, ymm5
 vaddpd     ymm4, ymm4, [STR2 + GPR1*8+96]
 vmovaps    [STR0 + GPR1*8]   , ymm1
 vmovaps    [STR0 + GPR1*8+32], ymm2
 vmovaps    [STR0 + GPR1*8+64], ymm3
 vmovaps    [STR0 + GPR1*8+96], ymm4
....

last question about likwid-bench，how can I config the stride for a certain case,like stream_avx.
Could you help to provide a example.
-w         <thread_domain>:<size>[:<num_threads>[:<chunk size>:<stride>]-<streamId>:<domain_id>[:<offset>]

**Comment by TomTheBear** [comment]
I don't get your comment. You mean that the not-unrolled version is performing better? This is not the case for my system.

`$ likwid-bench -t stream_avx -w N:10kB:1)`
* Not-unrolled: `97431.49 MByte/s`
* 4xUnrolled: `132965.95 MByte/s` (default `stream_avx`)

You cannot "configure" it but you can manipulate the loop counter register `GPR1` yourself at the end of the loop.

For the last question, have you checked the man or [wiki](https://github.com/RRZE-HPC/likwid/wiki/Likwid-Bench) page? In short, the `-:<domain_id>[:]` in your notation can be used to control the placement of the streams, like both streams in socket 1 (number of streams depend on the test case) but all threads on socket 0 (`-w S0:1GB:10:1:2-0:S1,1:S1`).

**Comment by TomTheBear** [comment]
Any updates?
