### ISSUE TITLE
likwid-mpirun passing a float to bash

### ISSUE THREAD

**Issue by axeliniyes** [RRZE-HPC/likwid#36]
In the script likwid-mpirun in the function: writeWrapperScript

There are cases where a float is written in the bash script causing errors in bash and stopping working:

`likwid-mpirun -hostfile $OAR_NODEFILE -np 8 -d echo $HOSTNAME` results in:

`/home/users/dlagunes/.likwidscript_22531.txt: line 8: [: 8.0: integer expression expected
/home/users/dlagunes/.likwidscript_22531.txt: line 11: 0 - (8.0 - 1): syntax error: invalid arithmetic operator (error token is ".0 - 1)")
`
the error must be when this operation `local full = tostring(np - (np % ppn))` returns an integer with an appended ".0" 

**Solution**: use math.floor lua function to force a integer in all instances of the variable "full"

`local full = tostring(math.floor(np - (np % ppn)))`

**Comment by TomTheBear** [comment]
This was already fixed in commit https://github.com/RRZE-HPC/likwid/commit/d6caba8850747ef9e9c1d2db3e642769a0a0b045.
The commit sets the mentioned line to
`local full = tostring(math.tointeger(np - (np % ppn)))`
All other cases were Integers are needed also use the `math.tointeger()` function.
