### ISSUE TITLE
[BUG] Likwid hangs while instrumenting contained subroutines with MarkerAPI in Fortran 

### ISSUE THREAD

**Issue by ErikP94** [RRZE-HPC/likwid#362]
Hil all,

I tried to mark some regions in a Fortran Code using the MarkerAPI. This usually worked fine until know. When I instrumented some regions in an external module, everything worked well, as long as the function and subroutine calls within the region were not included in the module file. 
When I try to instrument a region e.g.

CALL likwid_markerStartRegion("example_region")
call expand_and_transpose(args)
CALL likwid_markerStopRegion("example_region")

and the subroutine `expand_and_transpose` is located in the same file as the module, declared with a `contains` statement likwid seems to hang. Finally I get a timeout from slurm.
I am unfortunately at a loss here.
I hope I could explain the problem sufficiently and thanks in advance for your help!

Best,
Erik

**Comment by TomTheBear** [comment]
Can you supply a simple Fortran code which triggers the problem? Or at least a skeleton with `module`, `contains`and the function containing the region markers. Thanks.

**Comment by ErikP94** [comment]
Hello Thomas,

thanks for the quick reply.  Producing a simple test case didn't reproduce the error. We are working on it, I'll have to ask you for a little more patience.

Best, 
Erik

**Comment by ErikP94** [comment]
Hello Thomas,

we were able to finde the error. It wasn't on the likwid side. You may close this issue, thanks :)

Best, 
Erik

**Comment by TomTheBear** [comment]
Hi Erik,

good to read :+1: Thanks for the update.

Best,
Thomas
