### ISSUE TITLE
[Build]

### ISSUE THREAD

**Issue by lcebaman** [RRZE-HPC/likwid#375]
**Which version do you want to build?**
likwid-5.1.1-rc1

**Which architecture do you want to build for?**
- [x] x86_64

**To Reproduce**
- Changes to `config.mk` (you may leave out `PREFIX` changes)
- Changes to build configurations `make/include_<COMPILER>.mk`
- Any other changes

**Output log**
```
[sdge4@box0 likwid-5.1.1-rc1]$ make install
===> INSTALL access daemon to /home/sdge4/bin/likwid/sbin/likwid-accessD
install: cannot change ownership of ‘ /home/sdge4/bin/likwid/sbin/likwid-accessD’: Operation not permitted

```

**Comment by TomTheBear** [comment]
See #376
