### ISSUE TITLE
[Build] Ownership problem installing with same username and home location

### ISSUE THREAD

**Issue by lcebaman** [RRZE-HPC/likwid#376]
**Which version do you want to build?**
likwid-5.1.1-rc1

**Which architecture do you want to build for?**
- [x] x86_64

**To Reproduce**
```
PREFIX ?= /home/sdge4/bin/likwid
```
**Output log**
```[sdge4@box0 likwid-5.1.1-rc1]$ make install
===> INSTALL access daemon to /home/sdge4/bin/likwid/sbin/likwid-accessD
install: cannot change ownership of ‘ /home/sdge4/bin/likwid/sbin/likwid-accessD’: Operation not permitted
```

**Comment by pramodk** [comment]
@lcebaman : see instructions [here](https://github.com/RRZE-HPC/likwid/blob/b1a42449bc2db8af8e881168d047de22261021c4/README.md#download-build-and-install) and use of `sudo make install`. Worth looking at [this doc](https://github.com/RRZE-HPC/likwid/wiki/Build#usage-of-access-daemon-likwid-accessd) as well for considering security aspects.

**Comment by TomTheBear** [comment]
Thanks @pramodk  for answering.

If you don't have root permissions on the system, think about the perf_event backend (`ACCESSMODE=perf_event`). Infos [here](https://github.com/RRZE-HPC/likwid/wiki/likwid-perfctr#using-the-perf_event-backend-with-likwid-perfctr).

P.S. Duplicate of #375

**Comment by lcebaman** [comment]
Got it. Works
