### ISSUE TITLE
[BUG] perfmon_startCounters() does not zero counters

### ISSUE THREAD

**Issue by aowenson** [RRZE-HPC/likwid#382]
**Describe the bug**
C API documentation for perfmon_startCounters() claims: "The counter registered are zeroed before enabling the counters". 
However, this only happens on the first call (if at all).

Take a simple nested loop. Before the loop I have initialised Likwid.
Inside the outer loop, perfmon_startCounters() and perfmon_stopCounters() wrap the inner loop.
Suppose the inner loop executes 100K instructions, and Likwid is monitoring INSTR_RETIRED_ANY. The first call to perfmon_stopCounters() returns 100K, but the second call returns 200K, the third call returns 300K, and so on.
Only by re-executing perfmon_addEventSet() before every call to perfmon_startCounters() do counters get reset, so that perfmon_stopCounters() returns 100K each time.

This occurs in a simple, non-parallel C code - no MPI, no OpenMP, etc.
Likwid version is 5.1.0

**Comment by TomTheBear** [comment]
So, you mean something like this?
```
perfmon_init(1, {0});
int gid = perfmon_addEventSet(EVENTSET);
setupCounters(gid);
for (int runs=0; runs < max_runs; runs++)
{
    startCounters();
    for (int i = 0; i < size; i++) { /* inner loop */ }
    stopCounters();
    for (int e = 0; e < perfmon_getNumberOfEvents(gid); e++)
         printf("Event %d: %f\n", i, perfmon_getResult(gid, e, 0));
}
perfmon_finalize();
```

Which backend and architecture are you using? For the `accessdaemon` and `direct` access most architecture-specific files contain something like this in `startCounters...`:
```
eventSet->events[i].threadCounter[thread_id].startData = 0;
eventSet->events[i].threadCounter[thread_id].counterData = 0;
```
and therefore reset the internal counter value of LIKWID. Moreover, most counter registers are zeroed as well
```
CHECK_MSR_WRITE_ERROR(HPMwrite(cpu_id, dev, counter1, 0x0ULL));
```
I might have missed an architecture. Maybe `getLastResult()` is what you should try. 

I would write the code like this:
```
perfmon_init(1, {0});
int gid = perfmon_addEventSet(EVENTSET);
setupCounters(gid);
startCounters();
for (int runs=0; runs < max_runs; runs++)
{
    readCounters();
    for (int i = 0; i < size; i++) { /* inner loop */ }
    readCounters();
    for (int e = 0; e < perfmon_getNumberOfEvents(gid); e++)
         printf("Event %d: %f\n", i, perfmon_getLastResult(gid, e, 0));
}
stopCounters();
perfmon_finalize();
```

**Comment by aowenson** [comment]
> So, you mean something like this?

Yes. An MBOX event was being monitored, on Sandy Bridge desktop.

The issue appears to be I misunderstood perfmon_getResult(), that it is intended to accumulate counts. Coming from PAPI, I was expecting the same style of start/stopping to work the same, and that perfmon_getResult() would directly return the counter value (not sum total). So, the registers are being zeroed correctly, but I didn't account for Likwid abstraction. 

I wasn't aware of perfmon_getLastResult(). Reading its documentation now it is obviously what I should be using. Can I suggest that in the example API C code, that perfmon_getLastResult() is also used?

**Comment by TomTheBear** [comment]
That's a free-running read-only hardware counter, so no chance to reset it to zero. Therefore, LIKWID reads the register value at `start` instead of zeroing it.

Yes, the idea for `getResult()` is that you can do multiple rounds of `start` -> `stop` with accumulation. I never checked PAPI in detail but what I remember LIKWID's behavior is a `read` + `accumulate` in the PAPI world.

Sure, it would be helpful to have `getLastResult()` also in the examples. Do you want to try and submit a PR or should I put it on my todo list?

**Comment by aowenson** [comment]
I'll submit a PR. Thanks Tom.
