### ISSUE TITLE
[FeatureRequest] CSV Output for Timeline Mode

### ISSUE THREAD

**Issue by jklinkenberg** [RRZE-HPC/likwid#387]
**Is your feature request related to a problem? Please describe.**
Currently likwid-perfctr allows writing the output to a text file that is parsable with `-o` and `-O`.
However, if the timeline mode is used with `-t` the documentation says that this will be sent to **stderr**.
It is hard if applications that internally also use stderr. stderr output can be piped to a spearate file but the result is not really parsable as not only likwid is writing to stderr.

**Describe the solution you'd like**
I would be nice if likwid-perfctr would allow combining the timeline and text output mode with `-t -o <file> -O`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by TomTheBear** [comment]
This is already prepared but not properly working yet (https://github.com/RRZE-HPC/likwid/blob/master/src/applications/likwid-perfctr.lua#L1105-L1110). I tried it and it writes data to the output file but overwrites it in the end in the filter section:
```
$ likwid-perfctr -C 0 -g L3 -t 1s -o output.txt -O sleep 30 &
$ tail output.txt
# HWThreads,0
# GID,MetricsCount,CpuCount,Total runtime [s],Runtime (RDTSC) [s],Runtime unhalted [s],Clock [MHz],CPI,L3 load bandwidth [MBytes/s],L3 load data volume [GBytes],L3 evict bandwidth [MBytes/s],L3 evict data volume [GBytes],L3 bandwidth [MBytes/s],L3 data volume [GBytes]
1,10,1,2.8524467967822e-05,3.795724513758e-05,6.7736690259412e-06,993.74544431831,2.4434480763668,408.03804237799,1.5488e-05,200.64680596273,7.616e-06,608.68484834073,2.3104e-05
1,10,1,1.0001076333362,0.99996093091727,0.00049308894404904,2448.081605221,0.60835372230176,0.53038872180085,0.000530368,0.19968780161924,0.00019968,0.73007652342009,0.000730048
1,10,1,2.0001895384379,0.99993298061138,0.00036866497580776,2429.533709405,0.51269017984492,0.30210024657383,0.00030208,0.018561243963222,1.856e-05,0.32066149053705,0.00032064
1,10,1,3.000269666524,0.99984840637779,0.00036380785336309,1588.0868159623,0.5103138443472,0.31575986718202,0.000315712,0.020419095404635,2.0416e-05,0.33617896258665,0.000336128
```
