### ISSUE TITLE
RAPL Energy Unit not correct on Haswell EP DRAM domain

### ISSUE THREAD

**Issue by rschoene** [RRZE-HPC/likwid#39]
We have a user that reports over-estimated power-readings for the Haswell-EP DRAM domain (factor 4). I had a look into the source code and found the bug. You only determine the energy unit by reading MSR_RAPL_POWER_UNIT.
In [1, Section 5.3.3] Intel reports that the “ENERGY UNIT for DRAM domain is 15.3 μJ". This should be used for uncore-PCI-register RAPL readings. Hackenberg et al. described in [2, Section IV] that the statement about the energy unit is also correct for the DRAM RAPL reading from MSRs.

Best,
Robert

[1] Intel® Xeon® Processor E5-1600 and E5-2600 v3 Product Families, Volume 2 of 2, Registers Datasheet, Intel Corp.
[2] An Energy Efficiency Feature Survey of the Intel Haswell Processor, Hackenberg et al., Parallel and Distributed Processing Symposium Workshop (IPDPSW), 2015

**Comment by TomTheBear** [comment]
Hi,

you didn't read the code far enough. In Line 201 the energy unit for the Haswell EP DRAM domain is changed to 15.3 uJ. 

See: https://github.com/RRZE-HPC/likwid/blob/master/src/power.c#L197-L202

The code sets first the energy unit for all domains and later handles special cases like the Haswell EP DRAM domain.

Greetings,
Thomas

**Comment by rschoene** [comment]
My bad. I didn't recognize that the github search is only "Showing the top two matches."

**Comment by TomTheBear** [comment]
So, I assume, I can close the issue?

**Comment by rschoene** [comment]
Found the real bug in likwid-powermeter and opened a pull request

**Comment by TomTheBear** [comment]
Merged already. I also started to read the power related code but I didn't see this one. Thanks for your contribution.
