### ISSUE TITLE
Rocket Lake support requrest.

### ISSUE THREAD

**Issue by edisonchan** [RRZE-HPC/likwid#391]
**Why do you need support for this specific architecture?**
I hope to use likwid to profiling Rocket Lake.

**Which architecture model, family and further information? CPU or accelerator? **
```
CPU family:                    6
Model:                           167
Model name:                  11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
```
**Is the documentation of the hardware counters publicly available?**
https://software.intel.com/content/www/us/en/develop/articles/intel-sdm.html
The RKL is backport of IceLake, I think most performance counters should be same.

**Are there already any usable tools (commercial or open-source)?**
Perf do support RKL architecture counter, but Power/Energy not yet.

```
likwid-perfctr -g Energy sleep 10
Cannot access directory /usr/local/share/likwid/perfgroups/unknown
--------------------------------------------------------------------------------
CPU name:       11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
CPU type:       Unknown Intel Processor
CPU clock:      3.50 GHz
ERROR - [./src/perfmon.c:perfmon_init_maps:1157] Unsupported Processor
ERROR - [./src/perfmon.c:perfmon_init_funcs:1690] Unsupported Processor
Segmentation fault (core dumped)
```

I can use rdmsr to read the PKG energy status:
```
sudo rdmsr -d 0x611
806652205
```

but I dont know how to use msr method to profiling a program that have high power consumption and the run time lager than 60 seconds. 

According Intel SDM: "MSR_PKG_ENERGY_STATUS is a read-only MSR. It reports the actual energy use for the package domain. This MSR is updated every ~1msec. It has a wraparound time of around 60 secs when power consumption is high, andmay be longer otherwise."

**Comment by TomTheBear** [comment]
I cannot find the Model (0xA7 = 167) in the current SDM. I checked Volume 4 Table 2-1, Lists in Volume 4 Section 1.1, Volume 3 Section 18. There is also no RKL (or similar) folder at https://download.01.org/perfmon/ .

It could be added as Icelake Client but the event list might differ. The kernel does not match on the model id but on the "performance monitoring version". The handling at hardware level is similar but the event lists might differ based on the model id. The event lists are not part of the kernel, there is only a small set included for specific use-cases. For RAPL, the kernel lookup mechanism is based on the model id. RocketLake is [not listed](https://github.com/torvalds/linux/blob/master/arch/x86/events/rapl.c#L773-L809) and consequently, no RAPL readings through `perf`.

Reading `MSR_PKG_ENERGY_STATUS` is not enough to get the power consumption. You first need the energy unit from a different MSR. You read the status twice and scale the difference by this energy unit to get the value in Joules. LIKWID reads the RAPL counters every 30 seconds to catch overflows. So, you could write a shell script that reads the MSR every X seconds and run it in the background or a different shell.

If you want to add it yourself to LIKWID, (here is how](https://github.com/RRZE-HPC/likwid/wiki/AddX86Support). Just define the model id, define name in `src/topology.c` with own switch-case and add it to to all switch-case statements in `src/perfmon.c`, `src/power.c`, `src/thermal.c` where you find `ICELAKE1`. This way it uses the Icelake Desktop logic, counter and event lists.

**Comment by edisonchan** [comment]
Thanks Tom, I think I had reach support for RKL in part ：
` likwid-perfctr -C 6 -g ENERGY sleep 10
--------------------------------------------------------------------------------
CPU name:       11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
CPU type:       Intel Rocketlake processor
CPU clock:      3.50 GHz
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Group 1: ENERGY
+-----------------------+---------+------------+
|         Event         | Counter | HWThread 6 |
+-----------------------+---------+------------+
|   INSTR_RETIRED_ANY   |  FIXC0  |     590952 |
| CPU_CLK_UNHALTED_CORE |  FIXC1  |     867647 |
|  CPU_CLK_UNHALTED_REF |  FIXC2  |     584876 |
|       TEMP_CORE       |   TMP0  |         29 |
|     PWR_PKG_ENERGY    |   PWR0  |   186.1572 |
|     PWR_PP0_ENERGY    |   PWR1  |    17.1011 |
|    PWR_DRAM_ENERGY    |   PWR3  |          0 |
+-----------------------+---------+------------+

+----------------------+------------+
|        Metric        | HWThread 6 |
+----------------------+------------+
|  Runtime (RDTSC) [s] |    10.0007 |
| Runtime unhalted [s] |     0.0002 |
|      Clock [MHz]     |  5198.1379 |
|          CPI         |     1.4682 |
|    Temperature [C]   |         29 |
|      Energy [J]      |   186.1572 |
|       Power [W]      |    18.6145 |
|    Energy PP0 [J]    |    17.1011 |
|     Power PP0 [W]    |     1.7100 |
|    Energy DRAM [J]   |          0 |
|    Power DRAM [W]    |          0 |
+----------------------+------------+
`

**Comment by TomTheBear** [comment]
You could add a PR with your changes. I could fill the missing parts, if any, to complete the support.

**Comment by edisonchan** [comment]
I found there is still a problem here: when there is more than one group, the time is not right.

 time likwid-perfctr -C 6 -g ENERGY sh doit.sh
```--------------------------------------------------------------------------------
CPU name:       11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
CPU type:       Intel Rocketlake processor
CPU clock:      3.50 GHz
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Group 1: ENERGY
+-----------------------+---------+---------------+
|         Event         | Counter |   HWThread 6  |
+-----------------------+---------+---------------+
|   INSTR_RETIRED_ANY   |  FIXC0  | 2678180048459 |
| CPU_CLK_UNHALTED_CORE |  FIXC1  |  879888016173 |
|  CPU_CLK_UNHALTED_REF |  FIXC2  |  586114570268 |
|       TEMP_CORE       |   TMP0  |            56 |
|     PWR_PKG_ENERGY    |   PWR0  |    10711.5438 |
|     PWR_PP0_ENERGY    |   PWR1  |     7991.9431 |
|    PWR_DRAM_ENERGY    |   PWR3  |             0 |
+-----------------------+---------+---------------+

+----------------------+------------+
|        Metric        | HWThread 6 |
+----------------------+------------+
|  Runtime (RDTSC) [s] |   167.5116 |
| Runtime unhalted [s] |   251.1077 |
|      Clock [MHz]     |  5260.3220 |
|          CPI         |     0.3285 |
|    Temperature [C]   |         56 |
|      Energy [J]      | 10711.5438 |
|       Power [W]      |    63.9451 |
|    Energy PP0 [J]    |  7991.9431 |
|     Power PP0 [W]    |    47.7098 |
|    Energy DRAM [J]   |          0 |
|    Power DRAM [W]    |          0 |
+----------------------+------------+


real    2m48.582s
user    2m47.337s
sys     0m0.145s
```

time likwid-perfctr -C 6 -g ENERGY -g DATA sh doit.sh
```--------------------------------------------------------------------------------
CPU name:       11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
CPU type:       Intel Rocketlake processor
CPU clock:      3.50 GHz
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Group 1: ENERGY
+-----------------------+---------+---------------+
|         Event         | Counter |   HWThread 6  |
+-----------------------+---------+---------------+
|   INSTR_RETIRED_ANY   |  FIXC0  | 1346459105684 |
| CPU_CLK_UNHALTED_CORE |  FIXC1  |  444617263627 |
|  CPU_CLK_UNHALTED_REF |  FIXC2  |  296014255546 |
|       TEMP_CORE       |   TMP0  |            56 |
|     PWR_PKG_ENERGY    |   PWR0  |     5379.9755 |
|     PWR_PP0_ENERGY    |   PWR1  |     4008.8473 |
|    PWR_DRAM_ENERGY    |   PWR3  |             0 |
+-----------------------+---------+---------------+

+----------------------+------------+
|        Metric        | HWThread 6 |
+----------------------+------------+
|  Runtime (RDTSC) [s] |    84.7570 |
| Runtime unhalted [s] |   126.8871 |
|      Clock [MHz]     |  5263.1119 |
|          CPI         |     0.3302 |
|    Temperature [C]   |         56 |
|      Energy [J]      |  5379.9755 |
|       Power [W]      |    63.4753 |
|    Energy PP0 [J]    |  4008.8473 |
|     Power PP0 [W]    |    47.2981 |
|    Energy DRAM [J]   |          0 |
|    Power DRAM [W]    |          0 |
+----------------------+------------+

Group 2: DATA
+-----------------------------+---------+---------------+
|            Event            | Counter |   HWThread 6  |
+-----------------------------+---------+---------------+
|      INSTR_RETIRED_ANY      |  FIXC0  | 1331720219816 |
|    CPU_CLK_UNHALTED_CORE    |  FIXC1  |  440465870665 |
|     CPU_CLK_UNHALTED_REF    |  FIXC2  |  293278102980 |
|  MEM_INST_RETIRED_ALL_LOADS |   PMC0  |  411300497238 |
| MEM_INST_RETIRED_ALL_STORES |   PMC1  |  229767128019 |
+-----------------------------+---------+---------------+

+----------------------+------------+
|        Metric        | HWThread 6 |
+----------------------+------------+
|  Runtime (RDTSC) [s] |    84.0030 |
| Runtime unhalted [s] |   125.7023 |
|      Clock [MHz]     |  5262.6142 |
|          CPI         |     0.3307 |
|  Load to store ratio |     1.7901 |
+----------------------+------------+


real    2m49.842s
user    2m48.259s
sys     0m0.136s
```

**Comment by TomTheBear** [comment]
I don't see a problem there, see https://github.com/RRZE-HPC/likwid/wiki/likwid-perfctr#using-multiple-event-sets-or-performance-groups-in-a-single-run
Your total runtime is around 168 seconds, each group is measured half of the time, so 84 seconds.

**Comment by edisonchan** [comment]
I dont know how to use pull request... so I upload the files to my google drive:
https://drive.google.com/file/d/1tzBalzKlFhRdzyEsY5B2YIZfBR-gg637/view?usp=sharing

**Comment by TomTheBear** [comment]
I downloaded it and open a PR for you.

There are still some questions open:
- Icelake provides a fourth fixed-purpose counter `TOPDOWN_SLOTS` but without documentation, it's unclear whether Rocketlake provides the same counter
- Icelake provides the  TMA Level 1 metrics. Are they also provided by Rocketlake?
- In your outputs, the RAPL DRAM domain didn't count but maybe it's a problem related to the domain's energy unit. The DRAM domain sometimes has a different unit than the other domains.
- Did you use the accessdaemon as access method or perf_event? With the accessdaemon, there might be some limitations because the code contains `if (model == ICELAKE1 || model == ICELAKE2)` which were not extended by `ROCKETLAKE` in your zipped code.

**Comment by edisonchan** [comment]
There is 4 TMA events in the perf list: 
```
  topdown-bad-spec OR cpu/topdown-bad-spec/          [Kernel PMU event]
  topdown-be-bound OR cpu/topdown-be-bound/          [Kernel PMU event]
  topdown-fe-bound OR cpu/topdown-fe-bound/          [Kernel PMU event]
  topdown-retiring OR cpu/topdown-retiring/          [Kernel PMU event]
```

```
perf stat -I 1000 --topdown -a
#           time             retiring      bad speculation       frontend bound        backend bound
     1.001195802                 6.7%                 6.6%                32.6%                54.0%
     2.002668103                 5.7%                 7.5%                36.2%                50.6%
     3.004105409                 5.9%                 7.7%                36.9%                49.6%
     4.005561887                14.7%                 1.5%                11.0%                72.9%
     5.006996836                 7.8%                 7.4%                34.9%                49.9%
     6.008456959                 5.5%                 7.2%                35.4%                51.9%
     7.009903367                 5.5%                 7.4%                35.2%                51.9%
     8.011357568                13.0%                 2.0%                12.5%                72.5%
     9.012807708                 5.2%                 7.2%                34.5%                53.1%
    10.014256600                 5.9%                 8.0%                38.1%                47.9%
```

DRAM Energy units(output from rapl-read):
```
Trying /dev/msr interface to gather results

        Listing paramaters for package #0
                Power units = 0.125W
                CPU Energy units = 0.00006104J
                DRAM Energy units = 0.00006104J
                Time units = 0.00097656s

                Package thermal spec: 125.000W
                Package minimum power: 0.000W
                Package maximum power: 0.000W
                Package maximum time window: 0.000000s
                Package power limits are unlocked
                Package power limit #1: 4095.875W for 0.108398s (enabled, clamped)
                Package power limit #2: 4095.875W for 0.032227s (enabled, not_clamped)
        PowerPlane1 (on-core GPU if avail) 0 policy: 16
```

yes, I found missing "model ==" in the code.

**Comment by TomTheBear** [comment]
Thanks for the update.

I added RKL to the Icelake Desktop Uncore logic (CBOX, UBOX and MBOX) and enabled the `TOPDOWN_SLOTS` event. It is not part of your output but it is commonly required for the other TMA metrics, so it's highly likely that it is provided.

No changes required for the RAPL DRAM domain since CPU and DRAM energy units are the same.

**Comment by TomTheBear** [comment]
Have you tried the code from the PR? If it works properly, I can merge it and include it in the upcoming release.

**Comment by edisonchan** [comment]
How can I test with TMA Level 1 ?

**Comment by TomTheBear** [comment]
If you update (pull) from the PR, there should be a `TMA` group now.

Otherwise:
`$ likwid-perfctr -g RETIRING:TMA0,BAD_SPECULATION:TMA1,FRONTEND_BOUND:TMA2,BACKEND_BOUND:TMA3 ...`

**Comment by edisonchan** [comment]
PMC2 and PMC3 not allowed?
```
 likwid-perfctr -C 6 -g TMA sh doit.sh
--------------------------------------------------------------------------------
CPU name:       11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
CPU type:       Intel Rocketlake processor
CPU clock:      3.50 GHz
WARN: Register PMC2 not allowed for event FRONTEND_BOUND (limit TMA2)
WARN: Register PMC3 not allowed for event BACKEND_BOUND (limit TMA3)
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Group 1: TMA
+-----------------------+---------+---------------+
|         Event         | Counter |   HWThread 6  |
+-----------------------+---------+---------------+
|   INSTR_RETIRED_ANY   |  FIXC0  | 2679159138628 |
| CPU_CLK_UNHALTED_CORE |  FIXC1  |  872778413785 |
|  CPU_CLK_UNHALTED_REF |  FIXC2  |  587222488640 |
|     TOPDOWN_SLOTS     |  FIXC3  | 4363892068925 |
|        RETIRING       |   TMA0  |        3.5255 |
|    BAD_SPECULATION    |   TMA1  |        0.8235 |
|     FRONTEND_BOUND    |   PMC2  |       -       |
|     BACKEND_BOUND     |   PMC3  |       -       |
+-----------------------+---------+---------------+

+----------------------+---------------+
|        Metric        |   HWThread 6  |
+----------------------+---------------+
|  Runtime (RDTSC) [s] |      168.1202 |
| Runtime unhalted [s] |      249.0793 |
|      Clock [MHz]     |     5207.9594 |
|          CPI         |        0.3258 |
|          IPC         |        3.0697 |
|      Total Slots     | 4363892068925 |
|     Front End [%]    |  4.583065e-11 |
|    Speculation [%]   |  1.887144e-11 |
|     Retiring [%]     |  1.887144e-11 |
|     Back End [%]     |  6.874597e-11 |
+----------------------+---------------+

```

**Comment by TomTheBear** [comment]
There were typos in the group file. Please try again. I'm currently not sure whether the metrics are ok, I cannot test it, I don't have an Icelake desktop right now.

**Comment by edisonchan** [comment]
```
likwid-perfctr -C 6 -g TMA sh doit.sh
--------------------------------------------------------------------------------
CPU name:       11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
CPU type:       Intel Rocketlake processor
CPU clock:      3.50 GHz
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Group 1: TMA
+-----------------------+---------+---------------+
|         Event         | Counter |   HWThread 6  |
+-----------------------+---------+---------------+
|   INSTR_RETIRED_ANY   |  FIXC0  | 2679160577977 |
| CPU_CLK_UNHALTED_CORE |  FIXC1  |  880429497344 |
|  CPU_CLK_UNHALTED_REF |  FIXC2  |  592902744346 |
|     TOPDOWN_SLOTS     |  FIXC3  | 4402147486720 |
|        RETIRING       |   TMA0  |        3.5137 |
|    BAD_SPECULATION    |   TMA1  |        0.8275 |
|     FRONTEND_BOUND    |   TMA2  |        1.0627 |
|     BACKEND_BOUND     |   TMA3  |        0.5961 |
+-----------------------+---------+---------------+

+----------------------+---------------+
|        Metric        |   HWThread 6  |
+----------------------+---------------+
|  Runtime (RDTSC) [s] |      169.4667 |
| Runtime unhalted [s] |      251.2630 |
|      Clock [MHz]     |     5203.2793 |
|          CPI         |        0.3286 |
|          IPC         |        3.0430 |
|      Total Slots     | 4402147486720 |
|     Front End [%]    |      106.2745 |
|    Speculation [%]   |       82.7451 |
|     Retiring [%]     |      351.3725 |
|     Back End [%]     |       59.6078 |
+----------------------+---------------+

```

106% ?

**Comment by TomTheBear** [comment]
I have to check how you calculate the percentages out of the raw counts. You cannot use the raw counts, you have to do something with them to get to the percentages...

**Comment by edisonchan** [comment]
I think I had not change this part, did you try this on ice lake?

**Comment by TomTheBear** [comment]
The `TMAx` counter code is part of the Icelake logic common for desktop and server chips. The changes in the PR just tell LIKWID to use the same logic on Rocketlake. I didn't do any tests for the `TMA` group, I don't have access to an Icelake system with a working LIKWID setup at the moment.

**Comment by ivan-pi** [comment]
The L2 and L3 groups from ICL are also applicable to Rocket Lake. It would be nice to have a MEM group however, but I'm not sure if the needed counters are available.

I'm trying to determine the bandwidth and operational intensity for a roofline plot. Any suggestions?
