### ISSUE TITLE
segmentation fault in likwid-accessD

### ISSUE THREAD

**Issue by affenwiesel** [RRZE-HPC/likwid#401]
When running likwid-perfctr, I run into the following error:
```
$ likwid-perfctr -e
ERROR - [./src/access_client.c:194] No such file or directory
Exiting due to timeout: The socket file at '/tmp/likwid-2003' could not be
opened within 10 seconds. Consult the error message above
this to find out why. If the error is 'no such file or directoy',
it usually means that likwid-accessD just failed to start.
```
In fact trying to run the access daemon directly yields a segfault:
```
$ likwid-accessD
[1]    1897 segmentation fault  likwid-accessD
```
I am running on wsl2 (Windows Subsystem for Linux) -- may this be the root of the problem?
Other likwid features, e.g., likwid-topology seem to work, though.

**Comment by TomTheBear** [comment]
Windows Subsystem for Linux is not supported. At least I never tried. The problematic part is probably the access to the hardware counters. Not all LIKWID tools use them, mainly `likwid-perfctr` and `likwid-mpirun`.
