### ISSUE TITLE
API: Declare parameters const where applicable

### ISSUE THREAD

**Issue by gueraf** [RRZE-HPC/likwid#41]
Hi Thomas,

I'm currently working on embedding Likwid into a PDE framework (written in C++) to enable profiling of the individual compute kernels. Following common design guidelines most of the output functions of the  generic profiler interface provided by the framework are declared "const". 

In the implementation of these const methods in my Likwid-wrapping profiler I need to call methods from the Likwid API, e.g. `double power_printEnergy(PowerData* data)`. The problem is that the PowerData instance in my case is a member of the profiler, and inside a const method I can only provide a `const PowerData*`, not a `PowerData*` (leaving aside `const_cast` as a dirty solution).

Considering the implementation of [`power_printEnergy`](https://github.com/RRZE-HPC/likwid/blob/a17dbfc8840ff9c497377dacbf89f537e4be08fc/src/includes/power.h#L71) which clearly doesn't modify its arguments (one could even say it would be unexpected if it did) and some other similar examples in the Likwid API, I wanted to ask if it would be OK to explicitly declare these arguments constant in some future version of Likwid.

Please let me know what you think. Thanks.

(I can send a PR for the obvious examples that I encountered if that helps, but wanted to check with you first.)

**Comment by TomTheBear** [comment]
Hi,

I never thought about making the arguments const but of course it is possible for a bunch of functions and probably beneficial. There are quite a few functions where the arguments are not modified in the functions, so it is a big change. Moreover, the whole code has to be checked afterwards where the functions are called internally to create the arguments with the proper type. Also the Lua API needs some care afterwards.

You are welcome to submit a pull request, I check it and see how much work is generated by the change. 

Greetings,
Thomas

**Comment by gueraf** [comment]
Hi Thomas,

thanks for your immediate response. I've just finished a first pass through the API and sent you a PR. All changes should be pretty much straightforward, basically wherever I found an argument of pointer type being tagged as [in] in Doxygen I made the pointer constant. Some of these changes need to be propagated into internal functions, but again this only affects the function signature.

I furthermore added two TODOs to point your attention to two minor points that I stumbled upon, namely a statement which seems to be a noop, and an argument which I think should be marked [out] or [in/out] rather than [in].

Summing this up I think that the change should have no impact on the functionality of the framework. We merely extend a guarantee that is made in the Doxygen documentation to be reflected in the code directly. [Travis](https://travis-ci.org/gueraf/likwid/builds/139455224) still passes, however I have no idea how strong of a statement that is.

Thanks again for consider the change. Please take all the time you need to review it carefully and to decide whether you consider it beneficial.

Best,
Fabian

**Comment by TomTheBear** [comment]
PR merged
