### ISSUE TITLE
Potential error(e.g., deadlock, ill peformance) due to the unreleased lock threadLocks[myCPU]

### ISSUE THREAD

**Issue by jenny-cheung** [RRZE-HPC/likwid#416]
Hi, developers, thank you for your checking. The lock `threadLocks[myCPU]` may not be correctly released if the `results->state != MARKER_STATE_START` satisfies and the control flow goes to the branch listed below. Finally, the method returns with the unreleased lock. `The fix is to insert pthread_mutex_unlock(&threadLocks[myCPU]);`  before returning.

https://github.com/RRZE-HPC/likwid/blob/af9e3c58b98f3521b3e10e0d7d7e6808c43ee246/src/libperfctr.c#L603
https://github.com/RRZE-HPC/likwid/blob/af9e3c58b98f3521b3e10e0d7d7e6808c43ee246/src/libperfctr.c#L608
https://github.com/RRZE-HPC/likwid/blob/af9e3c58b98f3521b3e10e0d7d7e6808c43ee246/src/libperfctr.c#L611

```
int
likwid_markerStopRegion(const char* regionTag)
{
    ...;
    if (use_locks == 1)
    {
        pthread_mutex_lock(&threadLocks[myCPU]);
    }

    cpu_id = hashTable_get(tag, &results);
    thread_id = getThreadID(cpu_id);
    if (results->state != MARKER_STATE_START)
    {
        fprintf(stderr, "WARN: Stopping an unknown/not-started region %s\n", regionTag);
        return -EFAULT;
    }
   ...;
    results->state = MARKER_STATE_STOP;
    if (use_locks == 1)
    {
        pthread_mutex_unlock(&threadLocks[myCPU]);
    }
    return 0;
}
```

Best,

**Comment by TomTheBear** [comment]
Hi, good find. Many thanks. Do you want to open a PR or should I fix it?

**Comment by jenny-cheung** [comment]
I created a PR. Please Check. Thanks!
