### ISSUE TITLE
[BUG] likwid-setFrequencies -reset sets to second last governor

### ISSUE THREAD

**Issue by dr-br** [RRZE-HPC/likwid#433]
**Describe the bug**
`likwid-setFrequencies -reset` sets the governor to the second last one in the list obtained by `likwid-setFrequencies -m` but it should reset to the last one (cf. https://github.com/RRZE-HPC/likwid/wiki/likwid-setFrequencies#resetting-frequencies).

**To Reproduce**
* LIKWID version: `likwid-setFrequencies -- Version 5.2.0 (commit: 233ab943543480cd46058b34616c174198ba0459)`
* OS: `Linux desktop 5.15.0-1-MANJARO #1 SMP PREEMPT Tue Oct 5 12:01:28 UTC 2021 x86_64 GNU/Linux`

**To Reproduce with a LIKWID command**

```
> likwid-setFrequencies -p
Current CPU frequencies:
HWThread 0: governor    schedutil min/cur/max 2.2/3.399154/3.4 GHz Turbo 0
…
HWThread 31: governor    schedutil min/cur/max 2.2/2.19493/3.4 GHz Turbo 0

No support for Uncore frequencies

> likwid-setFrequencies -m
Available governors:
conservative ondemand userspace powersave performance schedutil

> likwid-setFrequencies -reset
Reset to governor performance with min freq. 2.2 GHz and deactivate turbo mode
```

**Comment by TomTheBear** [comment]
I updated the wiki and the Doxygen input. The man page already contained the explanation.

Thanks
