### ISSUE TITLE
[FeatureRequest] signalling stethoscope mode to stop

### ISSUE THREAD

**Issue by iamholger** [RRZE-HPC/likwid#445]
**Is your feature request related to a problem? Please describe.**
We have a parallel application and want to use likwid-perfctr on a
certain phase of the application. We cannot use the marker API
due to the restrictions of omp master.

We are able to infer when the phase in question starts and stops
and would like to use a combination of likwid-pin and likwid-perfctr
for our measurements. 

We did not see the ability of attaching perfctr to a process id so the only
option for us seems to use the stethoscope mode.

Starting the measurement is trivial, but we cannot stop it
at the end of the program phase of interest. We tried
setting a very large stethoscope time and then signalling
perfctr to terminate but that gives no output.

**Describe the solution you'd like**
We would like to be able to signal a long-running perfctr process
to end its measurements  early.

**Describe alternatives you've considered**

**Additional context**

**Comment by iamholger** [comment]
Addendum ---- sending SIGINT to likwid-perfctr seems to do the trick.
What I do is to run pin in the background and perfctr through python.



```
likwid-pin [...]  myapplication & python3 likwidator.py [...]



cat likwidator.py

if __name__ == "__main__":

    import os, sys, subprocess

    # Wait for the program phase to start
    while not os.path.exists("ready"):
        pass

    # Run likwid-perfctr in stethoscope mode for a long time
    import subprocess
    cmd = "likwid-perfctr -g FLOPS_DP -C {} -f -S 1000s -o {}".format(sys.argv[1], sys.argv[2])
    process = subprocess.Popen(args=cmd.split())
    
    # Wait for the program phase to end
    while not os.path.exists("done"):
        pass
    
    # send SIGINT to likwid-perfctr, seems to shutdown gently
    import signal
    process.send_signal(signal.SIGINT)

    os.remove("ready")
    os.remove("done")
```

**Comment by TomTheBear** [comment]
You found the way: [LIKWID catches SIGINT](https://github.com/RRZE-HPC/likwid/blob/master/src/luawid.c#L1928)
I should document that, thanks for the hint.

Is your feature request still required after you discovered the solution? If not, please close it.

**Comment by iamholger** [comment]
Good, so if that is an acceptable way I consider this closed.
Thank you kindly!

**Comment by TomTheBear** [comment]
I added SIGINT to the documentation/wiki for timeline and stethoscope mode
