### ISSUE TITLE
likwid-topology -g crashes for cache sizes not divisible by 2^20 

### ISSUE THREAD

**Issue by gjbex** [RRZE-HPC/likwid#45]
Thanks for the nice work on Likwid, I really like the tool.

On line 337, likwid-topology implicitly assumes that the LLC cache size can be divided by 2^20.

On Broadwell E5-2680 v4, the LLC is 35 MB, which doesn't cause an issue, unless the node is configured to have 4, rather than 2 NUMA domains.  In that case, the division no longer results in an integer, and the format function fails since the format code is '%d'.

It is of course not a big deal, and few people will notice.

**Comment by TomTheBear** [comment]
I think my colleague fixed this issue in https://github.com/RRZE-HPC/likwid/commit/a4daf8074a42f4f183486f07a0d9adacb0197816. The format string is changed to "%.0f".

**Comment by gjbex** [comment]
Many thanks, indeed, I hacked our installed version similarly ('%.1f'), which solves the problem.

Probably the change didn't make it into a release yet, since I was installing from 4.1.1.

Thanks again, Geert Jan Bex

**Comment by TomTheBear** [comment]
No, but we are currently preparing a bugfix release which will include the fix.
