### ISSUE TITLE
Dereferencing 'nodes' after it is deallocated in numa_virtual.c

### ISSUE THREAD

**Issue by ultilambda212** [RRZE-HPC/likwid#458]
On line 51 nodes was allocated.
On line 57 nodes[0].processors was allocated.
On line 70 nodes was freed.
On line 71 nodes[0].processors was freed.
Since nodes was already freed at 70, nodes[0].processors is being dereferenciated on line 71, so the order for free should be the other way.

**Comment by TomTheBear** [comment]
Good find, Thanks.
