### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by xyh01** [RRZE-HPC/likwid#462]
In section Build LIKWID with perf_event backend instead of native access of document Build, are may need to be changed to is: _An example for this are the different CPU core frequencies in turbo mode (likwid-powermeter -i)._

**Comment by TomTheBear** [comment]
I don't understand what you want to change. The exact sentence is part of the [build with perf_event](https://github.com/RRZE-HPC/likwid/wiki/Build#build-likwid-with-perf_event-backend-instead-of-native-access) section, so how should it be changed?

**Comment by xyh01** [comment]
I wondered if _are_ should be changed to _is_ before. Now I find this is an inverted sentence.
Thanks for your reply!

**Comment by TomTheBear** [comment]
I changed the sentence to
> The different CPU core frequencies in turbo mode (`likwid-powermeter -i`) serve as an example."

to avoid any future confusion
