### ISSUE TITLE
[BUG] likwid-bench uses half of the cores with hyperthreading, non-standard core numbering

### ISSUE THREAD

**Issue by drembaru** [RRZE-HPC/likwid#463]
**Description**

likwid-bench does not use all (physical) cores of the node/socket but instead uses half of the physical cores with hyperthreading. I might of course do something wrong but I have two indicatives for this behaviour:

1. I observe which cores are busy in htop
2. I compare the measured performance with the theoretical peak performance

Below I describe how I came to the assumption that only half  the (physical) cores are used. This might be related to #46, at least I have the same non-standard core numbering on that machine. There is of course the other option, that I'm simply missusing the likwid-bench command.

**To Reproduce**

Hardware: Dual socket Intel(R) Xeon(R) Gold 6230R (26 cores)  with turbo turned off. The full node theoretical peak performance should be `2.1(clockrate)*2(fma)*8(simd)*2(fma units)*26(cores)*2(sockets)=3.49TFlops/s`

LIKWID command:

* `likwid-bench -t peakflops_avx512_fma -w N:1040kB:104` reports 3.49 TFlops/s, uses all cores in htop
* `likwid-bench -t peakflops_avx512_fma -w N:520kB:52` reports 1.73 TFlops/s, uses all cores with even numbers in htop (*)
* `likwid-bench -t peakflops_avx512_fma -w S0:260kB:26` reports 0.87 TFlops/s, uses half the cores with even numbers in htop
* `likwid-bench -t peakflops_avx512_fma -w S0:520kB:52` reports 1.73 TFlops/s, uses all cores with even numbers in htop (*)
* `likwid-bench -t peakflops_avx512_fma -w S1:520kB:52` reports 1.73 TFlops/s, uses all cores with odd numbers in htop

 The lines marked with (*) lead to my assumption. I attached all the output of the benchmark commands. Unfortunately I can't give evidence for the behavior I saw in htop.

Related information:
* likwid with access daemon from commit aee61f19fe78047fc2222be037f586dd46734e23 (2nd of May)
* Operating system: Ubuntu 20.04.2
* Output of `likwid-toplogy -V 3` is attached

If you need any more information I'm happy to help.

A big thank for developing likwid,
best regards,
René

[likwid-topology.txt](https://github.com/RRZE-HPC/likwid/files/8677324/likwid-topology.txt)
[lscpu.txt](https://github.com/RRZE-HPC/likwid/files/8677325/lscpu.txt)
[lstopo.txt](https://github.com/RRZE-HPC/likwid/files/8677326/lstopo.txt)
[peakflops_avx512_fma_N_520_52.txt](https://github.com/RRZE-HPC/likwid/files/8677327/peakflops_avx512_fma_N_520_52.txt)
[peakflops_avx512_fma_N_1040_104.txt](https://github.com/RRZE-HPC/likwid/files/8677328/peakflops_avx512_fma_N_1040_104.txt)
[peakflops_avx512_fma_S0_260_26.txt](https://github.com/RRZE-HPC/likwid/files/8677329/peakflops_avx512_fma_S0_260_26.txt)
[peakflops_avx512_fma_S0_520_52.txt](https://github.com/RRZE-HPC/likwid/files/8677330/peakflops_avx512_fma_S0_520_52.txt)
[peakflops_avx512_fma_S1_520_52.txt](https://github.com/RRZE-HPC/likwid/files/8677331/peakflops_avx512_fma_S1_520_52.txt)

**Comment by TomTheBear** [comment]
Thanks for the issue (with enough explanation and files). I think there is some misuse that I want to clarify before looking at your supplied files.

`likwid-bench` uses the unsorted list of hardware threads, so if you specify `N` the list is likely
`<phys0> <smt0> <phys1> <smt1> ...`
Check with `likwid-bench -p`

When you specify a number of threads inside the domain, `likwid-bench` starts at the beginning and takes as many hardware threads as needed. If you want to skip the SMT threads, you have to tell `likwid-bench` to do so: `N:<size>:<nThreads>:1:2` with `chunksize=1` and `stride=2` (for SMT2).

Under the hood, it uses the expression syntax available also for the other LIKWID tools, so you can try:
```
$ likwid-pin -E:N:104
<all hardware threads including SMT>
$ likwid-pin -E:N:52:1:2
<all physical hardware threads>
$ likwid-pin -E:S0:52
<all hardware threads including SMT at socket 0>
$ likwid-pin -E:S0:26:1:2
<all physical hardware threads at socket 0>
```

**Comment by drembaru** [comment]
This does indeed fix the issue. Thanks a lot for the quick reply :)

**Comment by TomTheBear** [comment]
Please remember, if you are using a system with more advanced SMT like SMT4 (Marvell Thunder X2, Intel Xeon Phi) or SMT8 (IBM POWER), you have to adjust the `chunksize` accordingly.

**Comment by drembaru** [comment]
Sorry for bringing this up again. I assume I have another misuse issue so I did not want to open a false issue again. If it is an issue (or if you prefer it, to make it easier to find) I would of course do that. Any help would be very much appreciated :)

I have a similar issue on a different machine (Milan, Zen3, 2x64 cores) with likwid-mpirun. I want to use both sockets of the node and if I just use

```
likwid-mpirun -np 128 -m -g MEM1 ./a.out
```

it will use half of the cores with hyperthreading on both sockets. I can avoid this problem by using

```
likwid-mpirun -np 128 --dist 1:close -m -g MEM1 ./a.out
```

but then one of the sockets does not report memory traffic.

PS: Is there a way of running on all cores of a single socket with likwid-mpirun? I could not find a way to do that.

Once again: Thanks a lot for all the effort :+1:
