### ISSUE TITLE
[BUG] likwid-mpirun using half the physical cores with hyperthreading and only one socket reports memory bandwidth

### ISSUE THREAD

**Issue by drembaru** [RRZE-HPC/likwid#464]
**Description**

I have two issues that might or might not be related:

1. likwid-mpirun is using half the physical cores with multithreading instead of using all physical cores.
2. The memory group reports only the memory bandwith for one of the two sockets
 
I have the following indications for that:
- Observing busy cores in htop
- Not reaching the expected performance for an executable where I should reach around ~50% of machine peak performance
- Looking at the output of the memory groups shows only one socket reporting (Sum=Max)
- Comparison to a different machine where everything works as expected

Below I describe the hardware and the commands I used.

**To Reproduce**

Problem Setup:
- There are flops and memory transfers happening (code comes from finite element simulation)
- Problem size around 40MB per rank

Hardware:
- Dual socket AMD EPYC 7713 64-Core, turbo mode turned off, NPS1 mode, theoretical peak: 4.096 TFLOPs for the full node
- Commands are directly run on the machine
- No irregularities found with `likwid-topology`

Commands for hyperthreading issue:
- `likwid-mpirun -nperdomain S:64 -np 128 -m -g FLOPS_DP ./a.out` Half of the physical cores with hyperthreading, reported performance: `1.205713e+06`
- `likwid-mpirun -np 128 -m -g FLOPS_DP ./a.out` Half of the physical cores with hyperthreading, reported performance: `1.205166e+06`
- `likwid-mpirun --dist 1:close -np 128 -m -g FLOPS_DP ./a.out` All physical cores, reported performance: `2.163329e+06`
- `likwid-mpirun -nperdomain S:64 --dist 1:close -np 128 -m -g FLOPS_DP ./a.out`Half of the physical cores with hyperthreading, reported performance: `1.169516e+06`
- `mpirun -np 128 ./a.out` All physical cores but not pinned

Commands for hyperthreading issue:
- `likwid-mpirun --dist 1:close -np 128 -m -g MEM1 ./a.out` only one socket reports memory bandwidth
- `likwid-mpirun -np 128 -m -g MEM1 ./a.out` only one socket reports memory bandwidth

Below I attached the full output of all commands.

**Likwid Version**

I tried to pull and rebuild likwid but I am not sure if it updated everything correctly. `likwid-mpirun --version` shows:
```
likwid-mpirun -- Version 5.2.0 (commit: 233ab943543480cd46058b34616c174198ba0459)
```
which does not seem to be the newest commit.

Again it is entirely possible that I am just misusing likwid. All help is appreciated and thanks for the good work :). I'm happy to provide more information if necessary.

Best regards,
René

[likwid-mpirun-dist-flops-dp.txt](https://github.com/RRZE-HPC/likwid/files/8710460/likwid-mpirun-dist-flops-dp.txt)
[likwid-mpirun-dist-mem1.txt](https://github.com/RRZE-HPC/likwid/files/8710461/likwid-mpirun-dist-mem1.txt)
[likwid-mpirun-normal-flops-dp.txt](https://github.com/RRZE-HPC/likwid/files/8710462/likwid-mpirun-normal-flops-dp.txt)
[likwid-mpirun-nperdomain-flops-dp.txt](https://github.com/RRZE-HPC/likwid/files/8710464/likwid-mpirun-nperdomain-flops-dp.txt)
[likwid-mpirun-regular-mem1.txt](https://github.com/RRZE-HPC/likwid/files/8710465/likwid-mpirun-regular-mem1.txt)

[likwid-topology.txt](https://github.com/RRZE-HPC/likwid/files/8710466/likwid-topology.txt)
[lscpu.txt](https://github.com/RRZE-HPC/likwid/files/8710467/lscpu.txt)
[lstopo.txt](https://github.com/RRZE-HPC/likwid/files/8710468/lstopo.txt)

**Comment by TomTheBear** [comment]
Thanks for the outputs. Unfortunately, I need them with the `-d` CLI switch for debugging output.

One first finding are the lines:
```
INFO: You are running LIKWID in a cpuset with 128 CPUs. Taking given IDs as logical ID in cpuset
INFO: You are running LIKWID in a cpuset with 128 CPUs. Taking given IDs as logical ID in cpuset
```

Please try again with `export LIKWID_IGNORE_CPUSET=1`. Maybe you have to forward it:
```
$ likwid-mpirun -e LIKWID_IGNORE_CPUSET=1 ...
```

**Comment by drembaru** [comment]
This seems to indeed solve both issues. Likwid now uses all physical cores and two cores report memory bandwidth. I have not yet rerun all simulations and compared to the other machine, but I assume that everything should be fine :)

**Comment by TomTheBear** [comment]
Please be aware that this setting should not be used by default. If you have a system with more separate compute jobs by different users on a node, each properly pinned to a distinct cpuset, you don't want to ignore these boundaries and maybe affect the other users' runs.

Configuration of clusters and/or batch systems are so different between centers that a *works everywhere* `likwid-mpirun` is not achievable.

If you still have issues with it, feel free to re-open the issue.
