### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by carstenbauer** [RRZE-HPC/likwid#474]
😄 

As you know, I'm coming from a LIKWID.jl perspective. The situation is as follows:

* To use `@nvmon` one needs https://github.com/RRZE-HPC/likwid/pull/473 (essentially current master + nvmon fix). But there one hits https://github.com/JuliaPerf/LIKWID.jl/issues/41 and can't use `@perfmon_marker`.
* To use `@perfmon_marker` one can use the latest release (v5.2) but than one can't use `@nvmon`....

That's ... unfortunate. It'd be great to, if possible, get a release where I can support both `@nvmon` and `@perfmon_marker`. In particular because LIKWID.jl might get some attention at the end of July due to my JuliaCon talk 🙂

Of course, I can understand that you need to consider other things as well and that you are pretty busy. Just wanted to put this out there 🙂 

PS: I also stalled https://github.com/JuliaPackaging/Yggdrasil/pull/4913 because I want to use the hwloc and `ldd --version` patches https://github.com/RRZE-HPC/likwid/commit/3a79b059c57f03949a74977b654a416b5ed51fcf and https://github.com/RRZE-HPC/likwid/commit/d6bbdcf2a84210d9c1dd6952d1ae533ae36bff07 on master.

**Comment by TomTheBear** [comment]
New release: https://github.com/RRZE-HPC/likwid/releases/tag/v5.2.2

Attempt to make LIKWID installation relocatable: #480 (work-in-progress)
