### ISSUE TITLE
[BUG] Event counter only have 0 as value when using marker API

### ISSUE THREAD

**Issue by reynozeros** [RRZE-HPC/likwid#476]
When I measure my application with ```likwid-perfctr``` it works fine when I do not use the ```-m``` option.
But when using the markers, all event counters have 0 as value, except the ones on the main thread and except for the ```CPMC``` registers for the L3 cache, those work fine in all cases.

likwid-perfctr -V 3 -m -g L3 -C 0-127 -s 0xF python3 CRM_run.py

likwid (v5.2) is built with perf event support from the cloned github repository together with the patch for the missing pin mask.
OS: Rocky Linux 8.5 (Green Obsidian)
HW: 2x AMD EPYC 7702 64-Core Processor
The application uses MPI with openMP.

Output:
[likwid_threading.txt](https://github.com/RRZE-HPC/likwid/files/9258527/likwid_threading.txt)

**Comment by TomTheBear** [comment]
Can you please try the test STREAM code to see whether there is a problem with the system itself or LIKWID has problems with your code:

```
$ cd $LIWKID_SRC/test
$ make streamGCC
$ likwid-perfctr -C 0-127 -g L3 -V 3 -m ./streamGCC
```

I never used Python with MPI and OpenMP under the hood, so I don't know how it behaves. It seems to start its own threads (`-s 0xF`). If it starts a process (`multiprocessing` module) and runs the application in there, the behavior of LIKWID is totally in line with that. LIKWID with perf_event tries to count only for a specific process (from your logs: `perf_event_open: cpu_id=108 pid=2620262 flags=0`) for hwthread-local events (`FIXC` and `PMC` countes). This is not possible with Uncore events (`CPMC` counters), so there you get the counts for all processes.

What is the value in `/proc/sys/kernel/perf_event_paranoid`?

**Comment by reynozeros** [comment]
```streamGCC``` works without issue.
The ```perf_event_paranoid``` value is 0.
I'm not sure if it would help to execute ```run.py``` directly, but I can't get it to work with the first line of it being ```#!/usr/bin/env python```. Running it directly without likwid, it works. With likwid I always get the error ```Failed to execute command: run.py```.
Is there a way around the process binding of perf_event?

**Comment by TomTheBear** [comment]
Unfortunately, I somehow destroyed my own logic in the last years. The plan was to use process binding for perf_event only with higher paranoid values where it is required and use the count everything mode otherwise. LIKWID's common ways to read the counters (AccessDaemon, direct mode) measure everything, so I wanted that to be in line for all modes.

The easiest way to try it out is probably this:
```
$ cp $(which likwid-perfctr) .
$ edit likwid-perfctr
$ ./likwid-perfctr ...
```
snippet to remove (around line 150)
```
if config["daemonMode"] == -1 then
    execpid = true
end
```

Another thing you could try would be to use `likwid-perfctr --perf-pid 1 ...`.

The execution of `likwid-perfctr` and `likwid-perfctr+MarkerAPI` is completely different. In the first case, everything is controlled by `likwid-perfctr` while in the second case, the user application has the control.

LIKWID uses `execvp` to start the processes, there is no shell involved which commonly resolves the Shebang.

**Comment by reynozeros** [comment]
The thing with ```--perf-pid``` doesn't seem to work, ```likwid-perfctr``` says: ```Invalid commandline option -perf-pid```.
But with removing these 3 lines, all works perfectly, thank you.
I think I will have to live with this little hack for now. Or would it be possible to create a command line flag for that? Or is that what ```--perf-pid``` would do?

**Comment by TomTheBear** [comment]
Because the option is called `--perfpid`.

**Comment by reynozeros** [comment]
Is there a way for this commandline option to work with ```likwid-mpirun```?
If not, I will just comment out these three lines.

**Comment by TomTheBear** [comment]
No because when `likwid-mpirun` runs, there are not PIDs that could be added to `--perfpid`. It might be even a different host. The PIDs exist after/while the underlying `mpiexec`/`srun` is executing `likwid-perfctr`.

**Comment by TomTheBear** [comment]
Maybe this one will help: https://github.com/RRZE-HPC/likwid/commit/185b4df6915ed65c27365981e0692213599c4025

**Comment by reynozeros** [comment]
Yes, this seems to fix it, thanks a lot.
