### ISSUE TITLE
[Build] unexpected operator

### ISSUE THREAD

**Issue by edisonchan** [RRZE-HPC/likwid#477]
**Which version do you want to build?**
master

**Which architecture do you want to build for?**
- [ x] x86_64

**To Reproduce**
make

**Output log**
make

> /bin/sh: 1: [: -lt: unexpected operator
> ===>  GENERATE HEADER GCC/perfmon_a15_events.h
> ===>  GENERATE HEADER GCC/perfmon_a57_events.h
> ....
> ===>  COMPILE  GCC/loadData.o
> ===>  ENTER  /home/edison/Downloads/likwid/ext/hwloc
> /bin/sh: 1: [: -lt: unexpected operator
> ===>  ENTER  /home/edison/Downloads/likwid/ext/lua
> /bin/sh: 1: [: -lt: unexpected operator
> ===>  CREATE SHARED LIB  liblikwid.so
> ===>  CREATE LIB  liblikwidpin.so
> make[1]: Entering directory '/home/edison/Downloads/likwid/src/pthread-overload'
> /bin/sh: 1: [: -lt: unexpected operator
> make[1]: Leaving directory '/home/edison/Downloads/likwid/src/pthread-overload'
> ===>  ADJUSTING  likwid-perfctr
> ...
> ===>  ENTER  bench
> /bin/sh: 1: [: -lt: unexpected operator
> ===>  COMPILE C GCC/allocator.o
> ===>  COMPILE C GCC/barrier.o
> 

OS: Ubuntu 22.04 with kernel 5.19
make --version: 

> GNU Make 4.3
> Built for x86_64-pc-linux-gnu
> Copyright (C) 1988-2020 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.

**Comment by TomTheBear** [comment]
Thanks for reporting. I added some problem to the build system which happens not all the time. I'm already searching.
