### ISSUE TITLE
Problem using perfctr, result always zero

### ISSUE THREAD

**Issue by sebwolf-de** [RRZE-HPC/likwid#479]
**Describe the bug**
When I use perfctr with the marker API, I only get measurement results for the first thread, but zeros for all other threads.

**To Reproduce**
* The problem happens in a rather large code basis (https://github.com/SeisSol/SeisSol/tree/dr/performance).
* likwid-perfctr -- Version 5.2.0 (commit: 233ab943543480cd46058b34616c174198ba0459) (loaded as a module)
* SLES
* OpenMP, MPI (not relevant here, I am only interested in single node performance)
* Marker API (CPU)

**To Reproduce with a LIKWID command**
Please supply the output of the command with `-V 3` added to the command:
* `likwid-perfctr -C S0:0-7 -g FLOPS_DP -m -V 3 ./SeisSol parameters.par` [out.txt](https://github.com/RRZE-HPC/likwid/files/9300357/out.txt)

Please supply the output of the command with `-d` added to the command line:
* likwid-mpirun (n/a)

**Additional context**
I would like to measure the performance of a small kernel, which is deep in the source tree. 
My main.cpp looks like:
```
int main() {
  LIKWID_MARKER_INIT;
#pragma omp parallel
  {
    LIKWID_MARKER_THREADINIT;
    LIKWID_MARKER_REGISTER("PrecomputeStress");
  }
  compute();
  LIKWID_MARKER_STOP;
}
```
`compute()` then calls several routines and the part, which I would like to measure, looks like:
```
#pragma omp parallel for schedule(static)
  for(....) {
    // some stuff
    LIKWID_MARKER_START("PrecomputeStress");
    precomputeStress();
    LIKWID_MARKER_STOP("PrecomputeStress");
    // some other stuff
  }
```
I saw the fix from #476, unfortunately I can not install likwid on my own. When I use likwid-perfctr together with likwid-bench, everything works as expected. Is my way to instrument my application wrong?

**Comment by TomTheBear** [comment]
Hi, your instrumentation looks almost right. Just use `LIKWID_MARKER_CLOSE` instead of `LIKWID_MARKER_STOP` after the `compute()` call.

The call to `LIKWID_MARKER_THREADINIT` is optional.

**Comment by sebwolf-de** [comment]
Hi, it is actually `LIKWID_MARKER_CLOSE` in the main file. This just flipped in, as I was simplifying the code ;-)
When I remove the threadinit, nothing changes.

**Comment by sebwolf-de** [comment]
Interestingly, thread 1 collects some data, and thread 0 reports a unhalted runtime of 1.4e10 seconds, but I did not wait 443 years for this result :D
```
+----------------------+---------------------+------------+------------+------------+------------+------------+------------+------------+
|        Metric        |      HWThread 0     | HWThread 1 | HWThread 2 | HWThread 3 | HWThread 4 | HWThread 5 | HWThread 6 | HWThread 7 |
+----------------------+---------------------+------------+------------+------------+------------+------------+------------+------------+
|  Runtime (RDTSC) [s] |              0.0005 |     0.0005 |     0.0004 |     0.0004 |     0.0004 |     0.0004 |     0.0004 |     0.0004 |
| Runtime unhalted [s] |        1.369651e+10 |     0.0112 |          0 |          0 |          0 |          0 |          0 |          0 |
|      Clock [MHz]     |           5387.2850 |  2370.1458 |      -     |      -     |      -     |      -     |      -     |      -     |
|          CPI         |              0.0155 |    23.6189 |      -     |      -     |      -     |      -     |      -     |      -     |
|     DP [MFLOP/s]     |        5.938957e+19 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
|   AVX DP [MFLOP/s]   |        4.327985e+19 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
|  AVX512 DP [MFLOP/s] |        4.327985e+19 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
|   Packed [MUOPS/s]   |        1.077989e+19 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
|   Scalar [MUOPS/s]   | 5369908652219977728 |          0 |          0 |          0 |          0 |          0 |          0 |          0 |
|  Vectorization ratio |             66.7494 |      -     |      -     |      -     |      -     |      -     |      -     |      -     |
+----------------------+---------------------+------------+------------+------------+------------+------------+------------+------------+
```

**Comment by TomTheBear** [comment]
I would recommend to split the worksharing loop:
```
#pragma omp parallel
{
  LIKWID_MARKER_START("PrecomputeStress");
# pragma omp for schedule(static)
  for(....) {
    // some stuff
    precomputeStress();
    // some other stuff
  }
  LIKWID_MARKER_STOP("PrecomputeStress");
}
```
This region will contain the `some stuff` and `some other stuff` as well but greatly reduces the overhead.

From the output, everything looks fine. All 8 hardware threads are read but perf_event does not return any data (for the PID). Unfortunately, you are using a buggy version of LIKWID but since it's perf_event, you can also install a recent version in your home directory, no root permissions required. 
Morever, since you mentioned the issue #476, is your `/proc/sys/kernel/perf_event_paranoid` level also 0? Are you sure there is no daemon running that limits perf_event access like PCP?

**Comment by sebwolf-de** [comment]
The output, I have attached was with the preinstalled version on our cluster. I'll give 5.2.2 a try.

**Comment by sebwolf-de** [comment]
I get this error `likwid-perfctr:160: attempt to call a nil value (field 'perf_event_paranoid')` at the startup of likwid-perfctr for v5.2.2.
I did a git bisect from v5.2.2 backwards and found that this commit breaks likwid-perfctr for me:185b4df6915ed65.
One commit earlier (i.e. ecabe651), I can run likwid-perfctr, but the original problem persists.

**Comment by TomTheBear** [comment]
Did you do a `make distclean` after switching the branches? It seems the `likwid.lua` was not updated.

**Comment by sebwolf-de** [comment]
Thanks for your support and your patience. After a `make distclean`, I can use v5.2.2 and get the expected results!
