### ISSUE TITLE
Issue of likwid-perfctr Command with '-t' Option

### ISSUE THREAD

**Issue by Sanghyun-Hong** [RRZE-HPC/likwid#48]
Hi,

I'm collecting performance counter values using _likwid-perfctr_ command with -t option. Here is the command that I tried (since my computer has four CPUs; N:0-3):
`likwid-perfctr -c N:0-3 -g BRANCH -t 2s`

However, the output that I could get is very different from the output at the _Wiki_ page. First of all, it just stops after two seconds, and, second, anything appeared at the command line (the below is all I have):
`--------------------------------------------------------------------------------`
`# CORES: 0|1|2|3`
` `
`--------------------------------------------------------------------------------`

Could you tell me what's wrong with the _likwid-perfctr_?

Best,
SH.

**Comment by TomTheBear** [comment]
There is a small bug in likwid-perfctr when using it in timeline mode without an executable.

In the meantime, just add an executable like `sleep`. 

Greetings,
Thomas
