### ISSUE TITLE
[Build] Issue with ARMv8 Preprocessor Guards

### ISSUE THREAD

**Issue by OoJJBoO** [RRZE-HPC/likwid#481]
While trying to compile likwid 5.2.2 on a Raspberry Pi4 using either the GCCARMv7 or GCCARMv8 compiler options I encountered an issue regarding the checks used throughout the code: 

It looks like the code most of the time looks at `__ARM_ARCH_8A` to check if we are building using an ARMv8 compiler. But at least my version of GCC 10.4.0 built from source seems to use `__ARM_ARCH_8A__` instead. This, I think, causes the build to try to make x86 code which then causes compilation errors. The first encountered file where this is the case is `includes/cpuid.h` which results in:

```
COMPILE  GCCARMv7/frequency_uncore.o
In file included from ./src/includes/frequency.h:41,
                 from ./src/frequency_uncore.c:42:
./src/frequency_uncore.c: In function ‘freq_setUncoreFreqMin’:
./src/includes/cpuid.h:48:5: error: impossible constraint in ‘asm’
   48 |     __asm__ volatile(".ifnc %%ebx,%3 ; movl  %%ebx,%3 ; .endif  \n\t" \
      |     ^~~~~~~
./src/includes/frequency.h:49:5: note: in expansion of macro ‘CPUID’
   49 |     CPUID(eax,ebx,ecx,edx);
      |     ^~~~~
make: *** [Makefile:302: GCCARMv7/frequency_uncore.o] Error 1
```

When replacing every instance of `__ARM_ARCH_8A` inside the source code with `__ARM_ARCH_8A__` these errors do not appear. I did not thouroughly investigate if I broke anything doing that, but the resulting ARMv7 installation (at least the supported parts of it) seems to work fine. I could not test ARMv8 yet, since I can not use the default `-mabi=lp64` compiler option set in `make/include_GCCARMv8` which looks to not be supported on this system and changing it results in a linker error.

---

**Which version do you want to build?**
likwid 5.2.2 (latest stable release as of now)

**Which architecture do you want to build for?**
- [ ] x86_64
- [x] ARMv8
- [ ] POWER9
- [ ] Nvidia GPUs
- [ ] x86 (32 bit)
- [x] ARMv7
- [ ] POWER8

**To Reproduce**
- set compiler option to either GCCARMv7 or GCCARMv8
- set used compiler to GCC 10.4.0 built from source with ARMv8 target

**Comment by TomTheBear** [comment]
Thanks for the report. The architecture define is often difficult because different compilers expert different names (as you experienced).
The files in `make` are just working ones for me, you are free to change them. During my times with RasPi systems, I realized, it depends on the OS you install. While Raspbian is commonly installed as a 32bit OS and therefore should use `GCCARMv7`, other OS are often 64bit and therefore should use `GCCARMv8`. You could try by adding `-D__ARM_ARCH_8A__` to the `DEFINES` section. The linking error could be the result of a 64bit build on a 32bit OS.

I don't have access to a RasPI right now, but I try to check it on a different ARM system.

**Comment by OoJJBoO** [comment]
Thanks for the quick reply, I will look into that later!

**Comment by OoJJBoO** [comment]
Adding the appropriate definition to the `DEFINES` section, so `-D__ARM_ARCH_7A__` in my case, indeed works, thanks again!

But this of course does not change that everyone using a compiler that defines `__ARM_ARCH_8A__` and not `__ARM_ARCH_8A` will most likely encounter this issue when building, since most (some of them actually already look for both) source files right now only check for the latter.

If it would be of any help I could create a small PR adding additional checks for the former variant since I've already done that locally for testing. Alternatively, maybe you could consider adding the appropriate definitions to the `make/include_GCCARMv7.mk` and `make/include_GCCARMv8.mk` files? I am of course by no means an expert here, so I do not know if there are reasons to not do one or both options. I just wanted to ask in case this could make things a little bit easier for future users.

**Comment by TomTheBear** [comment]
Thanks for the confirmation. I don't see a problem when both architecture strings are defined in the `make/include_*.mk` files. Do you want to submit a PR for that? Or should I do it?

**Comment by OoJJBoO** [comment]
Just created one! #482
