### ISSUE TITLE
Support for AMD Ryzen and EPyC Zen 4 Architecture

### ISSUE THREAD

**Issue by sbates130272** [RRZE-HPC/likwid#493]
**Why do you need support for this specific architecture?**

Now that Zen4 based Ryzen processors are available it would be great to add support to likwid. 

**Which architecture model, family and further information? CPU or accelerator? **

Zen4 for both Ryzen and EPyC (when it becomes available). 
**Is the documentation of the hardware counters publicly available?**

I do not know. 

**Are there already any usable tools (commercial or open-source)?**

There is an AMD tool that I know works for EPyC. Not sure it supports Zen4 nor if it works for Ryzen.

**Comment by TomTheBear** [comment]
https://www.amd.com/en/support/tech-docs/processor-programming-reference-ppr-for-amd-family-19h-model-11h-revision-b1
