### ISSUE TITLE
Likwid tests in OpenHPC started to fail with 5.2.2

### ISSUE THREAD

**Issue by adrianreber** [RRZE-HPC/likwid#494]
We upgraded likwid in OpenHPC to 5.2.2 and now our internal test suite produces errors:
```
1..2
  not ok 1 [perf-tools/likwid] C marker API under resource manager (slurm/gnu12)
  # (from function `run_serial_binary' in file ./common/functions, line 216,
  #  in test file rm_execution, line 25)
  #   `run_serial_binary ./run_c.sh' failed with status 143
  # INFO: You are running LIKWID in a cpuset with 32 CPUs. Taking given IDs as logical ID in cpuset
  # --------------------------------------------------------------------------------
  # CPU name:	Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
  # CPU type:	Intel Xeon Broadwell EN/EP/EX processor
  # CPU clock:	2.19 GHz
  # --------------------------------------------------------------------------------
  # WARN: Region example was already started
  # WARN: Stopping an unknown/not-started region example
  # srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
  # slurmstepd: error: *** STEP 421.0 ON c1 CANCELLED AT 2022-10-28T08:02:27 DUE TO TIME LIMIT ***
  # srun: error: c1: task 0: Terminated
    duration_ms: 90.533
  not ok 2 [perf-tools/likwid] FORTRAN marker API under resource manager (slurm/gnu12)
  # (from function `run_serial_binary' in file ./common/functions, line 216,
  #  in test file rm_execution, line 34)
  #   `run_serial_binary ./run_f90.sh' failed with status 143
  # INFO: You are running LIKWID in a cpuset with 32 CPUs. Taking given IDs as logical ID in cpuset
  # --------------------------------------------------------------------------------
  # CPU name:	Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz
  # CPU type:	Intel Xeon Broadwell EN/EP/EX processor
  # CPU clock:	2.19 GHz
  # --------------------------------------------------------------------------------
  # Thread 0 sleeps now for 2 seconds
  # Thread 1 sleeps now for 2 seconds
  # WARN: Region example was already started
  # Thread 0 wakes up again
  # Region example measures 3 events, total measurement time is     2.000
  # The region was called 1 times
  # Event 1: 0.5774000E+04
  # Event 2: 0.3088700E+05
  # Event 3: 0.5308600E+05
  # WARN: Stopping an unknown/not-started region example
  # srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
  # slurmstepd: error: *** STEP 422.0 ON c2 CANCELLED AT 2022-10-28T08:03:57 DUE TO TIME LIMIT ***
  # srun: error: c2: task 0: Terminated
    duration_ms: 90.094
```
Full log at: http://test.openhpc.community:8080/job/2.x/job/(2.6)%20-%20(rocky8.6,x86_64)%20(warewulf+slurm)%20(fabric=ib)/lastBuild/testReport/junit/UserLevelTests/LIKWID/_perf_tools_likwid__C_marker_API_under_resource_manager__slurm_gnu12_/

We are running likwid tests like this:
https://github.com/openhpc/ohpc/blob/2.x/tests/perf-tools/likwid/tests/run_c.sh
https://github.com/openhpc/ohpc/blob/2.x/tests/perf-tools/likwid/tests/run_f90.sh

Any ideas what we are doing wrong? I cannot reproduce the failure in a local VM.

**Comment by TomTheBear** [comment]
As far as I can see, there are more threads started by the application as requested (`-C 0` in your scripts but `Thread 0 sleeps now for 2 seconds` **AND** `Thread 1 sleeps now for 2 seconds`). Since LIKWID does not overwrite user settings like `OMP_NUM_THREADS`, the problem could be `OMP_NUM_THREADS=2` in the environment, so both application threads get pinned to hardware thread `0`. I heard that SLURM changed some default behaviors in the recent versions, maybe it is related to that. Or some left overs from previous runs that's why you cannot reproduce it locally when running only LIKWID's tests?

**Comment by adrianreber** [comment]
Thanks for your answer. We will look into that direction and let you know if we found a solution.

**Comment by TomTheBear** [comment]
If you want me to help, I need the output of a `likwid-mpirun` with the `-d` CLI switch. I checked the changes to `likwid-mpirun` vom 5.2.1 to 5.2.2 and they are minimal. Mainly this commit to sanitize values after calculations: https://github.com/RRZE-HPC/likwid/commit/574566d7ba427ee6e6f18d853f7a16dc98e504a9 . It might be related to a changes skip mask for your setup but this is rarely a reason for such an error.

**Comment by adrianreber** [comment]
We found a solution thanks to your help. https://github.com/openhpc/ohpc/commit/269b7bde332f0ea5ca0c2292584eedd73e4de637

Closing this as it is solved for us. Thanks a lot once more.
