### ISSUE TITLE
[BUG] Output file of likwid-perfctr in timeline mode is always empty

### ISSUE THREAD

**Issue by MoritzBrueckner** [RRZE-HPC/likwid#512]
**Describe the bug**
Hi, first of all, I'm not completely sure whether this is actually a LIKWID bug or a problem with the way I call/use LIKWID, but after spending many hours trying different commands, reading the wiki and parts of the source code, I'm pretty much out of ideas.

When using `likwid-perfctr` in timeline mode with the `--output` parameter, the specified output file is created, but always empty. The logs show some error messages which however seem to be related to RAPL (which if I understand correctly is only related to measuring energy consumption, which I don't need to measure) and in fact look like the actual performance counter collection takes place normally.

Log file generated by a very short test run:
[likwid.log](https://github.com/RRZE-HPC/likwid/files/10609102/likwid.log)

**To Reproduce**
* LIKWID command and/or API usage
  ```bash
  likwid-perfctr --verbose 3 -c N:0-47 -g MEM -t 500ms --output likwid.txt > likwid.log
  ```
  This is not the actual command I'm using for my use case, but I can still reproduce the issue with this command.

  I'm running the command within a SLURM job on a cluster, and I've taken care of disabling the cluster's own performance monitoring (unless the SLURM parameter mentioned in my cluster's wiki is wrong, I don't know of any way to actually _verify_ whether the parameter works). The same issue also happens if I call likwid outside of a SLURM job, but in that case I think the system's own performance monitoring is still active. The logs pretty much look the same in that case.

  If I choose a different output file format to use one of the included filters (e.g. json), the filter fails with an exception because it doesn't expect the original output file to be empty. Even if my issue is not caused by LIKWID, I guess this could be improved by displaying a more insightful error message.

  Exception when targeting .json:
  ```python
  Traceback (most recent call last):
     File "/opt/likwid/share/likwid/filter/json", line 141, in <module>
    for elems in tables[groups[0]]["Raw"]:
  IndexError: list index out of range
  ```

* LIKWID version and download source (Github, FTP, package manger, ...)
  ```bash
  likwid-perfctr -- Version 5.1.1 (commit: 233ab943543480cd46058b34616c174198ba0459)
  ```
  I can't tell you about the download source, I'm not the one who installed LIKWID on the cluster.
* Operating system
  CentOS Linux release 7.9.2009 (Core)
* Does your application use libraries like MPI, OpenMP or Pthreads?
  Probably, but only indirectly. Parts of the application are running in the JVM, which [seems to use Pthreads](https://stackoverflow.com/a/30835081/9985959). However, since I'm not using the wrapper mode, I guess this is not relevant anyways?
* In case of Nvidia GPUs, which CUDA version?
  /
* Are you using the MarkerAPI (CPU code instrumentation) or the NvMarkerAPI (Nvidia GPU code instrumentation)?
  No

**Additional context**
For my actual use case, I'm calling LIKWID over SSH on multiple nodes and then run it in the background with `nohup` and `&` to later kill the processes with `SIGINT` in another SSH connection:

```bash
nohup $likwid_cmd > $likwid_log_file 2> $likwid_err_file & echo $! >> $likwid_pids_file

# Later
kill -SIGINT $pid
```
The bash variables above are just for simplification, I actually call the commands from a Python script.

Because I'm running LIKWID in the background, I thought that maybe the way the file is written is conflicting with `nohup` or `$`, so I looked at the `likwid-perfctr` Lua sources and I guess I even found a potential issue (which, however, might not be related to the actual problem here since I can reproduce it even when not running LIKWID in the background): According to the Lua reference, [`file:write()`](https://www.lua.org/manual/5.3/manual.html#pdf-file:write) (which [`io.write()`](https://www.lua.org/manual/5.3/manual.html#pdf-io.write) is using) may return `nil` and an error message in case of a failure. When `-o` or `--output` is used, the perfctr sources define a `print()` function that uses `io.write()` but does not check the return value, so in case of an error the error is silently ignored:

https://github.com/RRZE-HPC/likwid/blob/a4116cdac104ee9560970093731cfa991f6a6d5e/src/applications/likwid-perfctr.lua#L353

The same holds true for the `print_stdout` and `print_stderr` functions, and potentially other functions in the io/file API (I haven't checked all of them).

Since I cannot (and should not) modify the cluster's LIKWID installation, is it possible to overwrite the Lua scripts on the application/user scope to debug them?

Another interesting observation is that using filters in combination with the timeline doesn't seem to be supported in newer versions?
https://github.com/RRZE-HPC/likwid/blob/a4116cdac104ee9560970093731cfa991f6a6d5e/src/applications/likwid-perfctr.lua#L1175
Perhaps I'm mistaken, but I don't see anything about this in the documentation or in the `--help` output.

Thanks!

**Comment by TomTheBear** [comment]
Thanks for using the timeline mode and reporting the issue. I thought I had documented it before but cannot find it at the moment: using the `--outfile` switch or filter scripts with timeline mode is not supported/implemented yet. I have some work-packages around timeline mode (if you have interest in collaborating).

I do not check the output of `io.write()` because it almost never occurs when printing to `stdout`/`stderr` (for me).

You can debug LIKWID's command line tools very simple even on a cluster:
```
$ cp $(which likwid-perfctr) .
$ vim likwid-perfctr
$ ./likwid-perfctr ...
```

The filter scripts parse the tables in CSV format outputted by the wrapper and MarkerAPI, so they cannot ingest the lines from timeline mode. With some work on the filters, it could be made possible, of course.

**Comment by TomTheBear** [comment]
I added a message when combining timeline mode with output redirection/filtering that it is not supported in https://github.com/RRZE-HPC/likwid/commit/8c3cb138e31aee15f02e33b7509ca0c434dc0ef5
