### ISSUE TITLE
[DOCS] CPU name was empty by likwid-perfctr -i

### ISSUE THREAD

**Issue by Autumn-Roy** [RRZE-HPC/likwid#525]
**What are you searching for**
I try to use likwid collecting info about CPU. But `likwid-perfctr -i` output empty of CPU name.

**Where have you searched for it**
I try to check the CPU in local file: `cat /proc/cpuinfo | grep name `, and I got an empty line.

Here is one of a CPU output: `cat /proc/cpuinfo | head -n 10 `

> processor       : 0
> BogoMIPS        : 200.00
> Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm
> CPU implementer : 0x48
> CPU architecture: 8
> CPU variant     : 0x1
> CPU part        : 0xd01
> CPU revision    : 0

Is there anything wrong when I installed the likwid?

**Comment by TomTheBear** [comment]
It's an unknown processor for LIKWID as well, so it cannot provide any information or features for you.

Which vendor is meant by the vendor ID `0x48`? I could add basic ARMv8 support for the chip but for more monitoring features, documentation is required.

https://github.com/RRZE-HPC/likwid/wiki/AddARMSupport

**Comment by TomTheBear** [comment]
Yes and no. ARM provides a basic set of counters & events. These can be enabled for the architecture but some kind of detection is required. If the chip vendor has extended this basic set (like A64FX) or changed it completely (like Apple M1), we need the documentation.

For testing, you could add the chip without a proper name but for integration in the repo, we need some chip information. Documentation only for extended event&counter support.

**Comment by TomTheBear** [comment]
I just found out:

> CPU implementer : 0x48

HiSilicon

> CPU part: 0xd01

Kunpeng-920

With this info, we could add it to the topology detection and basic hardware counting support in LIKWID. The cpu name is commonly read out of `/proc/cpuinfo`, so if there is no name, we can freely choose one. I would choose "HiSilicon Kunpeng-920".

**Comment by Autumn-Roy** [comment]
I check the cpu information with our engineer, "HiSilicon Kunpeng-920" is the right cpu name.

**Comment by TomTheBear** [comment]
I documented how to add a new ARM chip in the wiki: https://github.com/RRZE-HPC/likwid/wiki/AddARMSupport

I do not have access to such a system. The detection mechanism would work only for your system as it is based on the values you provided. But this does not mean that all HiSilicon Kunpeng-920 are detected then. Vendors use different IDs to identify the same architecture. If I have spare time, I probably could add the architecture based on the code of libpfm4 and the kernel, but at the moment I'm quite busy with other LIKWID related topics.

**Comment by Autumn-Roy** [comment]
Thanks, I will try to follow the document to add the ARM chip.

**Comment by Autumn-Roy** [comment]
I follow the wiki to add the arm chip. In the section "Adding support for performance monitoring", I'm confused, how can I get the  informaiton which used in `perfmon_<name>.h`, `perfmon_<name>_counters.h` and `perfmon_<name>_events.txt`?

**Comment by TomTheBear** [comment]
You commonly get this information from the vendor documentation. I also posted these links to other projects:

> https://sourceforge.net/p/perfmon2/libpfm4/ci/master/tree/lib/events/arm_hisilicon_kunpeng_events.h
> https://sourceforge.net/p/perfmon2/libpfm4/ci/master/tree/lib/events/arm_hisilicon_kunpeng_unc_events.h
> https://github.com/torvalds/linux/tree/master/tools/perf/pmu-events/arch/arm64/hisilicon/hip08

You could probably fully derive `perfmon_<name>_events.txt` from the links. The `perfmon_<name>_counters.h` probably contain the default six ARMv8 PMC counters, see [perfmon_a57_counters.h](https://github.com/RRZE-HPC/likwid/blob/master/src/includes/perfmon_a57_counters.h). Moreover, the links show that there are (at least) three Uncore units `ddrc`, `l3c` and `hha` but I didn't see the amount of counters of these units.

**Comment by TomTheBear** [comment]
The HiSilicon Kunpeng-920 should now be supported by 5.3.0 and `master` branch.
