### ISSUE TITLE
[Build] CUPTI not available

### ISSUE THREAD

**Issue by andy295** [RRZE-HPC/likwid#526]
I'm trying to build `LIKWID 5.0` on a system that has an old Nvidia GPU `Tesla K80`, with compute `capability < 7.0`.
I'm following the provided documentation but I'm stuck on the CUDA section of the `config.mk`.

My problem is that CUPTI is not installed, and looking at the Nvidia documentation I found that it isn't available for my GPU. I have already ordered a more modern GPU, but in the meanwhile I would like to experiment with LIKWID.

Does the unavailability of CUPTI mean that I cannot install the application?

**Comment by TomTheBear** [comment]
Why are you trying the old 5.0 Version?

The cupti library is only a piece of software,  so you should be able to install it. When I remember correctly, I used Likwid with a Tesla K80. But if it does not work, the library and (hopefully) Likwid will let you know.

Without the cupti library you won't be able to install Likwid with Nvidia GPU support. Of course, without Nvidia support, you can still build and use it for your CPU.

**Comment by andy295** [comment]
Sorry my mistake, I'm following the wiki [LIKWID-and-Nvidia-GPUs](https://github.com/RRZE-HPC/likwid/wiki/LIKWID-and-Nvidia-GPUs) and I thought `LIKWID 5.0` was the last version, but of course I'm using the last available.

On the Nvidia page I found a downloadable version of CUPTI, but unfortunately it is not compatible with my GPU. Because of that, I'm looking for a previous version of CUPTI.

Yes, I read that LIKWID was created for the CPU, but I would like to use it to monitor the consumption of the GPU.

**Comment by TomTheBear** [comment]
LIKWID cannot do any magic here. It relies on the CUPTI library for Nvidia GPU support.

You should be able to download and install any CUPTI version and probably can build LIKWID with it. The build phase uses the header files, the library is required only at runtime (through `dlopen`). But still, you won't have much fun without a supported GPU.
