### ISSUE TITLE
[FeatureRequest] Add domain for HWthreads closest to GPUs

### ISSUE THREAD

**Issue by JanLJL** [RRZE-HPC/likwid#534]
**Is your feature request related to a problem? Please describe.**
Often, GPUs are not closest to the NUMA domain a humain might think (e.g., GPU 3 is closest to NUMA domain 0, etc). Not every user remembers to run `likwid-topology` first to get the corresponding NUMA domains for their GPU(s).

**Describe the solution you'd like**
Add a affinity domain for `likwid-pin` and `likwid-perfctr`, e.g., `G` for placing HW threads close to the GPU.
For example, pinning 10 HWthreads closest to GPU 1:
```
likwid-pin -C G1:0-9 ./run_app
```

**Comment by stdweird** [comment]
i am also interested in being able to support cpu pinning in combination with gpu usage. what is the current best practise wrt likwidpin?

@JanLJL  you mentioned `likwid-topology`, but what is the proper flow a use should follow. i am also interested if likwid pin supports a hierarchy: if parent processes use a gpu, make sure the children are also pinned on cores in the same numa domain.

a very recent issue we had was people running torchrun with python code doing dataloader+train, and dataloaders. the dataload+train is what nvidia-smi reports as using the gpu, the remaining dataloaders are child processes of the train+dataload. torchrun is really crappy in pinning correctly, so we are looking for a way to "help" it. likwidpin would be a good candidate for this, but it's unclear how one woud invoke it
