### ISSUE TITLE
[BUG] Incorrect Memory bandwidth measurement on AMD Threadripper 2950x (Zen+)

### ISSUE THREAD

**Issue by badtst** [RRZE-HPC/likwid#535]
**Describe the bug**
When measuring memory bandwidth using likwid-perfctr in stethoscope mode and group MEM, reported memory bandwidth is ~ **half** of the memory bandwidth reported by the benchmark and AMDµProf measurements. 

Looks like `2950x` has 4 memory channels, two per die (2 for CCD-0 and 2 for CDD-1). 

Threadripper 2950x with 4x16GB RAM and all 4 DRAM channel being used (Output of `dmidecode --type 17` provided). 

[dmidecode17.txt](https://github.com/RRZE-HPC/likwid/files/11904217/dmidecode17.txt)

**To Reproduce**
* OS : Ubuntu 20.04.5 LTS
* Build Likwid from source `Version 5.2.2 (commit: 233ab943543480cd46058b34616c174198ba0459)`
* Run a memory intensive benchmark i.e. `stress-ng --memcpy 0`
* Measure memory with Likwid
* Compare output with `AMDuProfPcm -m memory -a -q -d 2000` for example, which is approximately double of what's reported by Likwid.

[AMDuProf.txt](https://github.com/RRZE-HPC/likwid/files/11904216/AMDuProf.txt)

**To Reproduce with a LIKWID command**
Output of the command with `-V 3` added to the command:
* likwid-perfctr -f -c 0-31 -g MEM -S 2s 
* likwid-topology

[perfctr.txt](https://github.com/RRZE-HPC/likwid/files/11904218/perfctr.txt)
[topology.txt](https://github.com/RRZE-HPC/likwid/files/11904219/topology.txt)

**Additional context**
*Processor Programming Reference (PPR) for AMD Family 17h Models 01h,08h, Revision B2 Processors* p161 writes that the measurement of transferred Data bytes is per *Node* which they define as : *A node, is an integrated circuit device that includes one to 8 cores (one or two Core Complexes).* i.e. CDD ? Which is detected by `likwid-topology` as a different die and not a different socket.

**Comment by TomTheBear** [comment]
Thanks for reporting. Please check the mentioned PR.

**Comment by badtst** [comment]
That looks good to me ! Memory measurement look more coherent. Thanks !

**Comment by TomTheBear** [comment]
Thanks for the response, I will merge the PR into master.
