### ISSUE TITLE
[BUG] Missing Likwid after installation with modified PREFIX

### ISSUE THREAD

**Issue by andy295** [RRZE-HPC/likwid#546]
The first time I installed `LIKWID` I forgot to set the path where to install it.

So I removed the installation  by using `sudo make uninstall`. Then I used 'make clean` and `make distclean`.
I modified the `config.mk` file in this way` PREFIX ?= /usr/local/likwid` and I reinstalled likwid with `make && sudo make install`.

After that I not more able to use likwid. For example if I digit `lokwid-topology` I obtain the following error message:

>Command 'likwid-topology' not found, but can be installed with: sudo apt install likwid

I also tried to set the environment variable, first I added `/usr/local/likwid` then `/usr/local/likwid/bin/`.
In the first case nothing happened, in the second case the system said that it was not able to found the `lua interpreter`.

Did I forget something?

**Comment by TomTheBear** [comment]
The paths `/usr/local/likwid` is not common, thus not in the default search list of operating systems.

You can add these lines to your `.bashrc` (or similar):
```
export PATH=/usr/local/likwid/sbin:/usr/local/likwid/bin:${PATH}
export LD_LIBRARY_PATH=/usr/local/likwid/lib:${LD_LIBRARY_PATH}
```
For simpler usage, I commonly define also:
```
export LIKWID_LIBDIR=/usr/local/likwid/lib
export LIKWID_INCDIR=/usr/local/likwid/include
```
If you are not sure which LIKWID is really called, use `which likwid-topology` to get the absolute path. If it is still `/usr/local/bin/likwid-topology`, something with the uninstallation went wrong.

**Comment by TomTheBear** [comment]
Were you able to resolve this?

**Comment by TomTheBear** [comment]
I close the issue now. If the problem persists, please re-open it.
