### ISSUE TITLE
[BUG] LIKWID_GPUMARKER_CLOSE on example instruction

### ISSUE THREAD

**Issue by andy295** [RRZE-HPC/likwid#547]
I installed `LIKWID 5.2.2` on a system that has the Nvidia GPU A100.
After the installation I tried some basic instructions, like for example `likwid-topology` with different parameters and everything seams to work correctly.

After that, following the reference [page](https://github.com/RRZE-HPC/likwid/wiki/LIKWID-and-Nvidia-GPUs) I tried to check if I'm able to collect data from the GPU.

I tried the following instruction: `sudo likwid-perfctr -G 0 -W FLOPS_DP -m likwid-nvidia/test/triadCU` and I obtained the following message error:

> CPU name:       AMD EPYC 7742 64-Core Processor                
CPU type:       AMD K17 (Zen2) architecture
CPU clock:      2.25 GHz
Failed to execute command: likwid-nvidia/test/triadCU
GPU Marker API result file does not exist. This may happen if the application has not called LIKWID_GPUMARKER_CLOSE.

I'm not sure if the problem is related to the installation or if there is another problem.

**Comment by TomTheBear** [comment]
Thanks for reporting. I just tried it on our [Alex cluster](https://hpc.fau.de/systems-services/documentation-instructions/clusters/alex-cluster/) (8 A100 per node) and it works.

First, it does not find the executable:
> `Failed to execute command: likwid-nvidia/test/triadCU`

The error is on the wiki page, the folder `likwid-nvidia` is wrong, use only `test/triadCU`. It's not mentioned explicitly but you have to compile `triadCU` first: `make -C test triadCU`.

Moreover, `sudo` commonly empties the `LD_LIBRARY_PATH` and other environment variables to avoid security issues. 

I updated the page (path to `triadCU` and the `make triadCU` step).

**Comment by andy295** [comment]
I tried to run without `sudo`, but I obtain the following message error:

> ERROR - [./src/includes/nvmon_perfworks.h:nvmon_perfworks_addEventSet:1620] Success.
Function (*cuptiProfilerGetCounterAvailabilityPtr)(&getCounterAvailabilityParams) failed with error 35
ERROR - [./src/includes/nvmon_perfworks.h:nvmon_perfworks_addEventSet:1620] Success.
CUPTI_ERROR_INSUFFICIENT_PRIVILEGES
ERROR - [./src/nvmon.c:nvmon_addEventSet:468] Bad address.
Failed to add event set for GPU 0

I read the documentation about `CUPTI_ERROR_INSUFFICIENT_PRIVILEGES` issue and basically `NVIDIA` suggests to use the `sudo` command.

Do you think that it can be a problem?

**Comment by TomTheBear** [comment]
The `sudo` fix is just for temporal permissions. There are other ways to do it permanently, see [Enable access permanently](https://developer.nvidia.com/nvidia-development-tools-solutions-err_nvgpuctrperm-permission-issue-performance-counters#SolnAdminTag). This should work:
`sudo PATH="$PATH" HOME="$HOME" LD_LIBRARY_PATH="$LD_LIBRARY_PATH" likwid-perfctr ...`

The `Makefile` misses the `-Xcompiler -fopenmp` options for the compilation. Not sure why. I changed it in the master branch: https://github.com/RRZE-HPC/likwid/commit/6a2421b6b31d25ae1a2b18a050ded0acbb291675

**Comment by andy295** [comment]
I had to change the `cuda` version from `11.6` to `11.8`, so I removed `Likwid` and installed it again with the new path.

If I run the command I obtain the following error message:

> CUDA runtime library libcudart.so not found.ERROR - [./src/topology_gpu.c:topology_gpu_init:226] Cannot open CUDA library to fill GPU topology
CUDA runtime library libcudart.so not found.ERROR - [./src/topology_gpu.c:topology_gpu_init:226] Cannot open CUDA library to fill GPU topology
CPU name:       AMD EPYC 7742 64-Core Processor                
CPU type:       AMD K17 (Zen2) architecture
CPU clock:      2.25 GHz
/usr/local/bin/likwid-lua: /usr/local/bin/likwid-perfctr:742: attempt to get length of a nil value (global 'gpulist')
stack traceback:
        /usr/local/bin/likwid-perfctr:742: in main chunk
        [C]: in ?

However, if I look for the file `libcudart.so` file with `find` I obtain this result:

> /usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so

The `CUDA_HOME` is equal to `/usr/local/cuda-11.8/` and the `LD_LIBRARY_PATH` in equal to `/usr/local/cuda-11.8/:/usr/local/cuda-11.8/lib64:/usr/local/cuda-11.1/targets/x86_64-linux/lib`

Here below the last part of the `Likwid config.mk` file:

> CUDAINCLUDE = $(CUDA_HOME)/include
CUPTIINCLUDE = $(CUDA_HOME)/extras/CUPTI/include
BUILDAPPDAEMON=true

**Comment by TomTheBear** [comment]
Your `LD_LIBRARY_PATH` does not contain the path to `libcudart.so`, there is `/usr/local/cuda-11.1/...` but it should be `/usr/local/cuda-11.8/...`

Nvidia sometimes does breaking changes in minor releases but it seems not to be the case for CUDA 11.6 -> 11.8.

**Comment by TomTheBear** [comment]
I just tested the topology component with CUDA 12.0.1 and 12.1.1 as well and it works.

**Comment by andy295** [comment]
That was a mistake for sure, thanks for that. I fixed it with the correct path, now I have 

`LD_LIBRARY_PATH=/usr/local/cuda-11.8/lib64:/usr/local/cuda-11.8/targets/x86_64-linux/lib`

However, I obtain the same error message.

Is there something else that I can do to check if `Likwid` is looking on the right position?

**Comment by andy295** [comment]
Ok, I changed the PATHs in this way:

`export CUDA_HOME=/usr/local/cuda`
`export PATH="/usr/local/cuda/bin:$PATH"`
`export LD_LIBRARY_PATH="/usr/local/cudau/lib64:$LD_LIBRARY_PATH"`

and now that error seems to be gone.

Unfortunately now I have this one here:

> CPU name:       AMD EPYC 7742 64-Core Processor                
CPU type:       AMD K17 (Zen2) architecture
CPU clock:      2.25 GHz
ERROR - [./src/nvmon.c:nvmon_init:204] No such file or directory.
Cannot create device 0

**Comment by TomTheBear** [comment]
In the output, it writes that it cannot find one of the libraries `libcupti.so`. Please check where it is located in your CUDA installation and add the path to `LD_LIBRARY_PATH`.  It's commonly `${CUDA_HOME}/extras/CUPTI/lib` but it might have changed in the recent versions of CUDA.

**Comment by andy295** [comment]
I found it into `/usr/local/cuda/extras/CUPTI/lib64`, I added it into the `LD_LIBRAY_PATH`, but nothing has changed.

Here the final part of the output file:

> DEBUG - [nvmon_init:182] Device 0 runs with CUPTI Profiling API backend
DEBUG - [nvmon_perfworks_createDevice:857] link_perfworks_libraries in createDevice
DEBUG - [link_perfworks_libraries:377] LD_LIBRARY_PATH=(null)
DEBUG - [link_perfworks_libraries:378] CUDA_HOME=(null)
DEBUG - [link_perfworks_libraries:468] CUpti library libcupti.so not found
ERROR - [./src/nvmon.c:nvmon_init:204] No such file or directory.

Why `LD_LIBRARY_PATH` and `CUDA_HOME` and `null`?

**Comment by TomTheBear** [comment]
You learn something, so no time wasted.

Unfortunately, you cannot do that at the moment with LIKWID but it will be generally challenging. As far as I remember, you do not get energy measurements (Joules) from the Nvidia libraries only power (Watt). So you cannot take a sample in the beginning of your training parts and one in the end to calculate power consumption of your kernel. Please check yourself to be sure.

**Comment by andy295** [comment]
Ok, I'll try to check directly some Nvidia, like the Nsight Perf SDK, which has replaced CUPTI and PerfWorks.

In any case, currently Likwid is not even capable of measuring the used power (Watt), of the GPU of course? In the meantime, that would be more than sufficient.

**Comment by TomTheBear** [comment]
Nsight Perf SDK uses CUPTI or Cupti/PerfWorks under the hood. It seems Nsight Perf is more for the graphics pipelines while NVIDIA Nsight Compute is for computing.
Since those are vendor tools, they should provide you with all functionality.

No, the Nvidia NVML library with the power readings is not yet supported.
