### ISSUE TITLE
[DOCS] CACHES perfctr removed?

### ISSUE THREAD

**Issue by mknaranja** [RRZE-HPC/likwid#556]
In https://github.com/RRZE-HPC/likwid/wiki/TutorialStart#performance-groups, I find the CACHES group counter which I assume that is not available anymore. Has this been replaced by another name (or removed)?

**Comment by TomTheBear** [comment]
The CACHES group is only available on few systems. You can create it yourself for your architecture but I recommend using the individual group L2, L3 and MEM.

**Comment by TomTheBear** [comment]
I removed the `CACHES` group from the output in the tutorial. And added some sentences to clarify that the outputs are architecture-dependent (for Intel SandyBridge EP).
