### ISSUE TITLE
Use as much machine readable documentation as possible

### ISSUE THREAD

**Issue by cod3monk** [RRZE-HPC/likwid#56]
Build event definitions for Intel architectures from https://download.01.org/perfmon/, with the optional introduction of patches to fix known issues with the provided JSON definitions.

Do other vendors provide similar machine readable documentation?

**Comment by TomTheBear** [comment]
This won't be part of LIKWID 5. It's only Intel who publishes their event lists in machine readable format. It would add another dependency (C or Lua JSON or TSV parser). For ARM and POWER exist some tables on webpages with a lot of JS stuff. I tried wget once with mixed results and parsing the HTML is no fun.
