### ISSUE TITLE
[BUG] nil value field getGpuTopology 

### ISSUE THREAD

**Issue by Atrisan** [RRZE-HPC/likwid#589]
`getGpuTopology()` is a null value, in the likwid.lua, when executing the triadCU test with the GPUMarkerAPI via likwid-perfctr.

#### Sources
Installation from Github branch: write_marker_file
Commit Hash: [3a54b98](https://github.com/RRZE-HPC/likwid/commit/3a54b988fb157a35c5f453a61430fd7083f69b73)

#### Config

[config.txt](https://github.com/RRZE-HPC/likwid/files/13637968/config.txt)

#### Install command
```
make && make install
```

### Execution:
```
likwid-perfctr -G 0 -W FLOPS_DP -m -V 3 test/triadCU
```

### Output:
[output.txt](https://github.com/RRZE-HPC/likwid/files/13637923/output.txt)

### Environment

Operating system: Rocky 8.9
CPU Setup:
```
=====  Processor composition  =====
Processor name    : Intel(R) Xeon(R) Platinum 8160  
Packages(sockets) : 2
Cores             : 48
Processors(CPUs)  : 48
Cores per package : 24
Threads per core  : 1
```

GPU Setup:
2x Nvidia Tesla V100-SXM2 with CUDA 12.0 Driver 

#### Compiler
CPU: GCC 11.3.0
GPU: CUDA 11.8

### Application 
triad.cu from the likwid testcases.

**Comment by TomTheBear** [comment]
Similar reason than the non-working markers. I renamed `getGpuTopology` to `getCudaTopology` but unfortunately not everywhere.

**Comment by TomTheBear** [comment]
This should now be fixed in the `master` branch. It would be great if you could test it and comment on/close the issue.

**Comment by Atrisan** [comment]
Thanks, everything works now.
