### ISSUE TITLE
Using the additional counters (PMC{4..7}) fails on BroadwellEP

### ISSUE THREAD

**Issue by K-Wic** [RRZE-HPC/likwid#59]
Hi,

I tried to use the additional PMCs on my Broadwell machine, but the additional counters only show zeros.

The CPU is a Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz wtih Hyperthreading turned off. I used the PORT_USAGE group as a test and this is the result:

```
+--------------------------------+---------+--------------+
|              Event             | Counter |      Sum     |
+--------------------------------+---------+--------------+
|     INSTR_RETIRED_ANY STAT     |  FIXC0  | 179574190000 |
|   CPU_CLK_UNHALTED_CORE STAT   |  FIXC1  | 175468080000 |
|    CPU_CLK_UNHALTED_REF STAT   |  FIXC2  | 175469240000 |
| UOPS_EXECUTED_PORT_PORT_0 STAT |   PMC0  |  43542586000 |
| UOPS_EXECUTED_PORT_PORT_1 STAT |   PMC1  |  61975496000 |
| UOPS_EXECUTED_PORT_PORT_2 STAT |   PMC2  |  51583122000 |
| UOPS_EXECUTED_PORT_PORT_3 STAT |   PMC3  |  51799443000 |
| UOPS_EXECUTED_PORT_PORT_4 STAT |   PMC4  |       0      |
| UOPS_EXECUTED_PORT_PORT_5 STAT |   PMC5  |       0      |
| UOPS_EXECUTED_PORT_PORT_6 STAT |   PMC6  |       0      |
| UOPS_EXECUTED_PORT_PORT_7 STAT |   PMC7  |       0      |
+--------------------------------+---------+--------------+
```

I have also tried assigning the events to different counters, but it is always PMC{4..7} that refuse to count. Attached is a log of a run with -V 3. Maybe someone with insider infos can figure out whats going wrong.

MfG
K-Wic

[Uploading likwid-perfctr_broadwellEP_counter_failure.txt…]()

**Comment by TomTheBear** [comment]
Hi,
I cannot read the -V 3 log, it is a link to this page.
Greetings,
Thomas

**Comment by K-Wic** [comment]
Sorry,
should be uploaded now

[likwid-perfctr_broadwellEP_counter_failure.txt](https://github.com/RRZE-HPC/likwid/files/447855/likwid-perfctr_broadwellEP_counter_failure.txt)

**Comment by TomTheBear** [comment]
The log seems fine. 

Accessible?
```
DEBUG - [perfmon_addEventSet:1614] Added event UOPS_EXECUTED_PORT_PORT_4 for counter PMC4 to group 0
DEBUG - [perfmon_addEventSet:1614] Added event UOPS_EXECUTED_PORT_PORT_5 for counter PMC5 to group 0
DEBUG - [perfmon_addEventSet:1614] Added event UOPS_EXECUTED_PORT_PORT_6 for counter PMC6 to group 0
DEBUG - [perfmon_addEventSet:1614] Added event UOPS_EXECUTED_PORT_PORT_7 for counter PMC7 to group 0
```
Yes

Program the registers:
```
DEBUG - [bdw_pmc_setup:193] SETUP_PMC [0] Register 0x18A , Flags: 0x4110A1 
DEBUG - [bdw_pmc_setup:193] SETUP_PMC [0] Register 0x18B , Flags: 0x4120A1 
DEBUG - [bdw_pmc_setup:193] SETUP_PMC [0] Register 0x18C , Flags: 0x4140A1 
DEBUG - [bdw_pmc_setup:193] SETUP_PMC [0] Register 0x18D , Flags: 0x4180A1
```
Yes

Start the counters:
```
DEBUG - [perfmon_startCountersThread_broadwell:1272] CLEAR_PMC_AND_FIXED_OVERFLOW [0] Register 0x390 , Flags: 0xC0000007000000FF 
DEBUG - [perfmon_startCountersThread_broadwell:1274] UNFREEZE_PMC_AND_FIXED [0] Register 0x38F , Flags: 0x7000000FF 
```
The FF in the end refers to the 8 PMC counters.

But the registers always return 0, so nothing is counted. I will check that as soon as possible on one of our Broadwell EP systems.
Have you tried different events on these counters?

**Comment by K-Wic** [comment]
It is the same with other events:
```
+-----------------------------------------------+---------+--------------+
|                     Event                     | Counter |      Sum     |
+-----------------------------------------------+---------+--------------+
|             INSTR_RETIRED_ANY STAT            |  FIXC0  | 482511923027 |
|           CPU_CLK_UNHALTED_CORE STAT          |  FIXC1  | 593646522789 |
|           CPU_CLK_UNHALTED_REF STAT           |  FIXC2  | 593665434960 |
|         UOPS_EXECUTED_PORT_PORT_0 STAT        |   PMC0  | 107565188634 |
|         UOPS_EXECUTED_PORT_PORT_1 STAT        |   PMC1  | 153711761795 |
|         UOPS_EXECUTED_PORT_PORT_2 STAT        |   PMC2  | 133289577159 |
|         UOPS_EXECUTED_PORT_PORT_4 STAT        |   PMC3  |  68141830174 |
| FP_ARITH_INST_RETIRED_256B_PACKED_DOUBLE STAT |   PMC4  |       0      |
|              L1D_REPLACEMENT STAT             |   PMC5  |       0      |
|              L2_LINES_IN_ALL STAT             |   PMC6  |       0      |
|         UOPS_EXECUTED_PORT_PORT_3 STAT        |   PMC7  |       0      |
+-----------------------------------------------+---------+--------------+
```

**Comment by TomTheBear** [comment]
There was some delay but now I tried it and got the same behavior. Everything looks fine (events are added, configuration is done and they are started) but the counters do not increment. I will retry it on another Broadwell EP. I currently don't know where to search for a bug as the commonly failing operations run fine.

**Comment by K-Wic** [comment]
No Problem. Just tell me if there is anything I can do to help.

**Comment by TomTheBear** [comment]
I got response from Intel that the additional PMC counters are not working if either user-level or kernel-level measurements are configured. If both are selected it should work. An erratum is published for that but I cannot find it. But there are some errata that indicate problems with the user-level / kernel-level filtering.
Can you please try events on PMC4-7 with the KERNEL option, thus something like this: FP_ARITH_INST_RETIRED_256B_PACKED_DOUBLE:PMC4:KERNEL
User-level filtering is always active in LIKWID, so this should activate both modes.

**Comment by K-Wic** [comment]
Good news,
it is working:

```
+------------------------------------------+-------------+--------------+--------------+
|                   Event                  |   Counter   |    Core 13   |    Core 14   |
+------------------------------------------+-------------+--------------+--------------+
|            Runtime (RDTSC) [s]           |     TSC     | 1.155388e+01 | 1.092751e+01 |
| FP_ARITH_INST_RETIRED_256B_PACKED_DOUBLE |     PMC0    |  33000060000 |  33000060000 |
| FP_ARITH_INST_RETIRED_256B_PACKED_DOUBLE | PMC1:KERNEL |  33000060000 |  33000060000 |
| FP_ARITH_INST_RETIRED_256B_PACKED_DOUBLE |     PMC4    |       0      |       0      |
| FP_ARITH_INST_RETIRED_256B_PACKED_DOUBLE | PMC5:KERNEL |  33000060000 |  33000060000 |
|             INSTR_RETIRED_ANY            |    FIXC0    |  44137760000 |  44137770000 |
|           CPU_CLK_UNHALTED_CORE          |    FIXC1    |  28844890000 |  27934590000 |
|           CPU_CLK_UNHALTED_REF           |    FIXC2    |  28844900000 |  27934620000 |
+------------------------------------------+-------------+--------------+--------------+
```

Could that be automated for events on Broadwell w/out Hyper Threading for counters >= PMC4 or should I rather add the KERNEL flag to the groups manually?

**Comment by TomTheBear** [comment]
Thanks for testing. I'm going to add the kernel option for the additional counters automatically and document it properly. For the FP events there shouldn't be a problem since the kernel rarely or never uses FP. For other events there can be problems with too high counts caused by kernel code.
