### ISSUE TITLE
[BUG] LIKWID_NVMARKER* shortcuts are not working

### ISSUE THREAD

**Issue by teojgo** [RRZE-HPC/likwid#590]
**Describe the bug**

The LIKWID_NVMARKER family of shortcuts (e.g `LIKWID_NVMARKER_INIT`) are not recognized. The following error is thrown during compilation:

```
tream.cu(150): error: identifier "likwid_gpuMarkerInit" is undefined

stream.cu(162): error: identifier "likwid_gpuMarkerRegisterRegion" is undefined

stream.cu(171): error: identifier "likwid_gpuMarkerStartRegion" is undefined

stream.cu(174): error: identifier "likwid_gpuMarkerStopRegion" is undefined

stream.cu(182): error: identifier "likwid_gpuMarkerStartRegion" is undefined

stream.cu(185): error: identifier "likwid_gpuMarkerStopRegion" is undefined

stream.cu(193): error: identifier "likwid_gpuMarkerStartRegion" is undefined

stream.cu(196): error: identifier "likwid_gpuMarkerStopRegion" is undefined

stream.cu(204): error: identifier "likwid_gpuMarkerStartRegion" is undefined

stream.cu(207): error: identifier "likwid_gpuMarkerStopRegion" is undefined

stream.cu(233): error: identifier "likwid_gpuMarkerClose" is undefined
```

**To Reproduce**
It is straightforward to reproduce by trying to make one of the cuda related tests using: `make -C tests streamCU`

* LIKWID version: Current master branch (49ec7af2e7739b2d59f1ace6433ba6643120e3a8)
* Operating system: SUSE Linux Enterprise Server 15 SP3SLES
* The test uses OpenMP
* Cuda version 11.6
* The test uses the NVMARKER API.

likwid was build with Nvidia integration enabled.

**Comment by TomTheBear** [comment]
Thanks for reporting. Another user @Atrisan found it yesterday and reported it in the LIKWID chat.

The patch is contained in #586 :
https://github.com/RRZE-HPC/likwid/pull/586/files#diff-97290a617557f2326bf33082439592b0ab9a6dfae07b0a7453a06eddba50bc19

I have to do some testing before I can merge the PR #586, so feel free to use the patch.

**Comment by teojgo** [comment]
> make -C tests streamCU

Yes now it works, thank you very much!
