### ISSUE TITLE
[Build] redefinition of ‘lua_likwid_rocmSupported’ with ROCM_INTERFACE=true

### ISSUE THREAD

**Issue by OkkeVanEck** [RRZE-HPC/likwid#596]
**Which version do you want to build?**
v5.3.0 - latest: [https://github.com/RRZE-HPC/likwid/releases/tag/v5.3.0](https://github.com/RRZE-HPC/likwid/releases/tag/v5.3.0)
Tarball: [https://github.com/RRZE-HPC/likwid/archive/refs/tags/v5.3.0.tar.gz](https://github.com/RRZE-HPC/likwid/archive/refs/tags/v5.3.0.tar.gz)

**Which architecture do you want to build for?**
- [x] x86_64
- [ ] ARMv8
- [ ] POWER9
- [ ] Nvidia GPUs
- [ ] x86 (32 bit)
- [ ] ARMv7
- [ ] POWER8

**To Reproduce**
- Changes to `config.mk` (you may leave out `PREFIX` changes)
    - set `ROCM_INTERFACE` to `true`
- Changes to build configurations `make/include_<COMPILER>.mk`
    - N/A 
- Any other changes
    - export ROCM_HOME variable: `export ROCM_HOME=/opt/rocm`  
        - As a NOTE: we're building on a supercomputer with the Cray environment. Loading the `rocm` module does not set the `ROCM_HOME` variable which is required for `config.mk`.

**Output log**
Error output of `make distclean && make`
```bash
/pfs/lustrep4/projappl/project_465000527/perf_tools/likwid/likwid-5.3.0/src/luawid.c:3700:12: error: redefinition of ‘lua_likwid_rocmSupported’
 static int lua_likwid_rocmSupported(lua_State *L) {
            ^~~~~~~~~~~~~~~~~~~~~~~~
/pfs/lustrep4/projappl/project_465000527/perf_tools/likwid/likwid-5.3.0/src/luawid.c:3036:12: note: previous definition of ‘lua_likwid_rocmSupported’ was here
 static int lua_likwid_rocmSupported(lua_State *L) {
            ^~~~~~~~~~~~~~~~~~~~~~~~
gcc: error: ./GCC/luawid.o: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -llikwid: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:112: likwid-bench] Error 1
make: *** [Makefile:319: bench/likwid-bench] Error 2
```

**Comment by TomTheBear** [comment]
I think I fixed it already in the master branch but I'm not sure.

**Comment by OkkeVanEck** [comment]
PR has been approved.
