### ISSUE TITLE
[FeatureRequest] DRAM traffic for Roofline on a two socket AMD 7773X (zen3) system

### ISSUE THREAD

**Issue by kadircs** [RRZE-HPC/likwid#610]
`MEM_DP` and `MEM_SP` are suggested for getting DRAM traffic for an application. But there is no such group for `zen3`: 
https://github.com/RRZE-HPC/likwid/tree/master/groups/zen3

Is there another way to measure an application's total DRAM traffic on a two socket AMD 7773X system?

**Comment by TomTheBear** [comment]
Measure once with `MEM1` and again with `MEM2` to get the full picture.

AMD Zen3 requires 8 DataFabric events to get the memory traffic but the DataFabric provides only 4 physical registers, therefore two groups.
