### ISSUE TITLE
Haswell MEM formulas not consistent with the metrics

### ISSUE THREAD

**Issue by ivan-pi** [RRZE-HPC/likwid#615]
https://github.com/RRZE-HPC/likwid/blob/51d851fbe8425a8399fd184e813a93cca7ef4843/groups/haswell/MEM.txt#L1-L29

**Comment by TomTheBear** [comment]
Thanks for reporting. The inconsistency got fixed in https://github.com/RRZE-HPC/likwid/commit/e64aae09395b6176079ca9b471de4c17fd57f61c
