### ISSUE TITLE
[Build] No rule to make target '/applications/likwid-perfctr.lua'

### ISSUE THREAD

**Issue by OkkeVanEck** [RRZE-HPC/likwid#629]
**Which version do you want to build?**  
VERSION=5.3.0
SOURCE=http://ftp.fau.de/pub/likwid/likwid-5.3.0.tar.gz

**Which architecture do you want to build for?**  
- [ x ] x86_64
- [ ] ARMv8
- [ ] POWER9
- [ ] Nvidia GPUs
- [ ] x86 (32 bit)
- [ ] ARMv7
- [ ] POWER8
It's on a Cray machine running CrayOS (5.14.21-150400.24.81_12.0.75-cray_shasta_c).

**To Reproduce**  
- Changes to `config.mk`
  - Set `ACCESSMODE = perf_event#NO SPACE`

**Output log**
Error output of `make distclean && make`

> vaneckok@uan03:/scratch/project_465000527/ovaneck/perf_tools/likwid/lumi/src_5.3.0> make distclean && make
> Info: Compiling for perf_event interface. Measurements of thermal information is disabled
> ===>  ENTER  /scratch/project_465000527/ovaneck/perf_tools/likwid/lumi/src_5.3.0/ext/lua
> Info: Compiling for perf_event interface. Measurements of thermal information is disabled
> ===>  ENTER  /scratch/project_465000527/ovaneck/perf_tools/likwid/lumi/src_5.3.0/ext/hwloc
> Info: Compiling for perf_event interface. Measurements of thermal information is disabled
> ===>  ENTER  /scratch/project_465000527/ovaneck/perf_tools/likwid/lumi/src_5.3.0/ext/GOTCHA
> Info: Compiling for perf_event interface. Measurements of thermal information is disabled
> ===>  ENTER  bench
> Info: Compiling for perf_event interface. Measurements of thermal information is disabled
> ===>  DIST CLEAN
> Info: Compiling for perf_event interface. Measurements of thermal information is disabled
> ===>  ENTER  /scratch/project_465000527/ovaneck/perf_tools/likwid/lumi/src_5.3.0/ext/hwloc
> Info: Compiling for perf_event interface. Measurements of thermal information is disabled
> ===>  ENTER  /scratch/project_465000527/ovaneck/perf_tools/likwid/lumi/src_5.3.0/ext/lua
> Info: Compiling for perf_event interface. Measurements of thermal information is disabled
> ===>  CREATE SHARED LIB  liblikwid.so
> ===>  CREATE LIB  liblikwidpin.so
> make[1]: Entering directory '/pfs/lustrep4/scratch/project_465000527/ovaneck/perf_tools/likwid/lumi/src_5.3.0/src/pthread-overload'
> Info: Compiling for perf_event interface. Measurements of thermal information is disabled
> make[1]: Leaving directory '/pfs/lustrep4/scratch/project_465000527/ovaneck/perf_tools/likwid/lumi/src_5.3.0/src/pthread-overload'
> make: *** No rule to make target '/applications/likwid-perfctr.lua', needed by 'likwid-perfctr'.  Stop.
> vaneckok@uan03:/scratch/project_465000527/ovaneck/perf_tools/likwid/lumi/src_5.3.0>

**Comment by TomTheBear** [comment]
Thanks for reporting. This is new.

My guess would be that there is some character in your path that somehow breaks it. The target exists:
`$(L_APPS): $(addprefix $(SRC_DIR)/applications/,$(addsuffix  .lua,$(L_APPS)))`
with `SRC_DIR=$(shell pwd)` during setup. With my basic knowledge about `make`, I would say it is ok like that. Can you try to replace the `$(shell pwd)` with the source path manually? Or shorten the path of the sources?

**Comment by OkkeVanEck** [comment]
Thank you for the quick reply! 
I found the problem.. I created my own `$SRC_DIR` variable in the `config.mk` to create a path relative to the `$PWD` of `config.mk`. From your snippet I see that you also use `$SRC_DIR` internally, so this created the conflict. Changing my variable name solved the problem.
