### ISSUE TITLE
[Build] Repeated "cd: $(INSTALLED_LIBPREFIX): No such file or directory" during installation

### ISSUE THREAD

**Issue by OkkeVanEck** [RRZE-HPC/likwid#631]
**Which version do you want to build?**
VERSION=5.3.0
SOURCE=http://ftp.fau.de/pub/likwid/likwid-5.3.0.tar.gz

**Which architecture do you want to build for?**
- [ x ] x86_64
- [ ] ARMv8
- [ ] POWER9
- [ ] Nvidia GPUs
- [ ] x86 (32 bit)
- [ ] ARMv7
- [ ] POWER8

**To Reproduce**
- Changes to `config.mk` (you may leave out `PREFIX` changes)
  - ACCESSMODE = perf_event
- Changes to build configurations `make/include_<COMPILER>.mk`
  - FC  = ftn
  -  FCFLAGS  = -J ./ -efZ

**Output log**
Error output of `make distclean && make && make install`:

> ...
> ===> No INSTALL of the access daemon
> ===> No INSTALL of setFrequencies tool
> ===> No INSTALL of the application interface appDaemon
> ===> INSTALL applications to ../install/bin
> ===> INSTALL helper applications to ../install/bin
> ===> INSTALL lua to likwid interface to ../install/share/lua
> ===> INSTALL libraries to ../install/lib
> /bin/sh: line 30: cd: ../install/lib: No such file or directory
> /bin/sh: line 31: cd: ../install/lib: No such file or directory
> /bin/sh: line 32: cd: ../install/lib: No such file or directory
> /bin/sh: line 34: cd: ../install/lib: No such file or directory
> /bin/sh: line 35: cd: ../install/lib: No such file or directory
> /bin/sh: line 38: cd: ../install/lib: No such file or directory
> /bin/sh: line 39: cd: ../install/lib: No such file or directory
> ===> INSTALL man pages to ../install/man/man1
> ===> INSTALL headers to ../install/include
> ===> INSTALL groups to ../install/share/likwid/perfgroups
> ===> INSTALL docs and examples to ../install/share/likwid/docs
> ===> INSTALL filters to /pfs/lustrep4/scratch/project_465000527/ovaneck/perf_tools/likwid/lumi/install/share/likwid/filter
> ===> INSTALL cmake to /pfs/lustrep4/scratch/project_465000527/ovaneck/perf_tools/likwid/lumi/install/share/likwid

The errors occur during the `make install` step. To me it looks like the problem might be the consecutive `@cd $(INSTALLED_LIBPREFIX) && ln -fs ..` commands in the Makefile, but I'm not an expert on that so I'm not sure.  The error remains if I pre-make the `../install/lib/` folder.

**Comment by OkkeVanEck** [comment]
Problem occurs due to `$PREFIX` being a relative path instead of an absolute one.
@TomTheBear would you agree that it'd be good to add a note to the building wiki stating that `$PREFIX` should be an absolute path?

**Comment by TomTheBear** [comment]
Correct, only absolute paths. I added it to the comment above [`PREFIX` in config.mk](https://github.com/RRZE-HPC/likwid/commit/d4f6c4e3e5ebfa195c5d5f535438ddb3f8630b12)
