### ISSUE TITLE
Minor clarification for Haswell FLOPS page

### ISSUE THREAD

**Issue by jdmccalpin** [RRZE-HPC/likwid#64]
The page at https://github.com/RRZE-HPC/likwid/wiki/FlopsHaswell nicely describes the functions of the individual Umask bits of Event 0xC6 "AVX_INSTS" that was partly documented by Intel.

The term "AVX" is ambiguous in this context -- it is often used to refer to instructions that use 256-bit registers, but it also refers to instructions that use the new 3-operand AVX instruction format.   It was not clear to me from reading this page which meaning is the right one for this event.

Using the "-mprefer-avx128" flag with the gcc compiler, I was able to demonstrate that this event only increments for 256-bit AVX instructions.  It does not increment for AVX instructions operating on 128-bit registers. It is probably safe to assume that it will not increment for scalar AVX instructions either, but I did not test this.

**Comment by TomTheBear** [comment]
Hi,
thanks for the clarification. I updated the page.
