### ISSUE TITLE
Sandy Bridge PMU bug

### ISSUE THREAD

**Issue by hofm** [RRZE-HPC/likwid#65]
There's a bug in SNB for some events that appears not to be accounted for in likwid.
More information here: https://software.intel.com/en-us/articles/performance-monitoring-on-intel-xeon-processor-e5-family
Here's a script that does some magic before the measurement to fix the counters: https://github.com/andikleen/pmu-tools/blob/master/latego.py After the measurement, some magic has to be applied to undo the changes, otherwise the system will be left in a lowish-performance mode.

See plots for a comparison of PERF and LIKWID-PERFCTR for SNB (which has the bug) and IVB (which doesn't have the bug).
https://s18.postimg.org/4oi4sh28p/load_snb.jpg
https://s21.postimg.org/5l3wax4zr/load_ivb.jpg

**Comment by TomTheBear** [comment]
I adopted the way of the perf_event interface which uses the OFFCORE_RESPONSE events with corresponding filter bitmasks. Measurements showed similar results as the UOP based performance group with the latego.py workaround.

https://s13.postimg.org/veokq09av/snb_fix_check.png
@hofm Thanks for the measurements
