### ISSUE TITLE
Skip mask not correctly detected with Intel compiler V17

### ISSUE THREAD

**Issue by rrzeschorscherl** [RRZE-HPC/likwid#75]
The OpenMP runtime in Intel 17 seems to not generate a shepherd thread any more. Likwid-pin etc. do not know this and use 0x1 as a skip mask for Intel, which leaves a worker thread non-pinned. The current workaround is to use -s 0x0 when the binary was compiled with Intel 17, but this should really be auto-detected.

**Comment by TomTheBear** [comment]
Based on your idea I added a mechanism to check for the shepard threads automatically. I tested the mechanism with GCC, PGI compilers and Intel C/C++ compilers. The version 11.0/11.1 of Intel's compiler refuses to collaborate, thus a skip mask has to be set by users if they want to use this outdated compiler version. The man page of likwid-pin contains an 'Important Notice' now.
