### ISSUE TITLE
likwid-lua crashes

### ISSUE THREAD

**Issue by michel2323** [RRZE-HPC/likwid#77]
Hi,

I followed all the steps to build and install likwid on a single KNL node. Unfortunately, likwid-lua crashes:

*** Error in `/opt/likwid/bin/likwid-lua': malloc(): memory corruption: 0x00000000022acc60 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7dd4d)[0x7f572e4c0d4d]
/lib64/libc.so.6(__libc_malloc+0x4c)[0x7f572e4c2fbc]
....

Weirdly enough, it runs successfully through valgrind. Is there anything I'm missing? What additional information shall I provide?

Thank you.

**Comment by yidawang** [comment]
@michel2323 Did you solve this issue? I encountered the some. Thanks!

**Comment by michel2323** [comment]
No, I gave up on it. I suspect it's a lua issue connected with the old version thereof.

**Comment by TomTheBear** [comment]
The integrated Lua is version 5.3.2. Latest version of Lua is 5.3.4. There is no big gap between the versions. I'm not sure whether you can blame Lua for that error. I cannot reproduce it, thus no change to fix it.
