### ISSUE TITLE
Setting Uncore Frequency

### ISSUE THREAD

**Issue by hofm** [RRZE-HPC/likwid#81]
[feature request] Add capability to set min/max Uncore clock frequency.

**Comment by TomTheBear** [comment]
Added in commit https://github.com/RRZE-HPC/likwid/commit/3274ee9e853f942086ae0c2df532a7fb7c20c610

One problem are the limits for the Uncore frequency. There is no register or similar that can be used as source for the supported range. Currently, the given frequency must be in range: minmal CPU clock to maximal CPU clock in Turbo mode. There are probably some frequencies in that range that are not supported by the PCU. If you are unsure whether your setting worked or not, please verify it with the UNCORE_CLOCK event.
