### ISSUE TITLE
Support for Broadwell  E3-1265L v4.

### ISSUE THREAD

**Issue by pouchet** [RRZE-HPC/likwid#85]
Hello,

I'm trying to measure power on a broadwell E3-1265L v4: https://ark.intel.com/products/88041/Intel-Xeon-Processor-E3-1265L-v4-6M-Cache-2_30-GHz
Intel PCM (github version) doesn't work out of the box because the processor is "not supported", I tried fooling the tool a bit thinking it is a supported processor, but no luck.
I tried likwid (github version) just now, it builds w/o any problem, but I get the message
[0]@broadwellx1:~/tools/likwid/likwid>/usr/local/bin/likwid-powermeter
The Unknown Intel Processor does not support reading power data

So, my questions:
- is that expected? Or is likwid supposed to support this processor? I saw a lot of broadwell-related patches in the changelog, so I'm wondering. FYI on Intel PCM it is recognized as "BROADWELL_XEON_E3".
- Assuming likwid doesn't support this processor yet, do you have any intuition if adding support for it would be simply about making it recognized as one of the existing broadwell processor? I've tried a bit that road for a few minutes, casting it as a broadwell and broadwell d, but did not have any luck (note my attempt patch may be incomplete and thus the reason for not working), I keep getting:

Cannot gather values from MSR_RAPL_POWER_UNIT, deactivating RAPL support
The Intel (Xeon D) Broadwell processor does not support reading power data

Many thanks,

++

**Comment by TomTheBear** [comment]
Hi,
It seems I overlooked one model number of Intel Broadwell CPUs. So, LIKWID is supposed to support it. 

Casting the model number to another architecture does not work or is at least very difficult, you have to trick the kernel to identify the system as another architecture.

I attached a patch that should add support for the E3 Broadwell. Can you please test it with a fresh `git clone` and apply the patch with `git apply --ignore-space-change --ignore-whitespace <PATCH>`. If it works, I commit it to the repository.
[likwid-broadwell-e3-add.zip](https://github.com/RRZE-HPC/likwid/files/813272/likwid-broadwell-e3-add.zip)

**Comment by pouchet** [comment]
Thanks for the quick reply. It seems to work, at least all likwid commands I tried worked w/o any error. I need to double-check the values I get, though, to confirm I get the expected data, but as far as I can tell I get meaningful data. For ex. below what I get for running a long DGEMM. The patch can be applied IMHO.

Many thanks! 

[0]broadwellx1:~/projects/test>likwid-powermeter ./mm.out
--------------------------------------------------------------------------------
CPU name:	Intel(R) Xeon(R) CPU E3-1265L v4 @ 2.30GHz
CPU type:	Intel Xeon E3 Broadwell processor
CPU clock:	2.30 GHz
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Runtime: 9.52367 s
Measure for socket 0 on CPU 0
Domain PKG:
Energy consumed: 303.738 Joules
Power consumed: 31.893 Watt
Domain PP0:
Energy consumed: 282.718 Joules
Power consumed: 29.6858 Watt
Domain PP1:
Energy consumed: 0 Joules
Power consumed: 0 Watt
Domain DRAM:
Energy consumed: 22.6331 Joules
Power consumed: 2.37651 Watt
--------------------------------------------------------------------------------

**Comment by TomTheBear** [comment]
Thanks for testing it. I was unsure about the energy unit for the DRAM domain. The desktop Broadwell uses a different one as Broadwell EP and Broadwell D. The E3 chips are commonly more like the desktop, that's why the current energy unit is for Desktop Broadwell. With the server DRAM energy unit, the values for DRAM would be 1/4 of the current values, a little low in my opinion. Also the Linux kernel internal RAPL interface uses the energy unit of the desktop.
