### ISSUE TITLE
Reading OFFCORE_RESPONSE counters

### ISSUE THREAD

**Issue by mradulovic** [RRZE-HPC/likwid#88]
Hello,

I've been trying to read OFFCORE_RESPONSE counters with OFFCORE_RESPONSE_x_OPTIONS event but I constantly read zeroes.
Maybe I'm doing something wrong.
Here's the example of my event:
OFFCORE_RESPONSE_1_OPTIONS:PMC4:MATCH0=0x1:MATCH1=0x6004
I'm using likwid 4.0.
My machine is SandyBridge, E5-2670.

Thanks,
Milan

**Comment by TomTheBear** [comment]
Is your system running without HyperThreading? If HT is enabled, there is no counter PMC4. If HT is disabled, the counter should exist.

When I look at your masks, you want the register to look like: 0x60040001 = (bits 0, 18, 29, 30)
These bits refer to:
Request: DEMAND_DATA_RD (Bit 0)
Response: LLC_HIT_M (Bit 18) and two unnamed bits 29 and 30 (part of the L3_MISS_REMOTE_DRAM group)
[Bit definitions](https://download.01.org/perfmon/JKT/Jaketown_matrix_bit_definitions_V20.json)
So, you want data reads that hit a modified cache line in another L3 and part of all misses that go to remote DRAM. I think your mask is not valid.

If you want to test if it works for your system at all, simply try the L3CACHE group on SandyBridge, it uses both OFFCORE_RESPONSE events.

**Comment by mradulovic** [comment]
Hello Tom,
Thanks for your answer.
You are right, my mask was wrong, it should be 0x600400001 - I missed last zero in match1 parameter.
And I tried with PMC3 and it worked!
It seems it doesnt support PMC4 although HT is disabled.

**Comment by TomTheBear** [comment]
You're welcome and congratulation.
I know, fiddling around with these bits is not nice but I don't want to integrate the names, it would require quite some changes in the event option code.

If you run `likwid-perfctr -e` and the PMC4 counter is listed, it should work. You can also add `-V 1` on command line for increased verbosity (1 for little bit verbose, 2 for quite some output and 3 for developer output). It would write a message like this:
```
$ likwid-perfctr -C 0 -V 1 -g UOPS_RETIRED_ANY:PMC4 hostname
[...]
DEBUG - [perfmon_addEventSet:1610] Cannot access counter register PMC4
```

**Comment by mradulovic** [comment]
I will have it on my list, thanks!
