### ISSUE TITLE
Request for information regarding LIKWID for ARM systems

### ISSUE THREAD

**Issue by mariam-umar** [RRZE-HPC/likwid#90]
Does LIKWID have the ability to extend to ARM based system? If so, would you please point me to resources regarding that?

**Comment by TomTheBear** [comment]
At the moment, LIKWID doesn't have the ability to run on ARM based systems. There is an ARMv7 branch in the repository but I don't think it is fully functional and even if, the port was made with an older version.
For ARMv8, I'm working on a port but I have little time currently and the ARMv8 test system is not functional at the moment but we are working on it.

**Comment by jjrob13** [comment]
Thanks for merging armv8 support in d944510e1092ddf9a2364353339ea3db6176ee01!

I was wondering if you could share some more details about your build/validation setup.  I am trying to get it up and running on a cortex a53 system, and I'm trying to use gcc-linaro-4.9 for cross-compilation, but I am having various build-related troubles.

Any guidance is much appreciated.

**Comment by TomTheBear** [comment]
It's already quite some time ago that I did that. I used an A57 ARM CPU but I'm not sure right now whether I had to cross-compile or compiled it directly on the platform. My intention was that users just need to change the `COMPILER` setting in config.mk to `GCCARMv7` or `GCCARMv8`. The backend is perf_event. I have a native backend for ARMv7 and 8 as well but there are issues that caused me to write the perf_event backend.
If you have trouble compiling it, please open a new issue with more details. I'll try to fix it but access to ARM-based systems is currently limited.

**Comment by TomTheBear** [comment]
And I found a Cortex A15 (BananaPi). I added the event definitions and now this architecture works as well.
```
$ likwid-perfctr -C 0 -g MEM hostname
|    Memory bandwidth [MBytes/s]    | 29.9289 |
|    Memory data volume [GBytes]    |  0.0002 |
```
