### ISSUE TITLE
likwid-bench 4.2.0 not compatible with Summit Ridge arch

### ISSUE THREAD

**Issue by rrzeschorscherl** [RRZE-HPC/likwid#92]
unrz55@summitridge1:~$ module load likwid/4.2.0
unrz55@summitridge1:~$ likwid-bench -t update_avx -w S0:120kB:1
ERROR - [./src/cpuid.c:689] Processor is not supported

The older 4.1.2 works fine.

**Comment by TomTheBear** [comment]
Interestingly, there is no file named src/cpuid.c in 4.2.0. The last version that had that file was 3.1.3 which did the topology recognition itself and doesn't know the model number of the AMD Ryzen. I tried it on summitridge and had no problem with 4.2.0.

**Comment by rrzeschorscherl** [comment]
OK, my mistake. 4.2.0 works fine (accidentally used an old likwid-bench that happened to be lurking in my PATH).
