### ISSUE TITLE
likwid-bench 4.2.0 "Cycle Clock" incorrect?

### ISSUE THREAD

**Issue by rrzeschorscherl** [RRZE-HPC/likwid#93]
unrz55@e0108:~$ likwid-setFrequencies -f 1.2
unrz55@e0108:~$ likwid-bench -t update_avx -w S0:120kB:1
Warning: Sanitizing vector length to a multiple of the loop stride 16 and thread count 1 from 15000 elements (240000 bytes) to 14992 elements (239872 bytes)
Allocate: Process running on core 0 (Domain S0) - Vector length 14992/119936 Offset 0 Alignment 512
--------------------------------------------------------------------------------
LIKWID MICRO BENCHMARK
Test: update_avx
--------------------------------------------------------------------------------
Using 1 work groups
Using 1 threads
--------------------------------------------------------------------------------
Group: 0 Thread 0 Global Thread 0 running on core 0 - Vector length 14992 Offset 0
--------------------------------------------------------------------------------
Cycles:                 3220266214
CPU Clock:              2200036822
Cycle Clock:            2200036822

Should the last two numbers not be different when the clock frequency is set to something other than the base clock speed?

**Comment by TomTheBear** [comment]
No, on x86 there is no difference between the (nominal) CPU clock and the clock which is used to increment the cycles counter. On x86, both values are the invariant TSC clock. I understand that the name CPU clock is somewhat misleading. 
These outputs were added for other architectures like POWER8 where the cycles clock is 512 MHz while the CPU clock (on my test machine) is 3GHz. So, if you measure cycles and want to have CPU clock cycles, the cycles value needs to be scaled.
It would be possible to output the current frequency but for which CPU? You need it for all CPUs that took part in the benchmarking run. Moreover, the value would only be reliable when the frequency is fixed. With frequency governors like ondemand you can output nearly anything there.

**Comment by rrzeschorscherl** [comment]
So do I understand correctly that the number of cycles per update (further down in the output) is calculated using the invariant CPU clock, and needs to be corrected by the ratio of nominal and actual clock speed? How about the bandwidth output? Is the bandwidth output based on wall-clock time?

**Comment by TomTheBear** [comment]
Yes, indeed. That's also why this clock is printed out. This is true for cycles per update and cycles per cache line. If you need the actual CPU clock values, you have to calculate them yourself after measuring with likwid-perfctr around likwid-bench.
The bandwidth is calculated based on runtime which is calculated from the invariant clock cycles (TSC). You don't need to scale it unless you want something like bytes per actual CPU cycle.
