### ISSUE TITLE
Question about the perf_event support

### ISSUE THREAD

**Issue by mcolmant** [RRZE-HPC/likwid#96]
Hi,

First of all, I would like to thank you for this awesome library and for your reactivity!
I have one question regarding the perf_event support.
I have a specific need regarding this support.
As you may know, the file descriptor are opened with the `perf_event_open` function while using this interface.
```
int perf_event_open(struct perf_event_attr *attr,
                           pid_t pid, int cpu, int group_fd,
                           unsigned long flags);
```
I already looked into the code and this function is wrapped inside `perf_*_setup` functions.
What I would like to do is to adapt the code for allowing to use of the `pid` and `flags` parameters.
The main modification will be located to the `perfmon_setupCountersThread`, but will lead to a lot of impacts.
Maybe you will have some advices to limit this impact.

I already wrote something, are you interested by such feature?

**Comment by TomTheBear** [comment]
Hi,

In general, I have no problem when perf_event is "limited" to a PID and the flags are set as long as it is configurable. The only concern I have is that it changes the measurement behavior. Normal LIKWID measures anything that runs on the selected cores. Perf_event with PID measures only PID and, if activated, the child processes. 

I would recommend to define new event options for PID and flags when compiled with perf_event support. Consequently, you need a loop in perfmon_setupCounterThread to search for the options and use them for the subsequent perf_event_open call. This limits the changes basically on the perf_event backend.

**Comment by mcolmant** [comment]
Hello,

Thanks for your quick answer!
I understand what you mean. 
I agree, it will be more elegant this way :-)
I'm working on it, and will come back with a PR (if you are interested for such feature in likwid).

**Comment by TomTheBear** [comment]
Hi,
you're welcome. Thanks for your attempt to enrich LIKWID. 
I'm very interested, it is always helpful to support more measurement backends. If you are experienced in the use of perf_event, it would be helpful to check the uncore support. I'm not really sure whether all the code is working for the uncore units, I only checked a few units and events.

**Comment by mcolmant** [comment]
I don't have the time to test everything right now, but if I find something, I will let you know.
Right now, it seems to work well.

**Comment by mcolmant** [comment]
Hello, 

One last question. I would like to use likwid (with this new support) to monitor several processes at runtime.
It seems that likwid does not support this type of monitoring (`perfmon_perfevent.h` uses a struct that allows to only have one counter per core).
However, when I look at the code in `perfmon.c`, some functions are provided to start/stop/read counters at the level of a group (`perfmon_startGroupCounters`, ...), but not exposed in the header.
When the effective callbacks are called, the groupId parameter is lost and we can only have information about the active group (actually, the last setup).

I tried to write something, but it seems that likwid was not designed for such purpose.

Thanks,

**Comment by TomTheBear** [comment]
Hi,

The start/stop/read group counters are not exposed because you commonly want to start/stop/read the group you have set up previously by `perfmon_setupCounters(groupid)`. Of course it doesn't harm if you run group1 and read group2 but the results will be meaningless because you don't know if the group is running and if it is running, which event is programmed? This is related to the _non_ perf_event method.

I'm not sure whether I fully understand your problem. You want to register multiple event sets (with different PIDs) and measure them simultaneously? This is a possibility since we enhanced the perf_event support but currently the structures are not made for this as you noted correctly. This is a result of the different measurement behavior. Although you should be able measure multiple event sets with the original MSR/PCI based implementation as long as the event sets don't overlap, it is not what LIKWID was thought for. But the changes shouldn't be too difficult to support that. It's mainly the export of some functions and extending the `cpu_event_fds` array to have one per group or PID.

**Comment by mcolmant** [comment]
Hello,

Yes, this is exactly what I want to do. With the perf_event support, I would like to monitor different running processes at runtime, thus calling the perfmon_read function concurrently.
I did the change but given that I'm not a C expert, I'm not sure that is the best solution.
Can I only change the callbacks (I need to pass the groupId) without impacting the original behavior?

Thanks,

**Comment by TomTheBear** [comment]
Hi,
yes you can. In the default case you should hand over groupSet->activeGroup (and check before that it is greater than 0) and then provide some extra interfaces which allows to select a group ID.

**Comment by TomTheBear** [comment]
I updated the perf_event support in the master branch (also in draft release 4.3.0). LIKWID still assumes the you just measure a single application, so until now no fix for your last problem. What you can do is to call likwid multiple times:
likwid-perfctr -c 0-7 -g L3 --perfpid <pid1> --perfflags 0x0 -S 10s &
likwid-perfctr -c 0-7 -g L2 --perfpid <pid2> -S 10s
This allows you to measure different groups and different PIDs. perfflags defaults to 0x0, so you don't need it in most cases.
For normal mode you have to set --execpid to set perfpid to the PID of the started application.
